let katySV = document.querySelector ("#katy1");
let brassiusSV = document.querySelector ("#brassius1");
let ionoSV = document.querySelector ("#iono1");
let kofuSV = document.querySelector ("#kofu1");
let larrySV = document.querySelector ("#larry1");
let rymeSV = document.querySelector ("#ryme1");
let tulipSV = document.querySelector ("#tulip1");
let grushaSV = document.querySelector ("#grusha1");
let rikaSV = document.querySelector ("#rika1");
let poppySV = document.querySelector ("#poppy1");
let larryE4SV = document.querySelector ("#larry2");
let hasselSV = document.querySelector ("#hassel1");
let geetaSV = document.querySelector ("#geeta1");
let nemonaGSV = document.querySelector ("#nemona1_g");
let nemonaFSV = document.querySelector ("#nemona1_f");
let nemonaWSV = document.querySelector ("#nemona1_w");
let giacomoSV = document.querySelector ("#giacomo1");
let melaSV = document.querySelector ("#mela1");
let atticusSV = document.querySelector ("#atticus1");
let ortegaSV = document.querySelector ("#ortega1");
let eriSV = document.querySelector ("#eri1");
let clavellGSV = document.querySelector ("#clavell1_g");
let clavellFSV = document.querySelector ("#clavell1_f");
let clavellWSV = document.querySelector ("#clavell1_w");
let cassiopeiaSV = document.querySelector ("#cassiopeia1");
let arvenSV = document.querySelector ("#arven1");
let sadaSV = document.querySelector ("#sada1");
let turoSV = document.querySelector ("#turo1");

let sv_trainers = [
    {
        namea : "Nymble",
        levela : "LV: 14",
        typea : "Type: Bug",
        abilitya: "Ability: Swarm",
        itema : "Item: None",
        hpa : "HP: 36",
        atka : "Atk: 20",
        defa : "Def: 19",
        spatka : "Sp. Atk: 13",
        spdefa : "Sp. Def: 14",
        spda : "Spd: 20",
        move1a : "-Struggle Bug",
        move2a : "-Double Kick",
        move3a : "",
        move4a : "",

        nameb : "Tarountula",
        levelb : "LV: 14",
        typeb : "Type: Bug",
        abilityb: "Ability: Insomnia",
        itemb : "Item: None",
        hpb : "HP: 36",
        atkb : "Atk: 19",
        defb : "Def: 20",
        spatkb : "Sp. Atk: 15",
        spdefb : "Sp. Def: 19",
        spdb : "Spd: 13",
        move1b : "-Bug Bite",
        move2b : "-Assurance",
        move3b : "",
        move4b : "",

        namec : "Teddiursa",
        levelc : "LV: 15",
        typec : "Type: Bug (Tera)",
        abilityc: "Ability: Pickup",
        itemc : "Item: None",
        hpc : "HP: 56",
        atkc : "Atk: 32",
        defc : "Def: 23",
        spatkc : "Sp. Atk: 23",
        spdefc : "Sp. Def: 23",
        spdc : "Spd: 20",
        move1c : "-Fury Cutter",
        move2c : "-Fury Swipes",
        move3c : "",
        move4c : "",
    },

    {
        namea : "Petilil",
        levela : "LV: 16",
        typea : "Type: Grass",
        abilitya: "Ability: Own Tempo",
        itema : "Item: None",
        hpa : "HP: 43",
        atka : "Atk: 19",
        defa : "Def: 24",
        spatka : "Sp. Atk: 30",
        spdefa : "Sp. Def: 24",
        spda : "Spd: 17",
        move1a : "-Sleep Powder",
        move2a : "-Mega Drain",
        move3a : "",
        move4a : "",

        nameb : "Smoliv",
        levelb : "LV: 16",
        typeb : "Type: Grass/Normal",
        abilityb: "Ability: Early Bird",
        itemb : "Item: None",
        hpb : "HP: 42",
        atkb : "Atk: 19",
        defb : "Def: 22",
        spatkb : "Sp. Atk: 26",
        spdefb : "Sp. Def: 24",
        spdb : "Spd: 17",
        move1b : "-Tackle",
        move2b : "-Razor Leaf",
        move3b : "",
        move4b : "",

        namec : "Sudowoodo",
        levelc : "LV: 17",
        typec : "Type: Grass (Tera)",
        abilityc: "Ability: Sturdy",
        itemc : "Item: None",
        hpc : "HP: 65",
        atkc : "Atk: 43",
        defc : "Def: 48",
        spatkc : "Sp. Atk: 19",
        spdefc : "Sp. Def: 31",
        spdc : "Spd: 19",
        move1c : "-Trailblaze",
        move2c : "-Rock Throw",
        move3c : "",
        move4c : "",
    },

    {
        namea : "Wattrel",
        levela : "LV: 23",
        typea : "Type: Electric/Flying",
        abilitya: "Ability: Wind Power",
        itema : "Item: None",
        hpa : "HP: 56",
        atka : "Atk: 28",
        defa : "Def: 25",
        spatka : "Sp. Atk: 34",
        spdefa : "Sp. Def: 28",
        spda : "Spd: 41",
        move1a : "-Pluck",
        move2a : "-Quick Attack",
        move3a : "-Spark",
        move4a : "",

        nameb : "Bellibolt",
        levelb : "LV: 23",
        typeb : "Type: Electric",
        abilityb: "Ability: Electromorphosis",
        itemb : "Item: None",
        hpb : "HP: 87",
        atkb : "Atk: 39",
        defb : "Def: 51",
        spatkb : "Sp. Atk: 56",
        spdefb : "Sp. Def: 47",
        spdb : "Spd: 30",
        move1b : "-Spark",
        move2b : "-Water Gun",
        move3b : "",
        move4b : "",

        namec : "Luxio",
        levelc : "LV: 23",
        typec : "Type: Electric",
        abilityc: "Ability: Intimidate",
        itemc : "Item: None",
        hpc : "HP: 65",
        atkc : "Atk: 48",
        defc : "Def: 32",
        spatkc : "Sp. Atk: 37",
        spdefc : "Sp. Def: 32",
        spdc : "Spd: 37",
        move1c : "-Spark",
        move2c : "-Bite",
        move3c : "",
        move4c : "",

        named : "Mismagius",
        leveld : "LV: 24",
        typed : "Type: Electric (Tera)",
        abilityd: "Ability: Levitate",
        itemd : "Item: None",
        hpd : "HP: 87",
        atkd : "Atk: 41",
        defd : "Def: 41",
        spatkd : "Sp. Atk: 63",
        spdefd : "Sp. Def: 63",
        spdd : "Spd: 63",
        move1d : "-Charge Beam",
        move2d : "-Hex",
        move3d : "-Confuse Ray",
        move4d : "",
    },

    {
        namea : "Veluza",
        levela : "LV: 29",
        typea : "Type: Water/Psychic",
        abilitya: "Ability: Mold Breaker",
        itema : "Item: None",
        hpa : "HP: 97",
        atka : "Atk: 69",
        defa : "Def: 53",
        spatka : "Sp. Atk: 56",
        spdefa : "Sp. Def: 48",
        spda : "Spd: 51",
        move1a : "-Slash",
        move2a : "-Pluck",
        move3a : "-Aqua Cutter",
        move4a : "",

        nameb : "Wugtrio",
        levelb : "LV: 29",
        typeb : "Type: Water",
        abilityb: "Ability: Gooey",
        itemb : "Item: None",
        hpb : "HP: 65",
        atkb : "Atk: 68",
        defb : "Def: 39",
        spatkb : "Sp. Atk: 39",
        spdefb : "Sp. Def: 51",
        spdb : "Spd: 80",
        move1b : "-Mud-Slap",
        move2b : "-Water Pulse",
        move3b : "-Headbutt",
        move4b : "",

        namec : "Crabominable",
        levelc : "LV: 30",
        typec : "Type: Water (Tera)",
        abilityc: "Ability: Iron Fist",
        itemc : "Item: None",
        hpc : "HP: 124",
        atkc : "Atk: 91",
        defc : "Def: 58",
        spatkc : "Sp. Atk: 49",
        spdefc : "Sp. Def: 52",
        spdc : "Spd: 38",
        move1c : "-Crabhammer",
        move2c : "-Rock Smash",
        move3c : "-Slam",
        move4c : "",
    },

    {
        namea : "Komala",
        levela : "LV: 35",
        typea : "Type: Normal",
        abilitya: "Ability: Comatose",
        itema : "Item: None",
        hpa : "HP: 97",
        atka : "Atk: 92",
        defa : "Def: 57",
        spatka : "Sp. Atk: 64",
        spdefa : "Sp. Def: 78",
        spda : "Spd: 57",
        move1a : "-Yawn",
        move2a : "-Sucker Punch",
        move3a : "-Slam",
        move4a : "",

        nameb : "Dudunsparce",
        levelb : "LV: 35",
        typeb : "Type: Normal",
        abilityb: "Ability: Serene Grace",
        itemb : "Item: None",
        hpb : "HP: 139",
        atkb : "Atk: 82",
        defb : "Def: 68",
        spatkb : "Sp. Atk: 71",
        spdefb : "Sp. Def: 64",
        spdb : "Spd: 50",
        move1b : "-Hyper Drill",
        move2b : "-Drill Run",
        move3b : "-Glare",
        move4b : "",

        namec : "Staraptor",
        levelc : "LV: 36",
        typec : "Type: Normal (Tera)",
        abilityc: "Ability: Intimidate",
        itemc : "Item: None",
        hpc : "HP: 138",
        atkc : "Atk: 100",
        defc : "Def: 64",
        spatkc : "Sp. Atk: 50",
        spdefc : "Sp. Def: 57",
        spdc : "Spd: 86",
        move1c : "-Facade",
        move2c : "-Aerial Ace",
        move3c : "",
        move4c : "",
    },

    {
        namea : "Banette",
        levela : "LV: 41",
        typea : "Type: Ghost",
        abilitya: "Ability: Insomnia",
        itema : "Item: None",
        hpa : "HP: 111",
        atka : "Atk: 107",
        defa : "Def: 66",
        spatka : "Sp. Atk: 81",
        spdefa : "Sp. Def: 64",
        spda : "Spd: 66",
        move1a : "-Icy Wind",
        move2a : "-Sucker Punch",
        move3a : "-Shadow Sneak",
        move4a : "",

        nameb : "Mimikyu",
        levelb : "LV: 41",
        typeb : "Type: Ghost/Fairy",
        abilityb: "Ability: Disguise",
        itemb : "Item: None",
        hpb : "HP: 104",
        atkb : "Atk: 87",
        defb : "Def: 78",
        spatkb : "Sp. Atk: 54",
        spdefb : "Sp. Def: 99",
        spdb : "Spd: 91",
        move1b : "-Light Screen",
        move2b : "-Shadow Sneak",
        move3b : "-Slash",
        move4b : "",

        namec : "Houndstone",
        levelc : "LV: 41",
        typec : "Type: Ghost",
        abilityc: "Ability: Sand Rush",
        itemc : "Item: None",
        hpc : "HP: 118",
        atkc : "Atk: 96",
        defc : "Def: 95",
        spatkc : "Sp. Atk: 54",
        spdefc : "Sp. Def: 92",
        spdc : "Spd: 68",
        move1c : "-Play Rough",
        move2c : "-Crunch",
        move3c : "-Phantom Force",
        move4c : "",

        named : "Toxtricity",
        leveld : "LV: 42",
        typed : "Type: Ghost (Tera)",
        abilityd: "Ability: Punk Rock",
        itemd : "Item: None",
        hpd : "HP: 151",
        atkd : "Atk: 97",
        defd : "Def: 74",
        spatkd : "Sp. Atk: 111",
        spdefd : "Sp. Def: 74",
        spdd : "Spd: 98",
        move1d : "-Discharge",
        move2d : "-Hex",
        move3d : "-Hyper Voice",
        move4d : "",
    },

    {
        namea : "Farigiraf",
        levela : "LV: 44",
        typea : "Type: Normal/Psychic",
        abilitya: "Ability: Armor Tail",
        itema : "Item: None",
        hpa : "HP: 168",
        atka : "Atk: 93",
        defa : "Def: 75",
        spatka : "Sp. Atk: 110",
        spdefa : "Sp. Def: 75",
        spda : "Spd: 66",
        move1a : "-Crunch",
        move2a : "-Zen Headbutt",
        move3a : "-Reflect",
        move4a : "",

        nameb : "Gardevoir",
        levelb : "LV: 44",
        typeb : "Type: Psychic/Fairy",
        abilityb: "Ability: Synchronize",
        itemb : "Item: None",
        hpb : "HP: 122",
        atkb : "Atk: 71",
        defb : "Def: 71",
        spatkb : "Sp. Atk: 123",
        spdefb : "Sp. Def: 115",
        spdb : "Spd: 84",
        move1b : "-Psychic",
        move2b : "-Dazzling Gleam",
        move3b : "-Shadow Ball",
        move4b : "",

        namec : "Espathra",
        levelc : "LV: 44",
        typec : "Type: Psychic",
        abilityc: "Ability: Opportunist",
        itemc : "Item: None",
        hpc : "HP: 146",
        atkc : "Atk: 66",
        defc : "Def: 66",
        spatkc : "Sp. Atk: 102",
        spdefc : "Sp. Def: 66",
        spdc : "Spd: 106",
        move1c : "-Psychic",
        move2c : "-Quick Attack",
        move3c : "-Shadow Ball",
        move4c : "",

        named : "Florges",
        leveld : "LV: 45",
        typed : "Type: Psychic (Tera)",
        abilityd: "Ability: Flower Veil",
        itemd : "Item: None",
        hpd : "HP: 164",
        atkd : "Atk: 74",
        defd : "Def: 77",
        spatkd : "Sp. Atk: 117",
        spdefd : "Sp. Def: 154",
        spdd : "Spd: 83",
        move1d : "-Psychic",
        move2d : "-Moonblast",
        move3d : "-Petal Blizzard",
        move4d : "",
    },

    {
        namea : "Frosmoth",
        levela : "LV: 47",
        typea : "Type: Ice/Bug",
        abilitya: "Ability: Shield Dust",
        itema : "Item: None",
        hpa : "HP: 132",
        atka : "Atk: 75",
        defa : "Def: 70",
        spatka : "Sp. Atk: 131",
        spdefa : "Sp. Def: 99",
        spda : "Spd: 75",
        move1a : "-Blizzard",
        move2a : "-Bug Buzz",
        move3a : "-Tailwind",
        move4a : "",

        nameb : "Beartic",
        levelb : "LV: 47",
        typeb : "Type: Ice",
        abilityb: "Ability: Snow Cloak",
        itemb : "Item: None",
        hpb : "HP: 155",
        atkb : "Atk: 136",
        defb : "Def: 89",
        spatkb : "Sp. Atk: 80",
        spdefb : "Sp. Def: 89",
        spdb : "Spd: 61",
        move1b : "-Aqua Jet",
        move2b : "-Icicle Crash",
        move3b : "-Earthquake",
        move4b : "",

        namec : "Cetitan",
        levelc : "LV: 47",
        typec : "Type: Ice",
        abilityc: "Ability: Thick Fat",
        itemc : "Item: None",
        hpc : "HP: 226",
        atkc : "Atk: 120",
        defc : "Def: 75",
        spatkc : "Sp. Atk: 56",
        spdefc : "Sp. Def: 66",
        spdc : "Spd: 83",
        move1c : "-Ice Spinner",
        move2c : "-Liquidation",
        move3c : "-Ice Shard",
        move4c : "",

        named : "Altaria",
        leveld : "LV: 48",
        typed : "Type: Ice (Tera)",
        abilityd: "Ability: Natural Cure",
        itemd : "Item: None",
        hpd : "HP: 172",
        atkd : "Atk: 84",
        defd : "Def: 103",
        spatkd : "Sp. Atk: 84",
        spdefd : "Sp. Def: 117",
        spdd : "Spd: 93",
        move1d : "-Ice Beam",
        move2d : "-Dragon Pulse",
        move3d : "-Moonblast",
        move4d : "-Hurricane",
    },

    {
        namea : "Whiscash",
        levela : "LV: 57",
        typea : "Type: Oblivious",
        abilitya: "Ability: Water/Ground",
        itema : "Item: None",
        hpa : "HP: 203",
        atka : "Atk: 105",
        defa : "Def: 99",
        spatka : "Sp. Atk: 103",
        spdefa : "Sp. Def: 97",
        spda : "Spd: 84",
        move1a : "-Muddy Water",
        move2a : "-Earth Power",
        move3a : "-Blizzard",
        move4a : "-Future Sight",

        nameb : "Camerupt",
        levelb : "LV: 57",
        typeb : "Type: Fire/Ground",
        abilityb: "Ability: Magma Armor",
        itemb : "Item: None",
        hpb : "HP: 158",
        atkb : "Atk: 130",
        defb : "Def: 96",
        spatkb : "Sp. Atk: 136",
        spdefb : "Sp. Def: 101",
        spdb : "Spd: 62",
        move1b : "-Earth Power",
        move2b : "-Fire Blast",
        move3b : "-Flash Cannon",
        move4b : "-Yawn",

        namec : "Donphan",
        levelc : "LV: 57",
        typec : "Type: Ground",
        abilityc: "Ability: Sturdy",
        itemc : "Item: None",
        hpc : "HP: 181",
        atkc : "Atk: 153",
        defc : "Def: 153",
        spatkc : "Sp. Atk: 84",
        spdefc : "Sp. Def: 84",
        spdc : "Spd: 73",
        move1c : "-Earthquake",
        move2c : "-Stone Edge",
        move3c : "-Iron Head",
        move4c : "-Poison Jab",

        named : "Dugtrio",
        leveld : "LV: 57",
        typed : "Type: Ground",
        abilityd: "Ability: Sand Veil",
        itemd : "Item: None",
        hpd : "HP: 118",
        atkd : "Atk: 130",
        defd : "Def: 73",
        spatkd : "Sp. Atk: 73",
        spdefd : "Sp. Def: 96",
        spdd : "Spd: 153",
        move1d : "-Earthquake",
        move2d : "-Rock Slide",
        move3d : "-Sucker Punch",
        move4d : "-Sandstorm",

        namee : "Clodsire",
        levele : "LV: 58",
        typee : "Type: Ground (Tera)",
        abilitye: "Ability: Water Absorb",
        iteme : "Item: None",
        hpe : "HP: 269",
        atke : "Atk: 106",
        defe : "Def: 89",
        spatke : "Sp. Atk: 71",
        spdefe : "Sp. Def: 135",
        spde : "Spd: 42",
        move1e : "-Earthquake",
        move2e : "-Liquidation",
        move3e : "-Toxic",
        move4e : "-Protect",
    },

    {
        namea : "Copperajah",
        levela : "LV: 58",
        typea : "Type: Steel",
        abilitya: "Ability: Sheer Force",
        itema : "Item: None",
        hpa : "HP: 221",
        atka : "Atk: 167",
        defa : "Def: 96",
        spatka : "Sp. Atk: 109",
        spdefa : "Sp. Def: 96",
        spda : "Spd: 51",
        move1a : "-High Horsepower",
        move2a : "-Play Rough",
        move3a : "-Heavy Slam",
        move4a : "-Stealth Rock",

        nameb : "Magnezone",
        levelb : "LV: 58",
        typeb : "Type: Electric/Steel",
        abilityb: "Ability: Sturdy",
        itemb : "Item: None",
        hpb : "HP: 160",
        atkb : "Atk: 97",
        defb : "Def: 150",
        spatkb : "Sp. Atk: 167",
        spdefb : "Sp. Def: 121",
        spdb : "Spd: 86",
        move1b : "-Discharge",
        move2b : "-Flash Cannon",
        move3b : "-Light Screen",
        move4b : "-Tri Attack",

        namec : "Bronzong",
        levelc : "LV: 58",
        typec : "Type: Steel/Psychic",
        abilityc: "Ability: Levitate",
        itemc : "Item: None",
        hpc : "HP: 157",
        atkc : "Atk: 119",
        defc : "Def: 151",
        spatkc : "Sp. Atk: 108",
        spdefc : "Sp. Def: 151",
        spdc : "Spd: 54",
        move1c : "-Iron Head",
        move2c : "-Zen Headbutt",
        move3c : "-Rock Blast",
        move4c : "-Earthquake",

        named : "Corviknight",
        leveld : "LV: 58",
        typed : "Type: Flying/Steel",
        abilityd: "Ability: Pressure",
        itemd : "Item: None",
        hpd : "HP: 193",
        atkd : "Atk: 117",
        defd : "Def: 138",
        spatkd : "Sp. Atk: 78",
        spdefd : "Sp. Def: 115",
        spdd : "Spd: 94",
        move1d : "-Brave Bird",
        move2d : "-Iron Head",
        move3d : "-Body Press",
        move4d : "-Iron Defense",

        namee : "Tinkaton",
        levele : "LV: 59",
        typee : "Type: Steel (Tera)",
        abilitye: "Ability: Mold Breaker",
        iteme : "Item: None",
        hpe : "HP: 221",
        atke : "Atk: 108",
        defe : "Def: 110",
        spatke : "Sp. Atk: 102",
        spdefe : "Sp. Def: 143",
        spde : "Spd: 130",
        move1e : "-Play Rough",
        move2e : "-Gigaton Hammer",
        move3e : "-Brick Break",
        move4e : "-Stone Edge",
    },

    {
        namea : "Tropius",
        levela : "LV: 59",
        typea : "Type: Grass/Flying",
        abilitya: "Ability: Chlorophyll",
        itema : "Item: None",
        hpa : "HP: 197",
        atka : "Atk: 97",
        defa : "Def: 114",
        spatka : "Sp. Atk: 101",
        spdefa : "Sp. Def: 119",
        spda : "Spd: 76",
        move1a : "-Air Slash",
        move2a : "-Solar Beam",
        move3a : "-Dragon Pulse",
        move4a : "-Sunny Day",

        nameb : "Oricorio (Pom-Pom)",
        levelb : "LV: 59",
        typeb : "Type: Electric/Flying",
        abilityb: "Ability: Dancer",
        itemb : "Item: None",
        hpb : "HP: 169",
        atkb : "Atk: 99",
        defb : "Def: 99",
        spatkb : "Sp. Atk: 132",
        spdefb : "Sp. Def: 99",
        spdb : "Spd: 126",
        move1b : "-Revelation Dance",
        move2b : "-Air Slash",
        move3b : "-Teeter Dance",
        move4b : "-Icy Wind",

        namec : "Altaria",
        levelc : "LV: 59",
        typec : "Type: Dragon/Flying",
        abilityc: "Ability: Natural Cure",
        itemc : "Item: None",
        hpc : "HP: 169",
        atkc : "Atk: 99",
        defc : "Def: 123",
        spatkc : "Sp. Atk: 99",
        spdefc : "Sp. Def: 140",
        spdc : "Spd: 111",
        move1c : "-Moonblast",
        move2c : "-Flamethrower",
        move3c : "-Ice Beam",
        move4c : "-Dragon Pulse",

        named : "Staraptor",
        leveld : "LV: 59",
        typed : "Type: Normal/Flying",
        abilityd: "Ability: Intimidate",
        itemd : "Item: None",
        hpd : "HP: 181",
        atkd : "Atk: 158",
        defd : "Def: 99",
        spatkd : "Sp. Atk: 75",
        spdefd : "Sp. Def: 87",
        spdd : "Spd: 134",
        move1d : "-Facade",
        move2d : "-Brave Bird",
        move3d : "-Close Combat",
        move4d : "-Thief",

        namee : "Flamigo",
        levele : "LV: 60",
        typee : "Type: Flying (Tera)",
        abilitye: "Ability: Scrappy",
        iteme : "Item: None",
        hpe : "HP: 221",
        atke : "Atk: 158",
        defe : "Def: 108",
        spatke : "Sp. Atk: 110",
        spdefe : "Sp. Def: 96",
        spde : "Spd: 128",
        move1e : "-Brave Bird",
        move2e : "-Close Combat",
        move3e : "-Throat Chop",
        move4e : "-Liquidation",
    },

    {
        namea : "Noivern",
        levela : "LV: 60",
        typea : "Type: Flying/Dragon",
        abilitya: "Ability: Infiltrator",
        itema : "Item: None",
        hpa : "HP: 184",
        atka : "Atk: 101",
        defa : "Def: 113",
        spatka : "Sp. Atk: 133",
        spdefa : "Sp. Def: 113",
        spda : "Spd: 164",
        move1a : "-Air Slash",
        move2a : "-Dragon Pulse",
        move3a : "-Super Fang",
        move4a : "-Hyper Voice",

        nameb : "Haxorus",
        levelb : "LV: 60",
        typeb : "Type: Dragon",
        abilityb: "Ability: Mold Breaker",
        itemb : "Item: None",
        hpb : "HP: 173",
        atkb : "Atk: 193",
        defb : "Def: 125",
        spatkb : "Sp. Atk: 89",
        spdefb : "Sp. Def: 101",
        spdb : "Spd: 133",
        move1b : "-Dragon Claw",
        move2b : "-Crunch",
        move3b : "-Iron Head",
        move4b : "-Rock Tomb",

        namec : "Dragalge",
        levelc : "LV: 60",
        typec : "Type: Poison/Dragon",
        abilityc: "Ability: Poison Point",
        itemc : "Item: None",
        hpc : "HP: 160",
        atkc : "Atk: 107",
        defc : "Def: 125",
        spatkc : "Sp. Atk: 133",
        spdefc : "Sp. Def: 164",
        spdc : "Spd: 69",
        move1c : "-Sludge Bomb",
        move2c : "-Dragon Pulse",
        move3c : "-Hydro Pump",
        move4c : "-Thunderbolt",

        named : "Flapple",
        leveld : "LV: 60",
        typed : "Type: Grass/Dragon",
        abilityd: "Ability: Ripen",
        itemd : "Item: None",
        hpd : "HP: 166",
        atkd : "Atk: 149",
        defd : "Def: 113",
        spatkd : "Sp. Atk: 131",
        spdefd : "Sp. Def: 89",
        spdd : "Spd: 101",
        move1d : "-Dragon Rush",
        move2d : "-Seed Bomb",
        move3d : "-Aerial Ace",
        move4d : "-Leech Seed",

        namee : "Baxcalibur",
        levele : "LV: 61",
        typee : "Type: Dragon (Tera)",
        abilitye: "Ability: Thermal Exchange",
        iteme : "Item: None",
        hpe : "HP: 264",
        atke : "Atk: 197",
        defe : "Def: 132",
        spatke : "Sp. Atk: 111",
        spdefe : "Sp. Def: 125",
        spde : "Spd: 126",
        move1e : "-Icicle Crash",
        move2e : "-Brick Break",
        move3e : "-Glaive Rush",
        move4e : "",
    },

    {
        namea : "Espathra",
        levela : "LV: 61",
        typea : "Type: Psychic",
        abilitya: "Ability: Opportunist",
        itema : "Item: None",
        hpa : "HP: 202",
        atka : "Atk: 93",
        defa : "Def: 93",
        spatka : "Sp. Atk: 143",
        spdefa : "Sp. Def: 93",
        spda : "Spd: 148",
        move1a : "-Lumina Crash",
        move2a : "-Dazzling Gleam",
        move3a : "-Quick Attack",
        move4a : "-Reflect",

        nameb : "Gogoat",
        levelb : "LV: 61",
        typeb : "Type: Grass",
        abilityb: "Ability: Sap Sipper",
        itemb : "Item: None",
        hpb : "HP: 236",
        atkb : "Atk: 142",
        defb : "Def: 95",
        spatkb : "Sp. Atk: 138",
        spdefb : "Sp. Def: 119",
        spdb : "Spd: 103",
        move1b : "-Horn Leech",
        move2b : "-Zen Headbutt",
        move3b : "-Play Rough",
        move4b : "-Bulk Up",

        namec : "Veluza",
        levelc : "LV: 61",
        typec : "Type: Water/Psychic",
        abilityc: "Ability: Mold Breaker",
        itemc : "Item: None",
        hpc : "HP: 196",
        atkc : "Atk: 144",
        defc : "Def: 109",
        spatkc : "Sp. Atk: 115",
        spdefc : "Sp. Def: 99",
        spdc : "Spd: 105",
        move1c : "-Aqua Jet",
        move2c : "-Liquidation",
        move3c : "-Psycho Cut",
        move4c : "-Ice Fang",

        named : "Avalugg",
        leveld : "LV: 61",
        typed : "Type: Ice",
        abilityd: "Ability: Own Tempo",
        itemd : "Item: None",
        hpd : "HP: 202",
        atkd : "Atk: 162",
        defd : "Def: 244",
        spatkd : "Sp. Atk: 73",
        spdefd : "Sp. Def: 76",
        spdd : "Spd: 54",
        move1d : "-Avalanche",
        move2d : "-Crunch",
        move3d : "-Earthquake",
        move4d : "-Body Press",

        namee : "Kingambit",
        levele : "LV: 61",
        typee : "Type: Dark/Steel",
        abilitye: "Ability: Supreme Overlord",
        iteme : "Item: None",
        hpe : "HP: 208",
        atke : "Atk: 184",
        defe : "Def: 166",
        spatke : "Sp. Atk: 93",
        spdefe : "Sp. Def: 123",
        spde : "Spd: 81",
        move1e : "-Iron Head",
        move2e : "-Kowtow Cleave",
        move3e : "-Zen Headbutt",
        move4e : "-Stone Edge",

        namef : "Glimmora",
        levelf : "LV: 62",
        typef : "Type: Rock (Tera)",
        abilityf: "Ability: Toxic Debris",
        itemf : "Item: None",
        hpf : "HP: 232",
        atkf : "Atk: 91",
        deff : "Def: 135",
        spatkf : "Sp. Atk: 184",
        spdeff : "Sp. Def: 124",
        spdf : "Spd: 130",
        move1f : "-Tera Blast",
        move2f : "-Sludge Wave",
        move3f : "-Earth Power",
        move4f : "-Dazzling Gleam",
    },

    {
        namea : "Lycanroc (Midday)",
        levela : "LV: 65",
        typea : "Type: Rock",
        abilitya: "Ability: Sand Rush",
        itema : "Item: None",
        hpa : "HP: 185",
        atka : "Atk: 167",
        defa : "Def: 102",
        spatka : "Sp. Atk: 89",
        spdefa : "Sp. Def: 102",
        spda : "Spd: 163",
        move1a : "-Accelrock",
        move2a : "-Drill Run",
        move3a : "-Stone Edge",
        move4a : "-Stealth Rock",

        nameb : "Goodra",
        levelb : "LV: 65",
        typeb : "Type: Dragon",
        abilityb: "Ability: Sap Sipper",
        itemb : "Item: None",
        hpb : "HP: 205",
        atkb : "Atk: 148",
        defb : "Def: 109",
        spatkb : "Sp. Atk: 161",
        spdefb : "Sp. Def: 213",
        spdb : "Spd: 122",
        move1b : "-Dragon Pulse",
        move2b : "-Muddy Water",
        move3b : "-Ice Beam",
        move4b : "-Sludge Bomb",

        namec : "Dudunsparce",
        levelc : "LV: 65",
        typec : "Type: Normal",
        abilityc: "Ability: Serene Grace",
        itemc : "Item: None",
        hpc : "HP: 250",
        atkc : "Atk: 148",
        defc : "Def: 122",
        spatkc : "Sp. Atk: 128",
        spdefc : "Sp. Def: 115",
        spdc : "Spd: 89",
        move1c : "-Hyper Drill",
        move2c : "-Drill Run",
        move3c : "-Dragon Rush",
        move4c : "-Coil",

        named : "Orthworm",
        leveld : "LV: 65",
        typed : "Type: Steel",
        abilityd: "Ability: Earth Eater",
        itemd : "Item: None",
        hpd : "HP: 179",
        atkd : "Atk: 128",
        defd : "Def: 206",
        spatkd : "Sp. Atk: 96",
        spdefd : "Sp. Def: 89",
        spdd : "Spd: 102",
        move1d : "-Iron Tail",
        move2d : "-Body Press",
        move3d : "-Earthquake",
        move4d : "-Rock Blast",

        namee : "Pawmot",
        levele : "LV: 65",
        typee : "Type: Electric/Fighting",
        abilitye: "Ability: Volt Absorb",
        iteme : "Item: None",
        hpe : "HP: 179",
        atke : "Atk: 167",
        defe : "Def: 109",
        spatke : "Sp. Atk: 109",
        spdefe : "Sp. Def: 96",
        spde : "Spd: 154",
        move1e : "-Double Shock",
        move2e : "-Close Combat",
        move3e : "-Ice Punch",
        move4e : "-Quick Attack",

        namef : "Meowscarada",
        levelf : "LV: 66",
        typef : "Type: Grass (Tera)",
        abilityf: "Ability: Overgrow",
        itemf : "Item: None",
        hpf : "HP: 234",
        atkf : "Atk: 166",
        deff : "Def: 113",
        spatkf : "Sp. Atk: 128",
        spdeff : "Sp. Def: 113",
        spdf : "Spd: 183",
        move1f : "-Flower Trick",
        move2f : "-Thunder Punch",
        move3f : "-Shadow Claw",
        move4f : "-Play Rough",
    },

    {
        namea : "Lycanroc (Midday)",
        levela : "LV: 65",
        typea : "Type: Rock",
        abilitya: "Ability: Sand Rush",
        itema : "Item: None",
        hpa : "HP: 185",
        atka : "Atk: 167",
        defa : "Def: 102",
        spatka : "Sp. Atk: 89",
        spdefa : "Sp. Def: 102",
        spda : "Spd: 163",
        move1a : "-Accelrock",
        move2a : "-Drill Run",
        move3a : "-Stone Edge",
        move4a : "-Stealth Rock",

        nameb : "Goodra",
        levelb : "LV: 65",
        typeb : "Type: Dragon",
        abilityb: "Ability: Sap Sipper",
        itemb : "Item: None",
        hpb : "HP: 205",
        atkb : "Atk: 148",
        defb : "Def: 109",
        spatkb : "Sp. Atk: 161",
        spdefb : "Sp. Def: 213",
        spdb : "Spd: 122",
        move1b : "-Dragon Pulse",
        move2b : "-Muddy Water",
        move3b : "-Ice Beam",
        move4b : "-Sludge Bomb",

        namec : "Dudunsparce",
        levelc : "LV: 65",
        typec : "Type: Normal",
        abilityc: "Ability: Serene Grace",
        itemc : "Item: None",
        hpc : "HP: 250",
        atkc : "Atk: 148",
        defc : "Def: 122",
        spatkc : "Sp. Atk: 128",
        spdefc : "Sp. Def: 115",
        spdc : "Spd: 89",
        move1c : "-Hyper Drill",
        move2c : "-Drill Run",
        move3c : "-Dragon Rush",
        move4c : "-Coil",

        named : "Orthworm",
        leveld : "LV: 65",
        typed : "Type: Steel",
        abilityd: "Ability: Earth Eater",
        itemd : "Item: None",
        hpd : "HP: 179",
        atkd : "Atk: 128",
        defd : "Def: 206",
        spatkd : "Sp. Atk: 96",
        spdefd : "Sp. Def: 89",
        spdd : "Spd: 102",
        move1d : "-Iron Tail",
        move2d : "-Body Press",
        move3d : "-Earthquake",
        move4d : "-Rock Blast",

        namee : "Pawmot",
        levele : "LV: 65",
        typee : "Type: Electric/Fighting",
        abilitye: "Ability: Volt Absorb",
        iteme : "Item: None",
        hpe : "HP: 179",
        atke : "Atk: 167",
        defe : "Def: 109",
        spatke : "Sp. Atk: 109",
        spdefe : "Sp. Def: 96",
        spde : "Spd: 154",
        move1e : "-Double Shock",
        move2e : "-Close Combat",
        move3e : "-Ice Punch",
        move4e : "-Quick Attack",

        namef : "Skeledirge",
        levelf : "LV: 66",
        typef : "Type: Fire (Tera)",
        abilityf: "Ability: Blaze",
        itemf : "Item: None",
        hpf : "HP: 271",
        atkf : "Atk: 120",
        deff : "Def: 153",
        spatkf : "Sp. Atk: 166",
        spdeff : "Sp. Def: 120",
        spdf : "Spd: 108",
        move1f : "-Torch Song",
        move2f : "-Earth Power",
        move3f : "-Shadow Ball",
        move4f : "-Snarl",
    },

    {
        namea : "Lycanroc (Midday)",
        levela : "LV: 65",
        typea : "Type: Rock",
        abilitya: "Ability: Sand Rush",
        itema : "Item: None",
        hpa : "HP: 185",
        atka : "Atk: 167",
        defa : "Def: 102",
        spatka : "Sp. Atk: 89",
        spdefa : "Sp. Def: 102",
        spda : "Spd: 163",
        move1a : "-Accelrock",
        move2a : "-Drill Run",
        move3a : "-Stone Edge",
        move4a : "-Stealth Rock",

        nameb : "Goodra",
        levelb : "LV: 65",
        typeb : "Type: Dragon",
        abilityb: "Ability: Sap Sipper",
        itemb : "Item: None",
        hpb : "HP: 205",
        atkb : "Atk: 148",
        defb : "Def: 109",
        spatkb : "Sp. Atk: 161",
        spdefb : "Sp. Def: 213",
        spdb : "Spd: 122",
        move1b : "-Dragon Pulse",
        move2b : "-Muddy Water",
        move3b : "-Ice Beam",
        move4b : "-Sludge Bomb",

        namec : "Dudunsparce",
        levelc : "LV: 65",
        typec : "Type: Normal",
        abilityc: "Ability: Serene Grace",
        itemc : "Item: None",
        hpc : "HP: 250",
        atkc : "Atk: 148",
        defc : "Def: 122",
        spatkc : "Sp. Atk: 128",
        spdefc : "Sp. Def: 115",
        spdc : "Spd: 89",
        move1c : "-Hyper Drill",
        move2c : "-Drill Run",
        move3c : "-Dragon Rush",
        move4c : "-Coil",

        named : "Orthworm",
        leveld : "LV: 65",
        typed : "Type: Steel",
        abilityd: "Ability: Earth Eater",
        itemd : "Item: None",
        hpd : "HP: 179",
        atkd : "Atk: 128",
        defd : "Def: 206",
        spatkd : "Sp. Atk: 96",
        spdefd : "Sp. Def: 89",
        spdd : "Spd: 102",
        move1d : "-Iron Tail",
        move2d : "-Body Press",
        move3d : "-Earthquake",
        move4d : "-Rock Blast",

        namee : "Pawmot",
        levele : "LV: 65",
        typee : "Type: Electric/Fighting",
        abilitye: "Ability: Volt Absorb",
        iteme : "Item: None",
        hpe : "HP: 179",
        atke : "Atk: 167",
        defe : "Def: 109",
        spatke : "Sp. Atk: 109",
        spdefe : "Sp. Def: 96",
        spde : "Spd: 154",
        move1e : "-Double Shock",
        move2e : "-Close Combat",
        move3e : "-Ice Punch",
        move4e : "-Quick Attack",

        namef : "Quaquaval",
        levelf : "LV: 66",
        typef : "Type: Water (Tera)",
        abilityf: "Ability: Torrent",
        itemf : "Item: None",
        hpf : "HP: 246",
        atkf : "Atk: 179",
        deff : "Def: 127",
        spatkf : "Sp. Atk: 133",
        spdeff : "Sp. Def: 120",
        spdf : "Spd: 133",
        move1f : "-Aqua Step",
        move2f : "-Brick Break",
        move3f : "-Aerial Ace",
        move4f : "-Ice Spinner",
    },

    {
        namea : "Pawniard",
        levela : "LV: 21",
        typea : "Type: Dark/Steel",
        abilitya: "Ability: Defiant",
        itema : "Item: None",
        hpa : "HP: 55",
        atka : "Atk: 45",
        defa : "Def: 39",
        spatka : "Sp. Atk: 27",
        spdefa : "Sp. Def: 27",
        spda : "Spd: 35",
        move1a : "-Metal Claw",
        move2a : "-Fury Cutter",
        move3a : "-Aerial Ace",
        move4a : "",

        nameb : "Segin Starmobile",
        levelb : "LV: 20",
        typeb : "Type: Dark",
        abilityb: "Ability: Intimidate",
        itemb : "Item: None",
        hpb : "HP: U/A",
        atkb : "Atk: U/A",
        defb : "Def: U/A",
        spatkb : "Sp. Atk: U/A",
        spdefb : "Sp. Def: U/A",
        spdb : "Spd: U/A",
        move1b : "-Wicked Torque",
        move2b : "-Snarl",
        move3b : "-Metal Sound",
        move4b : "-Swift",
    },

    {
        namea : "Torkoal",
        levela : "LV: 27",
        typea : "Type: Fire",
        abilitya: "Ability: Drought",
        itema : "Item: None",
        hpa : "HP: 80",
        atka : "Atk: 56",
        defa : "Def: 86",
        spatka : "Sp. Atk: 56",
        spdefa : "Sp. Def: 48",
        spda : "Spd: 21",
        move1a : "-Flame Wheel",
        move2a : "-Clear Smog",
        move3a : "",
        move4a : "",

        nameb : "Schedar Starmobile",
        levelb : "LV: 26",
        typeb : "Type: Fire",
        abilityb: "Ability: Speed Boost",
        itemb : "Item: None",
        hpb : "HP: U/A",
        atkb : "Atk: U/A",
        defb : "Def: U/A",
        spatkb : "Sp. Atk: U/A",
        spdefb : "Sp. Def: U/A",
        spdb : "Spd: U/A",
        move1b : "-Blazing Torque",
        move2b : "-Overheat",
        move3b : "-Screech",
        move4b : "-Swift",
    },

    {
        namea : "Skuntank",
        levela : "LV: 32",
        typea : "Type: Poison/Dark",
        abilitya: "Ability: Stench",
        itema : "Item: None",
        hpa : "HP: 114",
        atka : "Atk: 70",
        defa : "Def: 54",
        spatka : "Sp. Atk: 56",
        spdefa : "Sp. Def: 50",
        spda : "Spd: 65",
        move1a : "-Sucker Punch",
        move2a : "-Toxic",
        move3a : "-Venoshock",
        move4a : "",

        nameb : "Muk",
        levelb : "LV: 32",
        typeb : "Type: Poison",
        abilityb: "Ability: Stench",
        itemb : "Item: None",
        hpb : "HP: 115",
        atkb : "Atk: 78",
        defb : "Def: 59",
        spatkb : "Sp. Atk: 53",
        spdefb : "Sp. Def: 75",
        spdb : "Spd: 43",
        move1b : "-Sludge Wave",
        move2b : "-Mud-Slap",
        move3b : "",
        move4b : "",

        namec : "Revaroom",
        levelc : "LV: 33",
        typec : "Type: Steel/Poison",
        abilityc: "Ability: Overcoat",
        itemc : "Item: None",
        hpc : "HP: 104",
        atkc : "Atk: 91",
        defc : "Def: 72",
        spatkc : "Sp. Atk: 48",
        spdefc : "Sp. Def: 57",
        spdc : "Spd: 72",
        move1c : "-Iron Head",
        move2c : "-Sludge",
        move3c : "-Assurance",
        move4c : "-Bulldoze",

        named : "Navi Starmobile",
        leveld : "LV: 32",
        typed : "Type: Poison",
        abilityd: "Ability: Toxic Debris",
        itemd : "Item: None",
        hpd : "HP: U/A",
        atkd : "Atk: U/A",
        defd : "Def: U/A",
        spatkd : "Sp. Atk: U/A",
        spdefd : "Sp. Def: U/A",
        spdd : "Spd: U/A",
        move1d : "-Noxious Torque",
        move2d : "-Spin Out",
        move3d : "-Flame Charge",
        move4d : "-Smog",
    },

    {
        namea : "Azumarill",
        levela : "LV: 50",
        typea : "Type: Water/Fairy",
        abilitya: "Ability: Huge Power",
        itema : "Item: None",
        hpa : "HP: 170",
        atka : "Atk: 65",
        defa : "Def: 95",
        spatka : "Sp. Atk: 75",
        spdefa : "Sp. Def: 95",
        spda : "Spd: 65",
        move1a : "-Aqua Tail",
        move2a : "-Play Rough",
        move3a : "-Bounce",
        move4a : "-Charm",

        nameb : "Wigglytuff",
        levelb : "LV: 50",
        typeb : "Type: Normal/Fairy",
        abilityb: "Ability: Cute Charm",
        itemb : "Item: None",
        hpb : "HP: 210",
        atkb : "Atk: 85",
        defb : "Def: 60",
        spatkb : "Sp. Atk: 100",
        spdefb : "Sp. Def: 65",
        spdb : "Spd: 60",
        move1b : "-Body Slam",
        move2b : "-Play Rough",
        move3b : "-Gyro Ball",
        move4b : "-Charm",

        namec : "Dachsbun",
        levelc : "LV: 51",
        typec : "Type: Fairy",
        abilityc: "Ability: Well-Baked Body",
        itemc : "Item: None",
        hpc : "HP: 131",
        atkc : "Atk: 99",
        defc : "Def: 135",
        spatkc : "Sp. Atk: 68",
        spdefc : "Sp. Def: 99",
        spdc : "Spd: 114",
        move1c : "-Crunch",
        move2c : "-Play Rough",
        move3c : "-Baby-Doll Eyes",
        move4c : "-Mud-Slap",

        named : "Ruchbah Starmobile",
        leveld : "LV: 50",
        typed : "Type: Fairy",
        abilityd: "Ability: Misty Surge",
        itemd : "Item: None",
        hpd : "HP: U/A",
        atkd : "Atk: U/A",
        defd : "Def: U/A",
        spatkd : "Sp. Atk: U/A",
        spdefd : "Sp. Def: U/A",
        spdd : "Spd: U/A",
        move1d : "-Magical Torque",
        move2d : "-Steel Roller",
        move3d : "-Confuse Ray",
        move4d : "-Spin Out",
    },

    {
        namea : "Toxicroak",
        levela : "LV: 55",
        typea : "Type: Poison/Fighting",
        abilitya: "Ability: Anticipation",
        itema : "Item: None",
        hpa : "HP: 167",
        atka : "Atk: 132",
        defa : "Def: 87",
        spatka : "Sp. Atk: 110",
        spdefa : "Sp. Def: 87",
        spda : "Spd: 109",
        move1a : "-Poison Jab",
        move2a : "-Brick Break",
        move3a : "-Sucker Punch",
        move4a : "",

        nameb : "Passimian",
        levelb : "LV: 55",
        typeb : "Type: Fighting",
        abilityb: "Ability: Receiver",
        itemb : "Item: None",
        hpb : "HP: 186",
        atkb : "Atk: 148",
        defb : "Def: 115",
        spatkb : "Sp. Atk: 60",
        spdefb : "Sp. Def: 82",
        spdb : "Spd: 104",
        move1b : "-Close Combat",
        move2b : "-Rock Throw",
        move3b : "-Seed Bomb",
        move4b : "",

        namec : "Lucario",
        levelc : "LV: 55",
        typec : "Type: Fighting/Steel",
        abilityc: "Ability: Steadfast",
        itemc : "Item: None",
        hpc : "HP: 153",
        atkc : "Atk: 137",
        defc : "Def: 93",
        spatkc : "Sp. Atk: 142",
        spdefc : "Sp. Def: 93",
        spdc : "Spd: 115",
        move1c : "-Dragon Pulse",
        move2c : "-Aura Sphere",
        move3c : "-Dark Pulse",
        move4c : "",

        named : "Annihilape",
        leveld : "LV: 56",
        typed : "Type: Fighting/Ghost",
        abilityd: "Ability: Vital Spirit",
        itemd : "Item: None",
        hpd : "HP: 203",
        atkd : "Atk: 147",
        defd : "Def: 108",
        spatkd : "Sp. Atk: 75",
        spdefd : "Sp. Def: 119",
        spdd : "Spd: 119",
        move1d : "-Rage Fist",
        move2d : "-Close Combat",
        move3d : "-Ice Punch",
        move4d : "-Fire Punch",

        namee : "Caph Starmobile",
        levele : "LV: 56",
        typee : "Type: Fighting",
        abilitye: "Ability: Stamina",
        iteme : "Item: None",
        hpe : "HP: U/A",
        atke : "Atk: U/A",
        defe : "Def: U/A",
        spatke : "Sp. Atk: U/A",
        spdefe : "Sp. Def: U/A",
        spde : "Spd: U/A",
        move1e : "-Combat Torque",
        move2e : "-Spin Out",
        move3e : "-Shift Gear",
        move4e : "-High Horsepower",
    },

    {
        namea : "Oranguru",
        levela : "LV: 60",
        typea : "Type: Normal/Psychic",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 190",
        atka : "Atk: 89",
        defa : "Def: 113",
        spatka : "Sp. Atk: 125",
        spdefa : "Sp. Def: 149",
        spda : "Spd: 89",
        move1a : "-Yawn",
        move2a : "-Dream Eater",
        move3a : "-Reflect",
        move4a : "-Foul Play",

        nameb : "Abomasnow",
        levelb : "LV: 60",
        typeb : "Type: Grass/Ice",
        abilityb: "Ability: Snow Warning",
        itemb : "Item: None",
        hpb : "HP: 190",
        atkb : "Atk: 127",
        defb : "Def: 107",
        spatkb : "Sp. Atk: 127",
        spdefb : "Sp. Def: 119",
        spdb : "Spd: 89",
        move1b : "-Aurora Veil",
        move2b : "-Blizzard",
        move3b : "-Wood Hammer",
        move4b : "-Ice Shard",

        namec : "Polteageist",
        levelc : "LV: 60",
        typec : "Type: Ghost",
        abilityc: "Ability: Weak Armor",
        itemc : "Item: None",
        hpc : "HP: 154",
        atkc : "Atk: 95",
        defc : "Def: 95",
        spatkc : "Sp. Atk: 177",
        spdefc : "Sp. Def: 153",
        spdc : "Spd: 101",
        move1c : "-Shell Smash",
        move2c : "-Shadow Ball",
        move3c : "-Sucker Punch",
        move4c : "-Will-O-Wisp",

        named : "Gyarados",
        leveld : "LV: 60",
        typed : "Type: Water/Flying",
        abilityd: "Ability: Intimidate",
        itemd : "Item: None",
        hpd : "HP: 196",
        atkd : "Atk: 167",
        defd : "Def: 111",
        spatkd : "Sp. Atk: 89",
        spdefd : "Sp. Def: 137",
        spdd : "Spd: 114",
        move1d : "-Aqua Tail",
        move2d : "-Crunch",
        move3d : "-Stone Edge",
        move4d : "-Earthquake",

        namee : "Houndoom",
        levele : "LV: 60",
        typee : "Type: Dark/Fire",
        abilitye: "Ability: Flash Fire",
        iteme : "Item: None",
        hpe : "HP: 172",
        atke : "Atk: 125",
        defe : "Def: 77",
        spatke : "Sp. Atk: 149",
        spdefe : "Sp. Def: 113",
        spde : "Spd: 131",
        move1e : "-Dark Pulse",
        move2e : "-Fire Blast",
        move3e : "-Sludge Bomb",
        move4e : "-Thunder Fang",

        namef : "Meowscarada",
        levelf : "LV: 61",
        typef : "Type: Grass (Tera)",
        abilityf: "Ability: Overgrow",
        itemf : "Item: None",
        hpf : "HP: 217",
        atkf : "Atk: 154",
        deff : "Def: 105",
        spatkf : "Sp. Atk: 119",
        spdeff : "Sp. Def: 105",
        spdf : "Spd: 170",
        move1f : "-Flower Trick",
        move2f : "-Thunder Punch",
        move3f : "-Shadow Claw",
        move4f : "-Play Rough",
    },

    {
        namea : "Oranguru",
        levela : "LV: 60",
        typea : "Type: Normal/Psychic",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 190",
        atka : "Atk: 89",
        defa : "Def: 113",
        spatka : "Sp. Atk: 125",
        spdefa : "Sp. Def: 149",
        spda : "Spd: 89",
        move1a : "-Yawn",
        move2a : "-Dream Eater",
        move3a : "-Reflect",
        move4a : "-Foul Play",

        nameb : "Abomasnow",
        levelb : "LV: 60",
        typeb : "Type: Grass/Ice",
        abilityb: "Ability: Snow Warning",
        itemb : "Item: None",
        hpb : "HP: 190",
        atkb : "Atk: 127",
        defb : "Def: 107",
        spatkb : "Sp. Atk: 127",
        spdefb : "Sp. Def: 119",
        spdb : "Spd: 89",
        move1b : "-Aurora Veil",
        move2b : "-Blizzard",
        move3b : "-Wood Hammer",
        move4b : "-Ice Shard",

        namec : "Polteageist",
        levelc : "LV: 60",
        typec : "Type: Ghost",
        abilityc: "Ability: Weak Armor",
        itemc : "Item: None",
        hpc : "HP: 154",
        atkc : "Atk: 95",
        defc : "Def: 95",
        spatkc : "Sp. Atk: 177",
        spdefc : "Sp. Def: 153",
        spdc : "Spd: 101",
        move1c : "-Shell Smash",
        move2c : "-Shadow Ball",
        move3c : "-Sucker Punch",
        move4c : "-Will-O-Wisp",

        named : "Amoongus",
        leveld : "LV: 60",
        typed : "Type: Grass/Poison",
        abilityd: "Ability: Effect Spore",
        itemd : "Item: None",
        hpd : "HP: 218",
        atkd : "Atk: 119",
        defd : "Def: 101",
        spatkd : "Sp. Atk: 119",
        spdefd : "Sp. Def: 113",
        spdd : "Spd: 53",
        move1d : "-Spore",
        move2d : "-Toxic",
        move3d : "-Giga Drain",
        move4d : "-Hex",

        namee : "Gyarados",
        levele : "LV: 60",
        typee : "Type: Water/Flying",
        abilitye: "Ability: Intimidate",
        iteme : "Item: None",
        hpe : "HP: 196",
        atke : "Atk: 167",
        defe : "Def: 111",
        spatke : "Sp. Atk: 89",
        spdefe : "Sp. Def: 137",
        spde : "Spd: 114",
        move1e : "-Aqua Tail",
        move2e : "-Crunch",
        move3e : "-Stone Edge",
        move4e : "-Earthquake",

        namef : "Skeledirge",
        levelf : "LV: 61",
        typef : "Type: Fire (Tera)",
        abilityf: "Ability: Blaze",
        itemf : "Item: None",
        hpf : "HP: 251",
        atkf : "Atk: 111",
        deff : "Def: 142",
        spatkf : "Sp. Atk: 154",
        spdeff : "Sp. Def: 111",
        spdf : "Spd: 100",
        move1f : "-Torch Song",
        move2f : "-Earth Power",
        move3f : "-Shadow Ball",
        move4f : "-Snarl",
    },

    {
        namea : "Oranguru",
        levela : "LV: 60",
        typea : "Type: Normal/Psychic",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 190",
        atka : "Atk: 89",
        defa : "Def: 113",
        spatka : "Sp. Atk: 125",
        spdefa : "Sp. Def: 149",
        spda : "Spd: 89",
        move1a : "-Yawn",
        move2a : "-Dream Eater",
        move3a : "-Reflect",
        move4a : "-Foul Play",

        nameb : "Abomasnow",
        levelb : "LV: 60",
        typeb : "Type: Grass/Ice",
        abilityb: "Ability: Snow Warning",
        itemb : "Item: None",
        hpb : "HP: 190",
        atkb : "Atk: 127",
        defb : "Def: 107",
        spatkb : "Sp. Atk: 127",
        spdefb : "Sp. Def: 119",
        spdb : "Spd: 89",
        move1b : "-Aurora Veil",
        move2b : "-Blizzard",
        move3b : "-Wood Hammer",
        move4b : "-Ice Shard",

        namec : "Polteageist",
        levelc : "LV: 60",
        typec : "Type: Ghost",
        abilityc: "Ability: Weak Armor",
        itemc : "Item: None",
        hpc : "HP: 154",
        atkc : "Atk: 95",
        defc : "Def: 95",
        spatkc : "Sp. Atk: 177",
        spdefc : "Sp. Def: 153",
        spdc : "Spd: 101",
        move1c : "-Shell Smash",
        move2c : "-Shadow Ball",
        move3c : "-Sucker Punch",
        move4c : "-Will-O-Wisp",

        named : "Houndoom",
        leveld : "LV: 60",
        typed : "Type: Dark/Fire",
        abilityd: "Ability: Flash Fire",
        itemd : "Item: None",
        hpd : "HP: 172",
        atkd : "Atk: 125",
        defd : "Def: 77",
        spatkd : "Sp. Atk: 149",
        spdefd : "Sp. Def: 113",
        spdd : "Spd: 131",
        move1d : "-Dark Pulse",
        move2d : "-Fire Blast",
        move3d : "-Sludge Bomb",
        move4d : "-Thunder Fang",

        namee : "Amoongus",
        levele : "LV: 60",
        typee : "Type: Grass/Poison",
        abilitye: "Ability: Effect Spore",
        iteme : "Item: None",
        hpe : "HP: 218",
        atke : "Atk: 119",
        defe : "Def: 101",
        spatke : "Sp. Atk: 119",
        spdefe : "Sp. Def: 113",
        spde : "Spd: 53",
        move1e : "-Spore",
        move2e : "-Toxic",
        move3e : "-Giga Drain",
        move4e : "-Hex",

        namef : "Quaquaval",
        levelf : "LV: 61",
        typef : "Type: Water (Tera)",
        abilityf: "Ability: Torrent",
        itemf : "Item: None",
        hpf : "HP: 228",
        atkf : "Atk: 166",
        deff : "Def: 117",
        spatkf : "Sp. Atk: 123",
        spdeff : "Sp. Def: 111",
        spdf : "Spd: 123",
        move1f : "-Aqua Step",
        move2f : "-Brick Break",
        move3f : "-Aerial Ace",
        move4f : "-Ice Spinner",
    },

    {
        namea : "Umbreon",
        levela : "LV: 62",
        typea : "Type: Dark",
        abilitya: "Ability: Synchronize",
        itema : "Item: None",
        hpa : "HP: 202",
        atka : "Atk: 98",
        defa : "Def: 153",
        spatka : "Sp. Atk: 91",
        spdefa : "Sp. Def: 178",
        spda : "Spd: 98",
        move1a : "-Dark Pulse",
        move2a : "-Quick Attack",
        move3a : "-Baby-Doll Eyes",
        move4a : "-Psychic",

        nameb : "Vaporeon",
        levelb : "LV: 62",
        typeb : "Type: Water",
        abilityb: "Ability: Water Absorb",
        itemb : "Item: None",
        hpb : "HP: 245",
        atkb : "Atk: 98",
        defb : "Def: 91",
        spatkb : "Sp. Atk: 153",
        spdefb : "Sp. Def: 135",
        spdb : "Spd: 98",
        move1b : "-",
        move2b : "-Quick Attack",
        move3b : "-Baby-Doll Eyes",
        move4b : "-",

        namec : "Jolteon",
        levelc : "LV: 62",
        typec : "Type: Electric",
        abilityc: "Ability: Quick Feet",
        itemc : "Item: None",
        hpc : "HP: 165",
        atkc : "Atk: 98",
        defc : "Def: 91",
        spatkc : "Sp. Atk: 153",
        spdefc : "Sp. Def: 135",
        spdc : "Spd: 178",
        move1c : "-Thunder",
        move2c : "-Quick Attack",
        move3c : "-Baby-Doll Eyes",
        move4c : "-Pin Missile",

        named : "Flareon",
        leveld : "LV: 62",
        typed : "Type: Fire",
        abilityd: "Ability: Flash Fire",
        itemd : "Item: None",
        hpd : "HP: 165",
        atkd : "Atk: 178",
        defd : "Def: 91",
        spatkd : "Sp. Atk: 135",
        spdefd : "Sp. Def: 153",
        spdd : "Spd: 98",
        move1d : "-Flare Blitz",
        move2d : "-Quick Attack",
        move3d : "-Baby-Doll Eyes",
        move4d : "-Fire Spin",

        namee : "Leafeon",
        levele : "LV: 62",
        typee : "Type: Grass",
        abilitye: "Ability: Leaf Guard",
        iteme : "Item: None",
        hpe : "HP: 165",
        atke : "Atk: 153",
        defe : "Def: 178",
        spatke : "Sp. Atk: 91",
        spdefe : "Sp. Def: 98",
        spde : "Spd: 135",
        move1e : "-Leaf Blade",
        move2e : "-Quick Attack",
        move3e : "-Baby-Doll Eyes",
        move4e : "-X-Scissor",

        namef : "Sylveon",
        levelf : "LV: 63",
        typef : "Type: Fairy (Tera)",
        abilityf: "Ability: Cute Charm",
        itemf : "Item: None",
        hpf : "HP: 248",
        atkf : "Atk: 102",
        deff : "Def: 102",
        spatkf : "Sp. Atk: 159",
        spdeff : "Sp. Def: 184",
        spdf : "Spd: 96",
        move1f : "-Moonblast",
        move2f : "-Quick Attack",
        move3f : "-Baby-Doll Eyes",
        move4f : "-Shadow Ball",
    },

    {
        namea : "Greedent",
        levela : "LV: 58",
        typea : "Type: Normal",
        abilitya: "Ability: Cheek Pouch",
        itema : "Item: None",
        hpa : "HP: 207",
        atka : "Atk: 115",
        defa : "Def: 115",
        spatka : "Sp. Atk: 68",
        spdefa : "Sp. Def: 92",
        spda : "Spd: 28",
        move1a : "-Bullet Seed",
        move2a : "-Body Slam",
        move3a : "-Psychic Fangs",
        move4a : "-Earthquake",

        nameb : "Cloyster",
        levelb : "LV: 59",
        typeb : "Type: Water/Ice",
        abilityb: "Ability: Skill Link",
        itemb : "Item: None",
        hpb : "HP: 139",
        atkb : "Atk: 128",
        defb : "Def: 229",
        spatkb : "Sp. Atk: 117",
        spdefb : "Sp. Def: 69",
        spdb : "Spd: 99",
        move1b : "-Rock Blast",
        move2b : "-Icicle Spear",
        move3b : "-Liquidation",
        move4b : "-Light Screen",

        namec : "Scovillain",
        levelc : "LV: 60",
        typec : "Type: Grass/Fire",
        abilityc: "Ability: Chlorophyll",
        itemc : "Item: None",
        hpc : "HP: 160",
        atkc : "Atk: 146",
        defc : "Def: 95",
        spatkc : "Sp. Atk: 146",
        spdefc : "Sp. Def: 95",
        spdc : "Spd: 107",
        move1c : "-Fire Blast",
        move2c : "-Energy Ball",
        move3c : "-Zen Headbutt",
        move4c : "-Crunch",

        named : "Toedscruel",
        leveld : "LV: 61",
        typed : "Type: Ground/Grass",
        abilityd: "Ability: Mycelium Might",
        itemd : "Item: None",
        hpd : "HP: 180",
        atkd : "Atk: 102",
        defd : "Def: 96",
        spatkd : "Sp. Atk: 114",
        spdefd : "Sp. Def: 163",
        spdd : "Spd: 139",
        move1d : "-Power Whip",
        move2d : "-Earth Power",
        move3d : "-Spore",
        move4d : "-Sludge Bomb",

        namee : "Garganacl",
        levele : "LV: 62",
        typee : "Type: Rock",
        abilitye: "Ability: Purifying Salt",
        iteme : "Item: None",
        hpe : "HP: 208",
        atke : "Atk: 141",
        defe : "Def: 178",
        spatke : "Sp. Atk: 73",
        spdefe : "Sp. Def: 129",
        spde : "Spd: 60",
        move1e : "-Stone Edge",
        move2e : "-Earthquake",
        move3e : "-Body Press",
        move4e : "-Stealth Rock",

        namef : "Mabosstiff",
        levelf : "LV: 63",
        typef : "Type: Dark (Tera)",
        abilityf: "Ability: Intimidate",
        itemf : "Item: None",
        hpf : "HP: 229",
        atkf : "Atk: 171",
        deff : "Def: 134",
        spatkf : "Sp. Atk: 96",
        spdeff : "Sp. Def: 108",
        spdf : "Spd: 127",
        move1f : "-Crunch",
        move2f : "-Psychic Fangs",
        move3f : "-Fire Fang",
        move4f : "-Play Rough",
    },

    {
        namea : "Slither Wing",
        levela : "LV: 66",
        typea : "Type: Bug/Fighting",
        abilitya: "Ability: Protosynthesis",
        itema : "Item: None",
        hpa : "HP: 204",
        atka : "Atk: 199",
        defa : "Def: 125",
        spatka : "Sp. Atk: 133",
        spdefa : "Sp. Def: 160",
        spda : "Spd: 128",
        move1a : "-Lunge",
        move2a : "-Leech Life",
        move3a : "-Low Sweep",
        move4a : "-Zen Headbutt",

        nameb : "Scream Tail",
        levelb : "LV: 66",
        typeb : "Type: Fairy/Psychic",
        abilityb: "Ability: Protosynthesis",
        itemb : "Item: None",
        hpb : "HP: 244",
        atkb : "Atk: 107",
        defb : "Def: 152",
        spatkb : "Sp. Atk: 107",
        spdefb : "Sp. Def: 173",
        spdb : "Spd: 168",
        move1b : "-Play Rough",
        move2b : "-Drain Punch",
        move3b : "-Ice Punch",
        move4b : "-Zen Headbutt",

        namec : "Brute Bonnet",
        levelc : "LV: 66",
        typec : "Type: Grass/Dark",
        abilityc: "Ability: Protosynthesis",
        itemc : "Item: None",
        hpc : "HP: 239",
        atkc : "Atk: 189",
        defc : "Def: 152",
        spatkc : "Sp. Atk: 125",
        spdefc : "Sp. Def: 152",
        spdc : "Spd: 94",
        move1c : "-Earth Power",
        move2c : "-Giga Drain",
        move3c : "-Payback",
        move4c : "-Sucker Punch",

        named : "Flutter Mane",
        leveld : "LV: 66",
        typed : "Type: Ghost/Fairy",
        abilityd: "Ability: Protosynthesis",
        itemd : "Item: None",
        hpd : "HP: 165",
        atkd : "Atk: 94",
        defd : "Def: 94",
        spatkd : "Sp. Atk: 199",
        spdefd : "Sp. Def: 199",
        spdd : "Spd: 199",
        move1d : "-Power Gem",
        move2d : "-Mystical Fire",
        move3d : "-Shadow Ball",
        move4d : "-Thunderbolt",

        namee : "Sandy Shocks",
        levele : "LV: 66",
        typee : "Type: Electric/Ground",
        abilitye: "Ability: Protosynthesis",
        iteme : "Item: None",
        hpe : "HP: 204",
        atke : "Atk: 128",
        defe : "Def: 149",
        spatke : "Sp. Atk: 181",
        spdefe : "Sp. Def: 133",
        spde : "Spd: 154",
        move1e : "-Discharge",
        move2e : "-Earth Power",
        move3e : "-Flash Cannon",
        move4e : "-Power Gem",

        namef : "Roaring Moon",
        levelf : "LV: 67",
        typef : "Type: Dragon/Dark",
        abilityf: "Ability: Protosynthesis",
        itemf : "Item: Booster Energy",
        hpf : "HP: 237",
        atkf : "Atk: 211",
        deff : "Def: 120",
        spatkf : "Sp. Atk: 98",
        spdeff : "Sp. Def: 160",
        spdf : "Spd: 184",
        move1f : "-Dragon Claw",
        move2f : "-Night Slash",
        move3f : "-Stone Edge",
        move4f : "-Earthquake",
    },

    {
        namea : "Iron Moth",
        levela : "LV: 66",
        typea : "Type: Fire/Poison",
        abilitya: "Ability: Quark Drive",
        itema : "Item: None",
        hpa : "HP: 198",
        atka : "Atk: 113",
        defa : "Def: 100",
        spatka : "Sp. Atk: 206",
        spdefa : "Sp. Def: 166",
        spda : "Spd: 166",
        move1a : "-Sludge Wave",
        move2a : "-Fiery Dance",
        move3a : "-Discharge",
        move4a : "-Air Slash",

        nameb : "Iron Bundle",
        levelb : "LV: 66",
        typeb : "Type: Ice/Water",
        abilityb: "Ability: Quark Drive",
        itemb : "Item: None",
        hpb : "HP: 166",
        atkb : "Atk: 127",
        defb : "Def: 171",
        spatkb : "Sp. Atk: 185",
        spdefb : "Sp. Def: 100",
        spdb : "Spd: 201",
        move1b : "-Drill Peck",
        move2b : "-Water Pulse",
        move3b : "-Freeze-Dry",
        move4b : "-Snowscape",

        namec : "Iron Hands",
        levelc : "LV: 66",
        typec : "Type: Fighting/Electric",
        abilityc: "Ability: Quark Drive",
        itemc : "Item: None",
        hpc : "HP: 295",
        atkc : "Atk: 206",
        defc : "Def: 164",
        spatkc : "Sp. Atk: 87",
        spdefc : "Sp. Def: 111",
        spdc : "Spd: 87",
        move1c : "-Thunder Punch",
        move2c : "-Drain Punch",
        move3c : "-Iron Head",
        move4c : "-Fake Out",

        named : "Iron Jugulis",
        leveld : "LV: 66",
        typed : "Type: Dark/Flying",
        abilityd: "Ability: Quark Drive",
        itemd : "Item: None",
        hpd : "HP: 216",
        atkd : "Atk: 127",
        defd : "Def: 135",
        spatkd : "Sp. Atk: 182",
        spdefd : "Sp. Def: 127",
        spdd : "Spd: 164",
        move1d : "-Air Slash",
        move2d : "-Dark Pulse",
        move3d : "-Flamethrower",
        move4d : "-Flash Cannon",

        namee : "Iron Thorns",
        levele : "LV: 66",
        typee : "Type: Rock/Eletric",
        abilitye: "Ability: Quark Drive",
        iteme : "Item: None",
        hpe : "HP: 224",
        atke : "Atk: 198",
        defe : "Def: 166",
        spatke : "Sp. Atk: 113",
        spdefe : "Sp. Def: 132",
        spde : "Spd: 116",
        move1e : "-Thunder Punch",
        move2e : "-Brick Break",
        move3e : "-Stone Edge",
        move4e : "-Earthquake",

        namef : "Iron Valiant",
        levelf : "LV: 67",
        typef : "Type: Fairy/Fighting",
        abilityf: "Ability: Quark Drive",
        itemf : "Item: Booster Drive",
        hpf : "HP: 196",
        atkf : "Atk: 199",
        deff : "Def: 145",
        spatkf : "Sp. Atk: 185",
        spdeff : "Sp. Def: 105",
        spdf : "Spd: 180",
        move1f : "-Psycho Cut",
        move2f : "-Brick Break",
        move3f : "-Spirit Break",
        move4f : "-Poison Jab",
    }
]

function displaySVTrainers() {

    let newTrainerId = this.id;
    if (newTrainerId !== currentTrainerId) {
        currentTrainerId = newTrainerId;
        showSVImages(newTrainerId);
        showPokemonSVImages(newTrainerId);
    }


    let svTrainer = this.dataset.member;

    document.querySelector('#name1').textContent = sv_trainers [svTrainer].namea;
    document.querySelector('#level1').textContent = sv_trainers [svTrainer].levela;
    document.querySelector('#type1').textContent = sv_trainers [svTrainer].typea;
    document.querySelector('#ability1').textContent= sv_trainers [svTrainer].abilitya;
    document.querySelector('#item1').textContent = sv_trainers [svTrainer].itema;
    document.querySelector('#hp1').textContent = sv_trainers [svTrainer].hpa;
    document.querySelector('#atk1').textContent = sv_trainers [svTrainer].atka;
    document.querySelector('#def1').textContent = sv_trainers [svTrainer].defa;
    document.querySelector('#spatk1').textContent = sv_trainers [svTrainer].spatka;
    document.querySelector('#spdef1').textContent = sv_trainers [svTrainer].spdefa;
    document.querySelector('#spd1').textContent = sv_trainers [svTrainer].spda;
    document.querySelector('#move1_1').textContent = sv_trainers [svTrainer].move1a;
    document.querySelector('#move2_1').textContent = sv_trainers [svTrainer].move2a;
    document.querySelector('#move3_1').textContent = sv_trainers [svTrainer].move3a;
    document.querySelector('#move4_1').textContent = sv_trainers [svTrainer].move4a;

    
    document.querySelector('#name2').textContent = sv_trainers [svTrainer].nameb;
    document.querySelector('#level2').textContent = sv_trainers [svTrainer].levelb;
    document.querySelector('#type2').textContent = sv_trainers [svTrainer].typeb;
    document.querySelector('#ability2').textContent= sv_trainers [svTrainer].abilityb;
    document.querySelector('#item2').textContent = sv_trainers [svTrainer].itemb;
    document.querySelector('#hp2').textContent = sv_trainers [svTrainer].hpb;
    document.querySelector('#atk2').textContent = sv_trainers [svTrainer].atkb;
    document.querySelector('#def2').textContent = sv_trainers [svTrainer].defb;
    document.querySelector('#spatk2').textContent = sv_trainers [svTrainer].spatkb;
    document.querySelector('#spdef2').textContent = sv_trainers [svTrainer].spdefb;
    document.querySelector('#spd2').textContent = sv_trainers [svTrainer].spdb;
    document.querySelector('#move1_2').textContent = sv_trainers [svTrainer].move1b;
    document.querySelector('#move2_2').textContent = sv_trainers [svTrainer].move2b;
    document.querySelector('#move3_2').textContent = sv_trainers [svTrainer].move3b;
    document.querySelector('#move4_2').textContent = sv_trainers [svTrainer].move4b;

    document.querySelector('#name3').textContent = sv_trainers [svTrainer].namec;
    document.querySelector('#level3').textContent = sv_trainers [svTrainer].levelc;
    document.querySelector('#type3').textContent = sv_trainers [svTrainer].typec;
    document.querySelector('#ability3').textContent= sv_trainers [svTrainer].abilityc;
    document.querySelector('#item3').textContent = sv_trainers [svTrainer].itemc;
    document.querySelector('#hp3').textContent = sv_trainers [svTrainer].hpc;
    document.querySelector('#atk3').textContent = sv_trainers [svTrainer].atkc;
    document.querySelector('#def3').textContent = sv_trainers [svTrainer].defc;
    document.querySelector('#spatk3').textContent = sv_trainers [svTrainer].spatkc;
    document.querySelector('#spdef3').textContent = sv_trainers [svTrainer].spdefc;
    document.querySelector('#spd3').textContent = sv_trainers [svTrainer].spdc;
    document.querySelector('#move1_3').textContent = sv_trainers [svTrainer].move1c;
    document.querySelector('#move2_3').textContent = sv_trainers [svTrainer].move2c;
    document.querySelector('#move3_3').textContent = sv_trainers [svTrainer].move3c;
    document.querySelector('#move4_3').textContent = sv_trainers [svTrainer].move4c;

    document.querySelector('#name4').textContent = sv_trainers [svTrainer].named;
    document.querySelector('#level4').textContent = sv_trainers [svTrainer].leveld;
    document.querySelector('#type4').textContent = sv_trainers [svTrainer].typed;
    document.querySelector('#ability4').textContent= sv_trainers [svTrainer].abilityd;
    document.querySelector('#item4').textContent = sv_trainers [svTrainer].itemd;
    document.querySelector('#hp4').textContent = sv_trainers [svTrainer].hpd;
    document.querySelector('#atk4').textContent = sv_trainers [svTrainer].atkd;
    document.querySelector('#def4').textContent = sv_trainers [svTrainer].defd;
    document.querySelector('#spatk4').textContent = sv_trainers [svTrainer].spatkd;
    document.querySelector('#spdef4').textContent = sv_trainers [svTrainer].spdefd;
    document.querySelector('#spd4').textContent = sv_trainers [svTrainer].spdd;
    document.querySelector('#move1_4').textContent = sv_trainers [svTrainer].move1d;
    document.querySelector('#move2_4').textContent = sv_trainers [svTrainer].move2d;
    document.querySelector('#move3_4').textContent = sv_trainers [svTrainer].move3d;
    document.querySelector('#move4_4').textContent = sv_trainers [svTrainer].move4d;

    document.querySelector('#name5').textContent = sv_trainers [svTrainer].namee;
    document.querySelector('#level5').textContent = sv_trainers [svTrainer].levele;
    document.querySelector('#type5').textContent = sv_trainers [svTrainer].typee;
    document.querySelector('#ability5').textContent= sv_trainers [svTrainer].abilitye;
    document.querySelector('#item5').textContent = sv_trainers [svTrainer].iteme;
    document.querySelector('#hp5').textContent = sv_trainers [svTrainer].hpe;
    document.querySelector('#atk5').textContent = sv_trainers [svTrainer].atke;
    document.querySelector('#def5').textContent = sv_trainers [svTrainer].defe;
    document.querySelector('#spatk5').textContent = sv_trainers [svTrainer].spatke;
    document.querySelector('#spdef5').textContent = sv_trainers [svTrainer].spdefe;
    document.querySelector('#spd5').textContent = sv_trainers [svTrainer].spde;
    document.querySelector('#move1_5').textContent = sv_trainers [svTrainer].move1e;
    document.querySelector('#move2_5').textContent = sv_trainers [svTrainer].move2e;
    document.querySelector('#move3_5').textContent = sv_trainers [svTrainer].move3e;
    document.querySelector('#move4_5').textContent = sv_trainers [svTrainer].move4e;

    document.querySelector('#name6').textContent = sv_trainers [svTrainer].namef;
    document.querySelector('#level6').textContent = sv_trainers [svTrainer].levelf;
    document.querySelector('#type6').textContent = sv_trainers [svTrainer].typef;
    document.querySelector('#ability6').textContent= sv_trainers [svTrainer].abilityf;
    document.querySelector('#item6').textContent = sv_trainers [svTrainer].itemf;
    document.querySelector('#hp6').textContent = sv_trainers [svTrainer].hpf;
    document.querySelector('#atk6').textContent = sv_trainers [svTrainer].atkf;
    document.querySelector('#def6').textContent = sv_trainers [svTrainer].deff;
    document.querySelector('#spatk6').textContent = sv_trainers [svTrainer].spatkf;
    document.querySelector('#spdef6').textContent = sv_trainers [svTrainer].spdeff;
    document.querySelector('#spd6').textContent = sv_trainers [svTrainer].spdf;
    document.querySelector('#move1_6').textContent = sv_trainers [svTrainer].move1f;
    document.querySelector('#move2_6').textContent = sv_trainers [svTrainer].move2f;
    document.querySelector('#move3_6').textContent = sv_trainers [svTrainer].move3f;
    document.querySelector('#move4_6').textContent = sv_trainers [svTrainer].move4f;
}

function showSVImages(trainerId) {
    var trainerPicture = document.querySelector("#trainer_image");
    
    trainerPicture.innerHTML = "";

    var imgTrainer = document.createElement("img");
    imgTrainer.src = "images/trainers/sv/" + trainerId + ".png";
    trainerPicture.appendChild(imgTrainer);
}

function showPokemonSVImages(trainerId) {
    var pokemon1Picture = document.querySelector("#pokemon_1_image");
    var pokemon2Picture = document.querySelector("#pokemon_2_image");
    var pokemon3Picture = document.querySelector("#pokemon_3_image");
    var pokemon4Picture = document.querySelector("#pokemon_4_image");
    var pokemon5Picture = document.querySelector("#pokemon_5_image");
    var pokemon6Picture = document.querySelector("#pokemon_6_image");
    var imgPokemon1 = document.createElement("img");
    var imgPokemon2 = document.createElement("img");
    var imgPokemon3 = document.createElement("img");
    var imgPokemon4 = document.createElement("img");
    var imgPokemon5 = document.createElement("img");
    var imgPokemon6 = document.createElement("img");
    
    pokemon1Picture.innerHTML = "";
    pokemon2Picture.innerHTML = "";
    pokemon3Picture.innerHTML = "";
    pokemon4Picture.innerHTML = "";
    pokemon5Picture.innerHTML = "";
    pokemon6Picture.innerHTML = "";

    
    imgPokemon1.src = "images/pokemon/sv/" + trainerId + "_1.png";
    imgPokemon2.src = "images/pokemon/sv/" + trainerId + "_2.png";
    imgPokemon3.src = "images/pokemon/sv/" + trainerId + "_3.png";
    imgPokemon4.src = "images/pokemon/sv/" + trainerId + "_4.png";
    imgPokemon5.src = "images/pokemon/sv/" + trainerId + "_5.png";
    imgPokemon6.src = "images/pokemon/sv/" + trainerId + "_6.png";

    pokemon1Picture.appendChild(imgPokemon1);
    pokemon2Picture.appendChild(imgPokemon2);
    pokemon3Picture.appendChild(imgPokemon3);
    pokemon4Picture.appendChild(imgPokemon4);
    pokemon5Picture.appendChild(imgPokemon5);
    pokemon6Picture.appendChild(imgPokemon6);
}

katySV.addEventListener('click', displaySVTrainers);
brassiusSV.addEventListener('click', displaySVTrainers);
ionoSV.addEventListener('click', displaySVTrainers);
kofuSV.addEventListener('click', displaySVTrainers);
larrySV.addEventListener('click', displaySVTrainers);
rymeSV.addEventListener('click', displaySVTrainers);
tulipSV.addEventListener('click', displaySVTrainers);
grushaSV.addEventListener('click', displaySVTrainers);
rikaSV.addEventListener('click', displaySVTrainers);
poppySV.addEventListener('click', displaySVTrainers);
larryE4SV.addEventListener('click', displaySVTrainers);
hasselSV.addEventListener('click', displaySVTrainers);
geetaSV.addEventListener('click', displaySVTrainers);
nemonaGSV.addEventListener('click', displaySVTrainers);
nemonaFSV.addEventListener('click', displaySVTrainers);
nemonaWSV.addEventListener('click', displaySVTrainers);
giacomoSV.addEventListener('click', displaySVTrainers);
melaSV.addEventListener('click', displaySVTrainers);
atticusSV.addEventListener('click', displaySVTrainers);
ortegaSV.addEventListener('click', displaySVTrainers);
eriSV.addEventListener('click', displaySVTrainers);
clavellGSV.addEventListener('click', displaySVTrainers);
clavellFSV.addEventListener('click', displaySVTrainers);
clavellWSV.addEventListener('click', displaySVTrainers);
cassiopeiaSV.addEventListener('click', displaySVTrainers);
arvenSV.addEventListener('click', displaySVTrainers);
sadaSV.addEventListener('click', displaySVTrainers);
turoSV.addEventListener('click', displaySVTrainers);
