let miloSWSH = document.querySelector ("#milo1");
let nessaSWSH = document.querySelector ("#nessa1");
let kabuSWSH = document.querySelector ("#kabu1");
let beaSWSH = document.querySelector ("#bea1");
let allisterSWSH = document.querySelector ("#allister1");
let opalSWSH = document.querySelector ("#opal1");
let gordieSWSH = document.querySelector ("#gordie1");
let melonySWSH = document.querySelector ("#melony1");
let piersSWSH = document.querySelector ("#piers1");
let raihanSWSH = document.querySelector ("#raihan1");
let marnieSWSH = document.querySelector ("#marnie1");
let hopGSWSH = document.querySelector ("#hop1_g");
let hopFSWSH = document.querySelector ("#hop1_f");
let hopWSWSH = document.querySelector ("#hop1_w");
let bedeSWSH = document.querySelector ("#bede1");
let nessaCSWSH = document.querySelector ("#nessa2");
let beaCSWSH = document.querySelector ("#bea2");
let allisterCSWSH = document.querySelector ("#allister2");
let raihanCSWSH = document.querySelector ("#raihan2");
let oleanaSWSH = document.querySelector ("#oleana1");
let roseSWSH = document.querySelector ("#rose1");
let leonGSWSH = document.querySelector ("#leon1_g");
let leonFSWSH = document.querySelector ("#leon1_f");
let leonWSWSH = document.querySelector ("#leon1_w");

let swsh_trainers = [
    {
        namea : "Gossifleur",
        levela : "LV: 19",
        typea : "Type: Grass",
        abilitya: "Ability: Regenerator",
        itema : "Item: None",
        hpa : "HP: 47",
        atka : "Atk: 23",
        defa : "Def: 30",
        spatka : "Sp. Atk: 23",
        spdefa : "Sp. Def: 30",
        spda : "Spd: 31",
        move1a : "-Magical Leaf",
        move2a : "-Round",
        move3a : "-Rapid Spin",
        move4a : "",

        nameb : "Eldegoss",
        levelb : "LV: 20",
        typeb : "Type: Grass",
        abilityb: "Ability: Regenerator",
        itemb : "Item: None",
        hpb : "HP: 58 --> 89",
        atkb : "Atk: 29",
        defb : "Def: 49",
        spatkb : "Sp. Atk: 41",
        spdefb : "Sp. Def: 57",
        spdb : "Spd: 29",
        move1b : "-Magical Leaf",
        move2b : "-Round",
        move3b : "-Leafage",
        move4b : "",
    },

    {
        namea : "Goldeen",
        levela : "LV: 22",
        typea : "Type: Water",
        abilitya: "Ability: Swift Swim",
        itema : "Item: None",
        hpa : "HP: 55",
        atka : "Atk: 33",
        defa : "Def: 34",
        spatka : "Sp. Atk: 23",
        spdefa : "Sp. Def: 30",
        spda : "Spd: 39",
        move1a : "-Water Pulse",
        move2a : "-Whirlpool",
        move3a : "-Horn Attack",
        move4a : "-Agility",

        nameb : "Arrokuda",
        levelb : "LV: 23",
        typeb : "Type: Water",
        abilityb: "Ability: Swift Swim",
        itemb : "Item: None",
        hpb : "HP: 55",
        atkb : "Atk: 33",
        defb : "Def: 26",
        spatkb : "Sp. Atk: 26",
        spdefb : "Sp. Def: 24",
        spdb : "Spd: 38",
        move1b : "-Aqua Jet",
        move2b : "-Bite",
        move3b : "-Whirlpool",
        move4b : "-Fury Attack",

        namec : "Drednaw",
        levelc : "LV: 24",
        typec : "Type: Water/Rock",
        abilityc: "Ability: Swift Swim",
        itemc : "Item: None",
        hpc : "HP: 82 --> 131.2",
        atkc : "Atk: 58",
        defc : "Def: 53",
        spatkc : "Sp. Atk: 35",
        spdefc : "Sp. Def: 42",
        spdc : "Spd: 45",
        move1c : "-Razor Shell",
        move2c : "-Water Gun",
        move3c : "-Bite",
        move4c : "-Headbutt",
    },

    {
        namea : "Ninetales",
        levela : "LV: 25",
        typea : "Type: Fire",
        abilitya: "Ability: Flash Fire",
        itema : "Item: None",
        hpa : "HP: 75",
        atka : "Atk: 41",
        defa : "Def: 50",
        spatka : "Sp. Atk: 49",
        spdefa : "Sp. Def: 58",
        spda : "Spd: 58",
        move1a : "-Will-O-Wisp",
        move2a : "-Fire Spin",
        move3a : "-Quick Attack",
        move4a : "-Ember",

        nameb : "Arcanine",
        levelb : "LV: 25",
        typeb : "Type: Fire",
        abilityb: "Ability: Intimidate",
        itemb : "Item: None",
        hpb : "HP: 83",
        atkb : "Atk: 56",
        defb : "Def: 48",
        spatkb : "Sp. Atk: 58",
        spdefb : "Sp. Def: 48",
        spdb : "Spd: 61",
        move1b : "-Will-O-Wisp",
        move2b : "-Flame Wheel",
        move3b : "-Bite",
        move4b : "-Agility",

        namec : "Centiskorch",
        levelc : "LV: 27",
        typec : "Type: Fire/Bug",
        abilityc: "Ability: Flash Fire",
        itemc : "Item: None",
        hpc : "HP: 96 --> 153",
        atkc : "Atk: 72",
        defc : "Def: 49",
        spatkc : "Sp. Atk: 53",
        spdefc : "Sp. Def: 59",
        spdc : "Spd: 45",
        move1c : "-Flame Wheel",
        move2c : "-Coil",
        move3c : "-Bug Bite",
        move4c : "-Smokescreen",
    },

    {
        namea : "Hitmontop",
        levela : "LV: 34",
        typea : "Type: Fighting",
        abilitya: "Ability: Technician",
        itema : "Item: None",
        hpa : "HP: 83",
        atka : "Atk: 81",
        defa : "Def: 74",
        spatka : "Sp. Atk: 29",
        spdefa : "Sp. Def: 84",
        spda : "Spd: 57",
        move1a : "-Triple Kick",
        move2a : "-Quick Attack",
        move3a : "-Counter",
        move4a : "-Revenge",

        nameb : "Pangoro",
        levelb : "LV: 34",
        typeb : "Type: Fighting/Dark",
        abilityb: "Ability: Mold Breaker",
        itemb : "Item: None",
        hpb : "HP: 113",
        atkb : "Atk: 94",
        defb : "Def: 63",
        spatkb : "Sp. Atk: 51",
        spdefb : "Sp. Def: 63",
        spdb : "Spd: 49",
        move1b : "-Bullet Punch",
        move2b : "-Circle Throw",
        move3b : "-Night Slash",
        move4b : "-Work Up",

        namec : "Sirfetch'd",
        levelc : "LV: 35",
        typec : "Type: Fighting",
        abilityc: "Ability: Steadfast",
        itemc : "Item: None",
        hpc : "HP: 93",
        atkc : "Atk: 104",
        defc : "Def: 83",
        spatkc : "Sp. Atk: 51",
        spdefc : "Sp. Def: 67",
        spdc : "Spd: 55",
        move1c : "-Detect",
        move2c : "-Swords Dance",
        move3c : "-Brutal Swing",
        move4c : "-Revenge",

        named : "Machamp",
        leveld : "LV: 36",
        typed : "Type: Fighting",
        abilityd: "Ability: Guts",
        itemd : "Item: None",
        hpd : "HP: 118 --> 194",
        atkd : "Atk: 105",
        defd : "Def: 69",
        spatkd : "Sp. Atk: 53",
        spdefd : "Sp. Def: 80",
        spdd : "Spd: 51",
        move1d : "-Scary Face",
        move2d : "-Revenge",
        move3d : "-Knock Off",
        move4d : "-Strength",
    },

    {
        namea : "Yamask (Galarian)",
        levela : "LV: 34",
        typea : "Type: Ground/Ghost",
        abilitya: "Ability: Wandering Spirit",
        itema : "Item: None",
        hpa : "HP: 74",
        atka : "Atk: 27",
        defa : "Def: 67",
        spatka : "Sp. Atk: 47",
        spdefa : "Sp. Def: 59",
        spda : "Spd: 30",
        move1a : "-Brutal Swing",
        move2a : "-Hex",
        move3a : "-Disable",
        move4a : "",

        nameb : "Mimikyu",
        levelb : "LV: 34",
        typeb : "Type: Ghost/Fairy",
        abilityb: "Ability: Disguise",
        itemb : "Item: None",
        hpb : "HP: 86",
        atkb : "Atk: 71",
        defb : "Def: 64",
        spatkb : "Sp. Atk: 39",
        spdefb : "Sp. Def: 81",
        spdb : "Spd: 82",
        move1b : "-Shadow Sneak",
        move2b : "-Baby-Doll Eyes",
        move3b : "-Hone Claws",
        move4b : "-Slash",

        namec : "Cursola",
        levelc : "LV: 35",
        typec : "Type: Ghost",
        abilityc: "Ability: Weak Armor",
        itemc : "Item: None",
        hpc : "HP: 92",
        atkc : "Atk: 68",
        defc : "Def: 49",
        spatkc : "Sp. Atk: 111",
        spdefc : "Sp. Def: 101",
        spdc : "Spd: 31",
        move1c : "-Ancient Power",
        move2c : "-Curse",
        move3c : "-Hex",
        move4c : "",

        named : "Gengar",
        leveld : "LV: 36",
        typed : "Type: Ghost/Poison",
        abilityd: "Ability: Cursed Body",
        itemd : "Item: None",
        hpd : "HP: 96 --> 158",
        atkd : "Atk: 64",
        defd : "Def: 55",
        spatkd : "Sp. Atk: 105",
        spdefd : "Sp. Def: 66",
        spdd : "Spd: 81",
        move1d : "-Venoshock",
        move2d : "-Hex",
        move3d : "-Hypnosis",
        move4d : "-Payback",
    },

    {
        namea : "Weezing (Galarian)",
        levela : "LV: 36",
        typea : "Type: Poison/Fairy",
        abilitya: "Ability: Levitate",
        itema : "Item: None",
        hpa : "HP: 98",
        atka : "Atk: 75",
        defa : "Def: 96",
        spatka : "Sp. Atk: 71",
        spdefa : "Sp. Def: 60",
        spda : "Spd: 53",
        move1a : "-Sludge",
        move2a : "-Fairy Wind",
        move3a : "-Tackle",
        move4a : "",

        nameb : "Mawile",
        levelb : "LV: 36",
        typeb : "Type: Steel/Fairy",
        abilityb: "Ability: Intimidate",
        itemb : "Item: None",
        hpb : "HP: 87",
        atkb : "Atk: 78",
        defb : "Def: 71",
        spatkb : "Sp. Atk: 45",
        spdefb : "Sp. Def: 50",
        spdb : "Spd: 46",
        move1b : "-Draining Kiss",
        move2b : "-Crunch",
        move3b : "-Iron Defense",
        move4b : "-Astonish",

        namec : "Togekiss",
        levelc : "LV: 37",
        typec : "Type: Fairy/Flying",
        abilityc: "Ability: Hustle",
        itemc : "Item: None",
        hpc : "HP: 115",
        atkc : "Atk: 42",
        defc : "Def: 80",
        spatkc : "Sp. Atk: 99",
        spdefc : "Sp. Def: 95",
        spdc : "Spd: 75",
        move1c : "-Air Slash",
        move2c : "-Draining Kiss",
        move3c : "-Ancient Power",
        move4c : "",

        named : "Alcremie",
        leveld : "LV: 38",
        typed : "Type: Fairy",
        abilityd: "Ability: Sweet Veil",
        itemd : "Item: None",
        hpd : "HP: 105 --> 173",
        atkd : "Atk: 52",
        defd : "Def: 75",
        spatkd : "Sp. Atk: 96",
        spdefd : "Sp. Def: 104",
        spdd : "Spd: 61",
        move1d : "-Draining Kiss",
        move2d : "-Acid Armor",
        move3d : "-Sweet Kiss",
        move4d : "",
    },

    {
        namea : "Barbaracle",
        levela : "LV: 40",
        typea : "Type: Rock/Water",
        abilitya: "Ability: Tough Claws",
        itema : "Item: None",
        hpa : "HP: 113",
        atka : "Atk: 104",
        defa : "Def: 103",
        spatka : "Sp. Atk: 48",
        spdefa : "Sp. Def: 79",
        spda : "Spd: 65",
        move1a : "-Shell Smash",
        move2a : "-Rock Tomb",
        move3a : "-Razor Shell",
        move4a : "",

        nameb : "Shuckle",
        levelb : "LV: 40",
        typeb : "Type: Bug/Rock",
        abilityb: "Ability: Contrary",
        itemb : "Item: None",
        hpb : "HP: 72",
        atkb : "Atk: 19",
        defb : "Def: 195",
        spatkb : "Sp. Atk: 20",
        spdefb : "Sp. Def: 195",
        spdb : "Spd: 13",
        move1b : "-Power Split",
        move2b : "-Stone Edge",
        move3b : "-Struggle Bug",
        move4b : "-Rock Tomb",

        namec : "Stonjourner",
        levelc : "LV: 41",
        typec : "Type: Rock",
        abilityc: "Ability: Power Spot",
        itemc : "Item: None",
        hpc : "HP: 139",
        atkc : "Atk: 113",
        defc : "Def: 121",
        spatkc : "Sp. Atk: 24",
        spdefc : "Sp. Def: 27",
        spdc : "Spd: 74",
        move1c : "-Stealth Rock",
        move2c : "-Rock Tomb",
        move3c : "-Body Slam",
        move4c : "-Wonder Room",

        named : "Coalossal",
        leveld : "LV: 42",
        typed : "Type: Rock/Fire",
        abilityd: "Ability: Steam Engine",
        itemd : "Item: None",
        hpd : "HP: 152 --> 258",
        atkd : "Atk: 88",
        defd : "Def: 114",
        spatkd : "Sp. Atk: 72",
        spdefd : "Sp. Def: 89",
        spdd : "Spd: 38",
        move1d : "-Tar Shot",
        move2d : "-Stealth Rock",
        move3d : "-Heat Crash",
        move4d : "-Rock Tomb",
    },

    {
        namea : "Frosmoth",
        levela : "LV: 40",
        typea : "Type: Ice/Bug",
        abilitya: "Ability: Shield Dust",
        itema : "Item: None",
        hpa : "HP: 112",
        atka : "Atk: 56",
        defa : "Def: 59",
        spatka : "Sp. Atk: 122",
        spdefa : "Sp. Def: 83",
        spda : "Spd: 63",
        move1a : "-Icy Wind",
        move2a : "-Feather Dance",
        move3a : "-Bug Buzz",
        move4a : "-Hail",

        nameb : "Darmanitan (Galar)",
        levelb : "LV: 40",
        typeb : "Type: Ice (Zen: +Fire)",
        abilityb: "Ability: Zen Mode",
        itemb : "Item: None",
        hpb : "HP: 140",
        atkb : "Atk: 123",
        defb : "Def: 55",
        spatkb : "Sp. Atk: 31",
        spdefb : "Sp. Def: 60",
        spdb : "Spd: 87",
        move1b : "-Icicle Crash",
        move2b : "-Headbutt",
        move3b : "-Taunt",
        move4b : "-Fire Fang",

        namec : "Eiscue",
        levelc : "LV: 41",
        typec : "Type: Ice",
        abilityc: "Ability: Ice Face",
        itemc : "Item: None",
        hpc : "HP: 118",
        atkc : "Atk: 76",
        defc : "Def: 101",
        spatkc : "Sp. Atk: 64",
        spdefc : "Sp. Def: 92",
        spdc : "Spd: 46",
        move1c : "-Amnesia",
        move2c : "-Freeze-Dry",
        move3c : "-Hail",
        move4c : "-Icy Wind",

        named : "Lapras",
        leveld : "LV: 42",
        typed : "Type: Water Ice",
        abilityd: "Ability: Shell Armor",
        itemd : "Item: None",
        hpd : "HP: 169 --> 287",
        atkd : "Atk: 75",
        defd : "Def: 80",
        spatkd : "Sp. Atk: 92",
        spdefd : "Sp. Def: 93",
        spdd : "Spd: 63",
        move1d : "-Icy Wind",
        move2d : "-Ice Beam",
        move3d : "-Surf",
        move4d : "-Sing",
    },

    {
        namea : "Scrafty",
        levela : "LV: 44",
        typea : "Type: Dark/Fighting",
        abilitya: "Ability: Intimidate",
        itema : "Item: None",
        hpa : "HP: 117",
        atka : "Atk: 99",
        defa : "Def: 112",
        spatka : "Sp. Atk: 45",
        spdefa : "Sp. Def: 112",
        spda : "Spd: 62",
        move1a : "-Fake Out",
        move2a : "-Sand Attack",
        move3a : "-Brick Break",
        move4a : "-Payback",

        nameb : "Malamar",
        levelb : "LV: 45",
        typeb : "Type: Dark/Psychic",
        abilityb: "Ability: Contrary",
        itemb : "Item: None",
        hpb : "HP: 139",
        atkb : "Atk: 103",
        defb : "Def: 90",
        spatkb : "Sp. Atk: 64",
        spdefb : "Sp. Def: 79",
        spdb : "Spd: 77",
        move1b : "-Night Slash",
        move2b : "-Foul Play",
        move3b : "-Psycho Cut",
        move4b : "-Payback",

        namec : "Skuntank",
        levelc : "LV: 45",
        typec : "Type: Poison/Dark",
        abilityc: "Ability: Aftermath",
        itemc : "Item: None",
        hpc : "HP: 161",
        atkc : "Atk: 112",
        defc : "Def: 79",
        spatkc : "Sp. Atk: 82",
        spdefc : "Sp. Def: 73",
        spdc : "Spd: 84",
        move1c : "-Sucker Punch",
        move2c : "-Screech",
        move3c : "-Toxic",
        move4c : "-Snarl",

        named : "Obstagoon",
        leveld : "LV: 46",
        typed : "Type: Dark/Normal",
        abilityd: "Ability: Reckless",
        itemd : "Item: None",
        hpd : "HP: 179",
        atkd : "Atk: 97",
        defd : "Def: 149",
        spatkd : "Sp. Atk: 69",
        spdefd : "Sp. Def: 88",
        spdd : "Spd: 90",
        move1d : "-Obstruct",
        move2d : "-Throat Chop",
        move3d : "-Counter",
        move4d : "-Shadow Claw",
    },

    {
        namea : "Gigalith",
        levela : "LV: 46",
        typea : "Type: Rock",
        abilitya: "Ability: Sand Stream",
        itema : "Item: None",
        hpa : "HP: 141",
        atka : "Atk: 136",
        defa : "Def: 131",
        spatka : "Sp. Atk: 60",
        spdefa : "Sp. Def: 93",
        spda : "Spd: 34",
        move1a : "-Stealth Rock",
        move2a : "-Sand Tomb",
        move3a : "-Rock Blast",
        move4a : "-Body Press",

        nameb : "Flygon",
        levelb : "LV: 47",
        typeb : "Type: Ground/Dragon",
        abilityb: "Ability: Levitate",
        itemb : "Item: None",
        hpb : "HP: 139",
        atkb : "Atk: 106",
        defb : "Def: 87",
        spatkb : "Sp. Atk: 78",
        spdefb : "Sp. Def: 87",
        spdb : "Spd: 116",
        move1b : "-Thunder Punch",
        move2b : "-Breaking Swipe",
        move3b : "-Crunch",
        move4b : "-Steel Wing",

        namec : "Sandaconda",
        levelc : "LV: 46",
        typec : "Type: Ground",
        abilityc: "Ability: Sand Spit",
        itemc : "Item: None",
        hpc : "HP: 129",
        atkc : "Atk: 99",
        defc : "Def: 126",
        spatkc : "Sp. Atk: 71",
        spdefc : "Sp. Def: 83",
        spdc : "Spd: 77",
        move1c : "-Protect",
        move2c : "-Glare",
        move3c : "-Fire Fang",
        move4c : "-Earth Power",

        named : "Duraludon",
        leveld : "LV: 48",
        typed : "Type: Steel/Dragon",
        abilityd: "Ability: Heavy Metal",
        itemd : "Item: None",
        hpd : "HP: 134 --> 234",
        atkd : "Atk: 105",
        defd : "Def: 125",
        spatkd : "Sp. Atk: 116",
        spdefd : "Sp. Def: 62",
        spdd : "Spd: 105",
        move1d : "-Breaking Swipe",
        move2d : "-Body Press",
        move3d : "-Stone Edge",
        move4d : "-Iron Head",
    },

    {
        namea : "Liepard",
        levela : "LV: 47",
        typea : "Type: Dark",
        abilitya: "Ability: Prankster",
        itema : "Item: None",
        hpa : "HP: 124",
        atka : "Atk: 84",
        defa : "Def: 59",
        spatka : "Sp. Atk: 94",
        spdefa : "Sp. Def: 59",
        spda : "Spd: 122",
        move1a : "-Fake Out",
        move2a : "-Torment",
        move3a : "-Nasty Plot",
        move4a : "-Snarl",

        nameb : "Toxicroak",
        levelb : "LV: 47",
        typeb : "Type: Poison/Fighting",
        abilityb: "Ability: Dry Skin",
        itemb : "Item: None",
        hpb : "HP: 142",
        atkb : "Atk: 122",
        defb : "Def: 73",
        spatkb : "Sp. Atk: 82",
        spdefb : "Sp. Def: 73",
        spdb : "Spd: 91",
        move1b : "-Venoshock",
        move2b : "-Sucker Punch",
        move3b : "-Swagger",
        move4b : "-Toxic",

        namec : "Scrafty",
        levelc : "LV: 47",
        typec : "Type: Dark/Fighting",
        abilityc: "Ability: Shed Skin",
        itemc : "Item: None",
        hpc : "HP: 125",
        atkc : "Atk: 105",
        defc : "Def: 120",
        spatkc : "Sp. Atk: 48",
        spdefc : "Sp. Def: 120",
        spdc : "Spd: 66",
        move1c : "-Swagger",
        move2c : "-Scary Face",
        move3c : "-Brick Break",
        move4c : "-Crunch",

        named : "Morpeko",
        leveld : "LV: 48",
        typed : "Type: Electric/Dark",
        abilityd: "Ability: Hunger Switch",
        itemd : "Item: None",
        hpd : "HP: 120",
        atkd : "Atk: 103",
        defd : "Def: 67",
        spatkd : "Sp. Atk: 71",
        spdefd : "Sp. Def: 67",
        spdd : "Spd: 115",
        move1d : "-Bullet Seed",
        move2d : "-Torment",
        move3d : "-Spark",
        move4d : "-Bite",

        namee : "Grimmsnarl",
        levele : "LV: 49",
        typee : "Type: Dark/Fairy",
        abilitye: "Ability: Prankster",
        iteme : "Item: None",
        hpe : "HP: 159 --> 270",
        atke : "Atk: 141",
        defe : "Def: 76",
        spatke : "Sp. Atk: 94",
        spdefe : "Sp. Def: 85",
        spde : "Spd: 71",
        move1e : "-Spirit Break",
        move2e : "-Darkest Lariat",
        move3e : "-Bulk Up",
        move4e : "-Torment",
    },

    {
        namea : "Dubwool",
        levela : "LV: 48",
        typea : "Type: Normal",
        abilitya: "Ability: Steadfast",
        itema : "Item: None",
        hpa : "HP: 129",
        atka : "Atk: 84",
        defa : "Def: 92",
        spatka : "Sp. Atk: 65",
        spdefa : "Sp. Def: 93",
        spda : "Spd: 100",
        move1a : "-Cotton Guard",
        move2a : "-Reversal",
        move3a : "-Body Slam",
        move4a : "-Zen Headbutt",

        nameb : "Corviknight",
        levelb : "LV: 48",
        typeb : "Type: Flying/Steel",
        abilityb: "Ability: Unnerve",
        itemb : "Item: None",
        hpb : "HP: 159",
        atkb : "Atk: 95",
        defb : "Def: 113",
        spatkb : "Sp. Atk: 56",
        spdefb : "Sp. Def: 93",
        spdb : "Spd: 83",
        move1b : "-Steel Wing",
        move2b : "-Drill Peck",
        move3b : "-Scary Face",
        move4b : "-Swagger",

        namec : "Pincurchin",
        levelc : "LV: 47",
        typec : "Type: Electric",
        abilityc: "Ability: Lightning Rod",
        itemc : "Item: None",
        hpc : "HP: 113",
        atkc : "Atk: 111",
        defc : "Def: 106",
        spatkc : "Sp. Atk: 102",
        spdefc : "Sp. Def: 105",
        spdc : "Spd: 27",
        move1c : "-Thunderbolt",
        move2c : "-Poison Jab",
        move3c : "-Curse",
        move4c : "",

        named : "Snorlax",
        leveld : "LV: 47",
        typed : "Type: Normal",
        abilityd: "Ability: Thick Fat",
        itemd : "Item: None",
        hpd : "HP: 212",
        atkd : "Atk: 101",
        defd : "Def: 77",
        spatkd : "Sp. Atk: 70",
        spdefd : "Sp. Def: 113",
        spdd : "Spd: 37",
        move1d : "-Heavy Slam",
        move2d : "-High Horsepower",
        move3d : "-Hammer Arm",
        move4d : "",

        namee : "Rillaboom",
        levele : "LV: 49",
        typee : "Type: Grass",
        abilitye: "Ability: Overgrow",
        iteme : "Item: None",
        hpe : "HP: 164 --> 270",
        atke : "Atk: 134",
        defe : "Def: 100",
        spatke : "Sp. Atk: 76",
        spdefe : "Sp. Def: 85",
        spde : "Spd: 98",
        move1e : "-Drum Beating",
        move2e : "-High Horsepower",
        move3e : "-Snarl",
        move4e : "-Uproar",
    },

    {
        namea : "Dubwool",
        levela : "LV: 48",
        typea : "Type: Normal",
        abilitya: "Ability: Steadfast",
        itema : "Item: None",
        hpa : "HP: 129",
        atka : "Atk: 84",
        defa : "Def: 92",
        spatka : "Sp. Atk: 65",
        spdefa : "Sp. Def: 93",
        spda : "Spd: 100",
        move1a : "-Cotton Guard",
        move2a : "-Reversal",
        move3a : "-Body Slam",
        move4a : "-Zen Headbutt",

        nameb : "Corviknight",
        levelb : "LV: 48",
        typeb : "Type: Flying/Steel",
        abilityb: "Ability: Unnerve",
        itemb : "Item: None",
        hpb : "HP: 159",
        atkb : "Atk: 95",
        defb : "Def: 113",
        spatkb : "Sp. Atk: 56",
        spdefb : "Sp. Def: 93",
        spdb : "Spd: 83",
        move1b : "-Steel Wing",
        move2b : "-Drill Peck",
        move3b : "-Scary Face",
        move4b : "-Swagger",

        namec : "Pincurchin",
        levelc : "LV: 47",
        typec : "Type: Electric",
        abilityc: "Ability: Lightning Rod",
        itemc : "Item: None",
        hpc : "HP: 113",
        atkc : "Atk: 111",
        defc : "Def: 106",
        spatkc : "Sp. Atk: 102",
        spdefc : "Sp. Def: 105",
        spdc : "Spd: 27",
        move1c : "-Thunderbolt",
        move2c : "-Poison Jab",
        move3c : "-Curse",
        move4c : "",

        named : "Snorlax",
        leveld : "LV: 47",
        typed : "Type: Normal",
        abilityd: "Ability: Thick Fat",
        itemd : "Item: None",
        hpd : "HP: 212",
        atkd : "Atk: 101",
        defd : "Def: 77",
        spatkd : "Sp. Atk: 70",
        spdefd : "Sp. Def: 113",
        spdd : "Spd: 37",
        move1d : "-Heavy Slam",
        move2d : "-High Horsepower",
        move3d : "-Hammer Arm",
        move4d : "",

        namee : "Cinderace",
        levele : "LV: 49",
        typee : "Type: Fire",
        abilitye: "Ability: Blaze",
        iteme : "Item: None",
        hpe : "HP: 144 --> 237",
        atke : "Atk: 126",
        defe : "Def: 85",
        spatke : "Sp. Atk: 80",
        spdefe : "Sp. Def: 90",
        spde : "Spd: 131",
        move1e : "-Pyro Ball",
        move2e : "-Counter",
        move3e : "-Gunk Shot",
        move4e : "-Bounce",
    },

    {
        namea : "Dubwool",
        levela : "LV: 48",
        typea : "Type: Normal",
        abilitya: "Ability: Steadfast",
        itema : "Item: None",
        hpa : "HP: 129",
        atka : "Atk: 84",
        defa : "Def: 92",
        spatka : "Sp. Atk: 65",
        spdefa : "Sp. Def: 93",
        spda : "Spd: 100",
        move1a : "-Cotton Guard",
        move2a : "-Reversal",
        move3a : "-Body Slam",
        move4a : "-Zen Headbutt",

        nameb : "Corviknight",
        levelb : "LV: 48",
        typeb : "Type: Flying/Steel",
        abilityb: "Ability: Unnerve",
        itemb : "Item: None",
        hpb : "HP: 159",
        atkb : "Atk: 95",
        defb : "Def: 113",
        spatkb : "Sp. Atk: 56",
        spdefb : "Sp. Def: 93",
        spdb : "Spd: 83",
        move1b : "-Steel Wing",
        move2b : "-Drill Peck",
        move3b : "-Scary Face",
        move4b : "-Swagger",

        namec : "Pincurchin",
        levelc : "LV: 47",
        typec : "Type: Electric",
        abilityc: "Ability: Lightning Rod",
        itemc : "Item: None",
        hpc : "HP: 113",
        atkc : "Atk: 111",
        defc : "Def: 106",
        spatkc : "Sp. Atk: 102",
        spdefc : "Sp. Def: 105",
        spdc : "Spd: 27",
        move1c : "-Thunderbolt",
        move2c : "-Poison Jab",
        move3c : "-Curse",
        move4c : "",

        named : "Snorlax",
        leveld : "LV: 47",
        typed : "Type: Normal",
        abilityd: "Ability: Thick Fat",
        itemd : "Item: None",
        hpd : "HP: 212",
        atkd : "Atk: 101",
        defd : "Def: 77",
        spatkd : "Sp. Atk: 70",
        spdefd : "Sp. Def: 113",
        spdd : "Spd: 37",
        move1d : "-Heavy Slam",
        move2d : "-High Horsepower",
        move3d : "-Hammer Arm",
        move4d : "",

        namee : "Inteleon",
        levele : "LV: 49",
        typee : "Type: Water",
        abilitye: "Ability: Torrent",
        iteme : "Item: None",
        hpe : "HP: 134 --> 214",
        atke : "Atk: 95",
        defe : "Def: 76",
        spatke : "Sp. Atk: 139",
        spdefe : "Sp. Def: 80",
        spde : "Spd: 132",
        move1e : "-Snipe Shot",
        move2e : "-Mud Shot",
        move3e : "-Icy Wind",
        move4e : "-Dark Pulse",
    },

    {
        namea : "Froslass",
        levela : "LV: 50",
        typea : "Type: Ice/Ghost",
        abilitya: "Ability: Snow Cloak",
        itema : "Item: None",
        hpa : "HP: 137",
        atka : "Atk: 82",
        defa : "Def: 82",
        spatka : "Sp. Atk: 92",
        spdefa : "Sp. Def: 82",
        spda : "Spd: 134",
        move1a : "-Will-O-Wisp",
        move2a : "-Hex",
        move3a : "-Icy Wind",
        move4a : "-Double Team",

        nameb : "Tsareena",
        levelb : "LV: 50",
        typeb : "Type: Grass",
        abilityb: "Ability: Queenly Majesty",
        itemb : "Item: None",
        hpb : "HP: 139",
        atkb : "Atk: 132",
        defb : "Def: 110",
        spatkb : "Sp. Atk: 55",
        spdefb : "Sp. Def: 110",
        spdb : "Spd: 92",
        move1b : "-Trop Kick",
        move2b : "-Acrobatics",
        move3b : "-Stomp",
        move4b : "-Attract",

        namec : "Salazzle",
        levelc : "LV: 50",
        typec : "Type: Poison/Fire",
        abilityc: "Ability: Corrosion",
        itemc : "Item: None",
        hpc : "HP: 135",
        atkc : "Atk: 68",
        defc : "Def: 72",
        spatkc : "Sp. Atk: 123",
        spdefc : "Sp. Def: 72",
        spdc : "Spd: 141",
        move1c : "-Poison Gas",
        move2c : "-Venoshock",
        move3c : "-Incinerate",
        move4c : "-Dragon Pulse",

        named : "Milotic",
        leveld : "LV: 51",
        typed : "Type: Water",
        abilityd: "Ability: Competitive",
        itemd : "Item: None",
        hpd : "HP: 165",
        atkd : "Atk: 65",
        defd : "Def: 102",
        spatkd : "Sp. Atk: 114",
        spdefd : "Sp. Def: 140",
        spdd : "Spd: 95",
        move1d : "-Surf",
        move2d : "-Safeguard",
        move3d : "-Aqua Ring",
        move4d : "-Recover",

        namee : "Garbodor",
        levele : "LV: 52",
        typee : "Type: Poison",
        abilitye: "Ability: Weak Armor",
        iteme : "Item: None",
        hpe : "HP: 155 --> 240",
        atke : "Atk: 125",
        defe : "Def: 100",
        spatke : "Sp. Atk: 69",
        spdefe : "Sp. Def: 100",
        spde : "Spd: 93",
        move1e : "-Gunk Shot",
        move2e : "-Stomping Tantrum",
        move3e : "-Rock Blast",
        move4e : "-Toxic Spikes",
    },

    {
        namea : "Mawile",
        levela : "LV: 51",
        typea : "Type: Steel/Fairy",
        abilitya: "Ability: Intimidate",
        itema : "Item: None",
        hpa : "HP: 119",
        atka : "Atk: 108",
        defa : "Def: 99",
        spatka : "Sp. Atk: 61",
        spdefa : "Sp. Def: 68",
        spda : "Spd: 63",
        move1a : "-Play Rough",
        move2a : "-Iron Head",
        move3a : "-Crunch",
        move4a : "",

        nameb : "Gardevoir",
        levelb : "LV: 51",
        typeb : "Type: Psychic/Fairy",
        abilityb: "Ability: Synchronize",
        itemb : "Item: None",
        hpb : "HP: 138",
        atkb : "Atk: 70",
        defb : "Def: 78",
        spatkb : "Sp. Atk: 140",
        spdefb : "Sp. Def: 129",
        spdb : "Spd: 103",
        move1b : "-Dazzling Gleam",
        move2b : "-Psychic",
        move3b : "-Calm Mind",
        move4b : "-Wish",

        namec : "Rapidash (Galarian)",
        levelc : "LV: 52",
        typec : "Type: Psychic/Fairy",
        abilityc: "Ability: Pastel Veil",
        itemc : "Item: None",
        hpc : "HP: 137",
        atkc : "Atk: 127",
        defc : "Def: 85",
        spatkc : "Sp. Atk: 86",
        spdefc : "Sp. Def: 96",
        spdc : "Spd: 122",
        move1c : "-Psycho Cut",
        move2c : "-Take Down",
        move3c : "-Dazzling Gleam",
        move4c : "-Quick Attack",

        named : "Hatterene",
        leveld : "LV: 53",
        typed : "Type: Psychic/Fairy",
        abilityd: "Ability: Anticipation",
        itemd : "Item: None",
        hpd : "HP: 131 --> 222",
        atkd : "Atk: 97",
        defd : "Def: 113",
        spatkd : "Sp. Atk: 172",
        spdefd : "Sp. Def: 122",
        spdd : "Spd: 43",
        move1d : "-Psychic",
        move2d : "-Dazzling Gleam",
        move3d : "-Calm Mind",
        move4d : "-Mystical Fire",
    },

    {
        namea : "Golisopod",
        levela : "LV: 51",
        typea : "Type: Bug/Water",
        abilitya: "Ability: Emergency Exit",
        itema : "Item: None",
        hpa : "HP: 145",
        atka : "Atk: 140",
        defa : "Def: 155",
        spatka : "Sp. Atk: 65",
        spdefa : "Sp. Def: 104",
        spda : "Spd: 58",
        move1a : "-First Impression",
        move2a : "-Liquidation",
        move3a : "-Swords Dance",
        move4a : "-Shadow Claw",

        nameb : "Pelipper",
        levelb : "LV: 51",
        typeb : "Type: Water/Flying",
        abilityb: "Ability: Drizzle",
        itemb : "Item: None",
        hpb : "HP: 129",
        atkb : "Atk: 56",
        defb : "Def: 125",
        spatkb : "Sp. Atk: 109",
        spdefb : "Sp. Def: 84",
        spdb : "Spd: 78",
        move1b : "-Roost",
        move2b : "-Air Slash",
        move3b : "-Water Pulse",
        move4b : "-Tailwind",

        namec : "Barraskewda",
        levelc : "LV: 52",
        typec : "Type: Water",
        abilityc: "Ability: Swift Swim",
        itemc : "Item: None",
        hpc : "HP: 133",
        atkc : "Atk: 126",
        defc : "Def: 75",
        spatkc : "Sp. Atk: 75",
        spdefc : "Sp. Def: 70",
        spdc : "Spd: 154",
        move1c : "-Liquidation",
        move2c : "-Throat Chop",
        move3c : "-Ice Fang",
        move4c : "-Drill Run",

        named : "Seaking",
        leveld : "LV: 52",
        typed : "Type: Water",
        abilityd: "Ability: Swift Swim",
        itemd : "Item: None",
        hpd : "HP: 153",
        atkd : "Atk: 97",
        defd : "Def: 80",
        spatkd : "Sp. Atk: 80",
        spdefd : "Sp. Def: 96",
        spdd : "Spd: 91",
        move1d : "-Smart Strike",
        move2d : "-Megahorn",
        move3d : "-Aqua Ring",
        move4d : "-Waterfall",

        namee : "Drednaw",
        levele : "LV: 53",
        typee : "Type: Water/Rock",
        abilitye: "Ability: Shell Armor",
        iteme : "Item: None",
        hpe : "HP: 169 --> 295",
        atke : "Atk: 150",
        defe : "Def: 111",
        spatke : "Sp. Atk: 59",
        spdefe : "Sp. Def: 87",
        spde : "Spd: 94",
        move1e : "-Liquidation",
        move2e : "-Jaw Lock",
        move3e : "-Rock Tomb",
        move4e : "-Crunch",
    },

    {
        namea : "Hawlucha",
        levela : "LV: 52",
        typea : "Type: Fightning/Flying",
        abilitya: "Ability: Limber",
        itema : "Item: None",
        hpa : "HP: 150",
        atka : "Atk: 118",
        defa : "Def: 90",
        spatka : "Sp. Atk: 80",
        spdefa : "Sp. Def: 78",
        spda : "Spd: 135",
        move1a : "-Flying Press",
        move2a : "-High Jump Kick",
        move3a : "-Bounce",
        move4a : "",

        nameb : "Grapploct",
        levelb : "LV: 52",
        typeb : "Type: Fighting",
        abilityb: "Ability: Limber",
        itemb : "Item: None",
        hpb : "HP: 153",
        atkb : "Atk: 121",
        defb : "Def: 116",
        spatkb : "Sp. Atk: 85",
        spdefb : "Sp. Def: 96",
        spdb : "Spd: 56",
        move1b : "-Octolock",
        move2b : "-Submission",
        move3b : "-Bind",
        move4b : "-Mega Punch",

        namec : "Sirfetch'd",
        levelc : "LV: 53",
        typec : "Type: Fighting",
        abilityc: "Ability: Steadfast",
        itemc : "Item: None",
        hpc : "HP: 136",
        atkc : "Atk: 156",
        defc : "Def: 124",
        spatkc : "Sp. Atk: 76",
        spdefc : "Sp. Def: 99",
        spdc : "Spd: 81",
        move1c : "-Leaf Blade",
        move2c : "-Slam",
        move3c : "-Brick Break",
        move4c : "-Brutal Swing",

        named : "Falinks",
        leveld : "LV: 53",
        typed : "Type: Fighting",
        abilityd: "Ability: Battle Armor",
        itemd : "Item: None",
        hpd : "HP: 139",
        atkd : "Atk: 106",
        defd : "Def: 129",
        spatkd : "Sp. Atk: 87",
        spdefd : "Sp. Def: 76",
        spdd : "Spd: 92",
        move1d : "-No Retreat",
        move2d : "-Bulk Up",
        move3d : "-Close Combat",
        move4d : "-Rock Tomb",

        namee : "Machamp",
        levele : "LV: 54",
        typee : "Type: Fighting",
        abilitye: "Ability: Guts",
        iteme : "Item: None",
        hpe : "HP: 172 --> 292",
        atke : "Atk: 156",
        defe : "Def: 102",
        spatke : "Sp. Atk: 77",
        spdefe : "Sp. Def: 117",
        spde : "Spd: 75",
        move1e : "-Cross Chop",
        move2e : "-Revenge",
        move3e : "-Fire Punch",
        move4e : "-Strength",
    },

    {
        namea : "Dusknoir",
        levela : "LV: 52",
        typea : "Type: Ghost",
        abilitya: "Ability: Pressure",
        itema : "Item: None",
        hpa : "HP: 116",
        atka : "Atk: 104",
        defa : "Def: 168",
        spatka : "Sp. Atk: 80",
        spdefa : "Sp. Def: 153",
        spda : "Spd: 59",
        move1a : "-Shadow Punch",
        move2a : "-Thunder Punch",
        move3a : "-Rock Tomb",
        move4a : "-Disable",

        nameb : "Chandelure",
        levelb : "LV: 52",
        typeb : "Type: Ghost/Fire",
        abilityb: "Ability: Flash Fire",
        itemb : "Item: None",
        hpb : "HP: 132",
        atkb : "Atk: 63",
        defb : "Def: 106",
        spatkb : "Sp. Atk: 163",
        spdefb : "Sp. Def: 106",
        spdb : "Spd: 105",
        move1b : "-Shadow Ball",
        move2b : "-Mystical Fire",
        move3b : "-Will-O-Wisp",
        move4b : "",

        namec : "Cursola",
        levelc : "LV: 53",
        typec : "Type: Ghost",
        abilityc: "Ability: Weak Armor",
        itemc : "Item: None",
        hpc : "HP: 134",
        atkc : "Atk: 101",
        defc : "Def: 71",
        spatkc : "Sp. Atk: 166",
        spdefc : "Sp. Def: 150",
        spdc : "Spd: 44",
        move1c : "-Hex",
        move2c : "-Strength Sap",
        move3c : "-Ancient Power",
        move4c : "-Amnesia",

        named : "Polteageist",
        leveld : "LV: 53",
        typed : "Type: Ghost",
        abilityd: "Ability: Weak Armor",
        itemd : "Item: None",
        hpd : "HP: 134",
        atkd : "Atk: 72",
        defd : "Def: 81",
        spatkd : "Sp. Atk: 154",
        spdefd : "Sp. Def: 133",
        spdd : "Spd: 95",
        move1d : "-Shadow Ball",
        move2d : "-Protect",
        move3d : "-Nasty Plot",
        move4d : "-Giga Drain",

        namee : "Gengar",
        levele : "LV: 54",
        typee : "Type: Ghost/Poison",
        abilitye: "Ability: Cursed Body",
        iteme : "Item: None",
        hpe : "HP: 139 --> 236",
        atke : "Atk: 94",
        defe : "Def: 80",
        spatke : "Sp. Atk: 156",
        spdefe : "Sp. Def: 96",
        spde : "Spd: 120",
        move1e : "-Shadow Ball",
        move2e : "-Sludge Bomb",
        move3e : "-Dark Pulse",
        move4e : "-Hypnosis",
    },

    {
        namea : "Torkoal",
        levela : "LV: 53",
        typea : "Type: Fire",
        abilitya: "Ability: Drought",
        itema : "Item: None",
        hpa : "HP: 145",
        atka : "Atk: 113",
        defa : "Def: 161",
        spatka : "Sp. Atk: 103",
        spdefa : "Sp. Def: 87",
        spda : "Spd: 30",
        move1a : "-Lava Plume",
        move2a : "-Body Press",
        move3a : "-Solar Beam",
        move4a : "-Yawn",

        nameb : "Goodra",
        levelb : "LV: 54",
        typeb : "Type: Dragon",
        abilityb: "Ability: Sap Sipper",
        itemb : "Item: None",
        hpb : "HP: 169",
        atkb : "Atk: 121",
        defb : "Def: 88",
        spatkb : "Sp. Atk: 144",
        spdefb : "Sp. Def: 175",
        spdb : "Spd: 89",
        move1b : "-Rain Dance",
        move2b : "-Surf",
        move3b : "-Thunder",
        move4b : "-Muddy Water",

        namec : "Turtonator",
        levelc : "LV: 54",
        typec : "Type: Fire/Dragon",
        abilityc: "Ability: Shell Armor",
        itemc : "Item: None",
        hpc : "HP: 136",
        atkc : "Atk: 97",
        defc : "Def: 158",
        spatkc : "Sp. Atk: 122",
        spdefc : "Sp. Def: 104",
        spdc : "Spd: 45",
        move1c : "-Sunny Day",
        move2c : "-Dragon Pulse",
        move3c : "-Shell Trap",
        move4c : "-Fire Blast",

        named : "Flygon",
        leveld : "LV: 54",
        typed : "Type: Ground/Dragon",
        abilityd: "Ability: Levitate",
        itemd : "Item: None",
        hpd : "HP: 158",
        atkd : "Atk: 121",
        defd : "Def: 99",
        spatkd : "Sp. Atk: 89",
        spdefd : "Sp. Def: 99",
        spdd : "Spd: 133",
        move1d : "-Sandstorm",
        move2d : "-Dragon Claw",
        move3d : "-Earthquake",
        move4d : "-Crunch",

        namee : "Duraludon",
        levele : "LV: 55",
        typee : "Type: Steel/Dragon",
        abilitye: "Ability: Light Metal",
        iteme : "Item: None",
        hpe : "HP: 153 --> 267",
        atke : "Atk: 120",
        defe : "Def: 142",
        spatke : "Sp. Atk: 133",
        spdefe : "Sp. Def: 71",
        spde : "Spd: 119",
        move1e : "-Dragon Claw",
        move2e : "-Body Press",
        move3e : "-Stone Edge",
        move4e : "-Iron Head",
    },

    {
        namea : "Escavalier",
        levela : "LV: 55",
        typea : "Type: Bug/Steel",
        abilitya: "Ability: Shell Armor",
        itema : "Item: None",
        hpa : "HP: 153",
        atka : "Atk: 180",
        defa : "Def: 131",
        spatka : "Sp. Atk: 82",
        spdefa : "Sp. Def: 131",
        spda : "Spd: 34",
        move1a : "-Drill Run",
        move2a : "-Iron Head",
        move3a : "-Megahorn",
        move4a : "-Swords Dance",

        nameb : "Ferrothorn",
        levelb : "LV: 55",
        typeb : "Type: Grass/Steel",
        abilityb: "Ability: Iron Barbs",
        itemb : "Item: None",
        hpb : "HP: 157",
        atkb : "Atk: 130",
        defb : "Def: 160",
        spatkb : "Sp. Atk: 75",
        spdefb : "Sp. Def: 143",
        spdb : "Spd: 34",
        move1b : "-Gyro Ball",
        move2b : "-Power Whip",
        move3b : "-Curse",
        move4b : "-Body Press",

        namec : "Perrserker",
        levelc : "LV: 55",
        typec : "Type: Steel",
        abilityc: "Ability: Tough Claws",
        itemc : "Item: None",
        hpc : "HP: 153",
        atkc : "Atk: 150",
        defc : "Def: 126",
        spatkc : "Sp. Atk: 71",
        spdefc : "Sp. Def: 82",
        spdc : "Spd: 63",
        move1c : "-Iron Head",
        move2c : "-Screech",
        move3c : "-Shadow Claw",
        move4c : "-Throat Chop",

        named : "Klinklang",
        leveld : "LV: 56",
        typed : "Type: Steel",
        abilityd: "Ability: Minus",
        itemd : "Item: None",
        hpd : "HP: 144",
        atkd : "Atk: 128",
        defd : "Def: 145",
        spatkd : "Sp. Atk: 84",
        spdefd : "Sp. Def: 111",
        spdd : "Spd: 128",
        move1d : "-Shift Gear",
        move2d : "-Gear Grind",
        move3d : "-Wild Charge",
        move4d : "-Assurance",

        namee : "Copperajah",
        levele : "LV: 57",
        typee : "Type: Steel",
        abilitye: "Ability: Sheer Force",
        iteme : "Item: None",
        hpe : "HP: 217 --> 379",
        atke : "Atk: 180",
        defe : "Def: 95",
        spatke : "Sp. Atk: 96",
        spdefe : "Sp. Def: 95",
        spde : "Spd: 50",
        move1e : "-Heavy Slam",
        move2e : "-Iron Head",
        move3e : "-High Horsepower",
        move4e : "-Zen Headbutt",
    },

    {
        namea : "Aegislash",
        levela : "LV: 62",
        typea : "Type: Steel/Ghost",
        abilitya: "Ability: Stance Change",
        itema : "Item: None",
        hpa : "HP: 158",
        atka : "Atk: 79 <--> 191",
        defa : "Def: 191 <--> 79",
        spatka : "Sp. Atk: 86 <--> 210",
        spdefa : "Sp. Def: 191 <--> 79",
        spda : "Spd: 81",
        move1a : "-King's Shield",
        move2a : "-Shadow Ball",
        move3a : "-Sacred Sword",
        move4a : "-Flash Cannon",

        nameb : "Dragapult",
        levelb : "LV: 62",
        typeb : "Type: Dragon/Ghost",
        abilityb: "Ability: Clear Body",
        itemb : "Item: None",
        hpb : "HP: 193",
        atkb : "Atk: 149",
        defb : "Def: 110",
        spatkb : "Sp. Atk: 155",
        spdefb : "Sp. Def: 110",
        spdb : "Spd: 193",
        move1b : "-Shadow Ball",
        move2b : "-Flamethrower",
        move3b : "-Thunderbolt",
        move4b : "-Dragon Breath",

        namec : "Haxorus",
        levelc : "LV: 63",
        typec : "Type: Dragon",
        abilityc: "Ability: Mold Breaker",
        itemc : "Item: None",
        hpc : "HP: 181",
        atkc : "Atk: 202",
        defc : "Def: 131",
        spatkc : "Sp. Atk: 83",
        spdefc : "Sp. Def: 105",
        spdc : "Spd: 152",
        move1c : "-Poison Jab",
        move2c : "-Iron Tail",
        move3c : "-Outrage",
        move4c : "-Earthquake",

        named : "Rhyperior",
        leveld : "LV: 64",
        typed : "Type: Ground/Rock",
        abilityd: "Ability: Solid Rock",
        itemd : "Item: None",
        hpd : "HP: 234",
        atkd : "Atk: 216",
        defd : "Def: 184",
        spatkd : "Sp. Atk: 79",
        spdefd : "Sp. Def: 88",
        spdd : "Spd: 69",
        move1d : "-Earthquake",
        move2d : "-Stone Edge",
        move3d : "-Megahorn",
        move4d : "-Heat Crash",

        namee : "Rillaboom",
        levele : "LV: 64",
        typee : "Type: Grass",
        abilitye: "Ability: Overgrow",
        iteme : "Item: None",
        hpe : "HP: 214",
        atke : "Atk: 194",
        defe : "Def: 133",
        spatke : "Sp. Atk: 84",
        spdefe : "Sp. Def: 107",
        spde : "Spd: 126",
        move1e : "-Drum Beating",
        move2e : "-Knock Off",
        move3e : "-High Horsepower",
        move4e : "-Endeavor",

        namef : "Charizard",
        levelf : "LV: 65",
        typef : "Type: Fire/Flying",
        abilityf: "Ability: Blaze",
        itemf : "Item: None",
        hpf : "HP: 195 --> 341",
        atkf : "Atk: 119",
        deff : "Def: 125",
        spatkf : "Sp. Atk: 166",
        spdeff : "Sp. Def: 135",
        spdf : "Spd: 169",
        move1f : "-Fire Blast",
        move2f : "-Air Slash",
        move3f : "-Solar Beam",
        move4f : "-Ancient Power",
    },

    {
        namea : "Aegislash",
        levela : "LV: 62",
        typea : "Type: Steel/Ghost",
        abilitya: "Ability: Stance Change",
        itema : "Item: None",
        hpa : "HP: 158",
        atka : "Atk: 79 <--> 191",
        defa : "Def: 191 <--> 79",
        spatka : "Sp. Atk: 86 <--> 210",
        spdefa : "Sp. Def: 191 <--> 79",
        spda : "Spd: 81",
        move1a : "-King's Shield",
        move2a : "-Shadow Ball",
        move3a : "-Sacred Sword",
        move4a : "-Flash Cannon",

        nameb : "Dragapult",
        levelb : "LV: 62",
        typeb : "Type: Dragon/Ghost",
        abilityb: "Ability: Clear Body",
        itemb : "Item: None",
        hpb : "HP: 193",
        atkb : "Atk: 149",
        defb : "Def: 110",
        spatkb : "Sp. Atk: 155",
        spdefb : "Sp. Def: 110",
        spdb : "Spd: 193",
        move1b : "-Shadow Ball",
        move2b : "-Flamethrower",
        move3b : "-Thunderbolt",
        move4b : "-Dragon Breath",

        namec : "Haxorus",
        levelc : "LV: 63",
        typec : "Type: Dragon",
        abilityc: "Ability: Mold Breaker",
        itemc : "Item: None",
        hpc : "HP: 181",
        atkc : "Atk: 202",
        defc : "Def: 131",
        spatkc : "Sp. Atk: 83",
        spdefc : "Sp. Def: 105",
        spdc : "Spd: 152",
        move1c : "-Poison Jab",
        move2c : "-Iron Tail",
        move3c : "-Outrage",
        move4c : "-Earthquake",

        named : "Seismitoad",
        leveld : "LV: 64",
        typed : "Type: Water/Ground",
        abilityd: "Ability: Water Absorb",
        itemd : "Item: None",
        hpd : "HP: 221",
        atkd : "Atk: 152",
        defd : "Def: 113",
        spatkd : "Sp. Atk: 113",
        spdefd : "Sp. Def: 113",
        spdd : "Spd: 112",
        move1d : "-Toxic",
        move2d : "-Drain Punch",
        move3d : "-Liquidation",
        move4d : "-Earthquake",

        namee : "Cinderace",
        levele : "LV: 64",
        typee : "Type: Fire",
        abilitye: "Ability: Blaze",
        iteme : "Item: None",
        hpe : "HP: 189",
        atke : "Atk: 166",
        defe : "Def: 113",
        spatke : "Sp. Atk: 90",
        spdefe : "Sp. Def: 113",
        spde : "Spd: 187",
        move1e : "-Pyro Ball",
        move2e : "-Feint",
        move3e : "-Acrobatics",
        move4e : "-Quick Attack",

        namef : "Charizard",
        levelf : "LV: 65",
        typef : "Type: Fire/Flying",
        abilityf: "Ability: Blaze",
        itemf : "Item: None",
        hpf : "HP: 195 --> 341",
        atkf : "Atk: 119",
        deff : "Def: 125",
        spatkf : "Sp. Atk: 166",
        spdeff : "Sp. Def: 135",
        spdf : "Spd: 169",
        move1f : "-Fire Blast",
        move2f : "-Air Slash",
        move3f : "-Solar Beam",
        move4f : "-Ancient Power",
    },

    {
        namea : "Aegislash",
        levela : "LV: 62",
        typea : "Type: Steel/Ghost",
        abilitya: "Ability: Stance Change",
        itema : "Item: None",
        hpa : "HP: 158",
        atka : "Atk: 79 <--> 191",
        defa : "Def: 191 <--> 79",
        spatka : "Sp. Atk: 86 <--> 210",
        spdefa : "Sp. Def: 191 <--> 79",
        spda : "Spd: 81",
        move1a : "-King's Shield",
        move2a : "-Shadow Ball",
        move3a : "-Sacred Sword",
        move4a : "-Flash Cannon",

        nameb : "Dragapult",
        levelb : "LV: 62",
        typeb : "Type: Dragon/Ghost",
        abilityb: "Ability: Clear Body",
        itemb : "Item: None",
        hpb : "HP: 193",
        atkb : "Atk: 149",
        defb : "Def: 110",
        spatkb : "Sp. Atk: 155",
        spdefb : "Sp. Def: 110",
        spdb : "Spd: 193",
        move1b : "-Shadow Ball",
        move2b : "-Flamethrower",
        move3b : "-Thunderbolt",
        move4b : "-Dragon Breath",

        namec : "Haxorus",
        levelc : "LV: 63",
        typec : "Type: Dragon",
        abilityc: "Ability: Mold Breaker",
        itemc : "Item: None",
        hpc : "HP: 181",
        atkc : "Atk: 202",
        defc : "Def: 131",
        spatkc : "Sp. Atk: 83",
        spdefc : "Sp. Def: 105",
        spdc : "Spd: 152",
        move1c : "-Poison Jab",
        move2c : "-Iron Tail",
        move3c : "-Outrage",
        move4c : "-Earthquake",

        named : "Mr. Rime",
        leveld : "LV: 64",
        typed : "Type: Ice/Psychic",
        abilityd: "Ability: Tangled Feet",
        itemd : "Item: None",
        hpd : "HP: 189",
        atkd : "Atk: 113",
        defd : "Def: 113",
        spatkd : "Sp. Atk: 173",
        spdefd : "Sp. Def: 145",
        spdd : "Spd: 107",
        move1d : "-Teeter Dance",
        move2d : "-Psychic",
        move3d : "-Freeze-Dry",
        move4d : "-Thunderbolt",

        namee : "Inteleon",
        levele : "LV: 64",
        typee : "Type: Water",
        abilitye: "Ability: Torrent",
        iteme : "Item: None",
        hpe : "HP: 176",
        atke : "Atk: 113",
        defe : "Def: 101",
        spatke : "Sp. Atk: 194",
        spdefe : "Sp. Def: 101",
        spde : "Spd: 171",
        move1e : "-Snipe Snot",
        move2e : "-Dark Pulse",
        move3e : "-Mud Shot",
        move4e : "-Tearful Look",

        namef : "Charizard",
        levelf : "LV: 65",
        typef : "Type: Fire/Flying",
        abilityf: "Ability: Blaze",
        itemf : "Item: None",
        hpf : "HP: 195 --> 341",
        atkf : "Atk: 119",
        deff : "Def: 125",
        spatkf : "Sp. Atk: 166",
        spdeff : "Sp. Def: 135",
        spdf : "Spd: 169",
        move1f : "-Fire Blast",
        move2f : "-Air Slash",
        move3f : "-Solar Beam",
        move4f : "-Ancient Power",
    },
]

function displaySWSHTrainers() {

    let newTrainerId = this.id;
    if (newTrainerId !== currentTrainerId) {
        currentTrainerId = newTrainerId;
        showSWSHImages(newTrainerId);
        showPokemonSWSHImages(newTrainerId);
    }


    let swshTrainer = this.dataset.member;

    document.querySelector('#name1').textContent = swsh_trainers [swshTrainer].namea;
    document.querySelector('#level1').textContent = swsh_trainers [swshTrainer].levela;
    document.querySelector('#type1').textContent = swsh_trainers [swshTrainer].typea;
    document.querySelector('#ability1').textContent= swsh_trainers [swshTrainer].abilitya;
    document.querySelector('#item1').textContent = swsh_trainers [swshTrainer].itema;
    document.querySelector('#hp1').textContent = swsh_trainers [swshTrainer].hpa;
    document.querySelector('#atk1').textContent = swsh_trainers [swshTrainer].atka;
    document.querySelector('#def1').textContent = swsh_trainers [swshTrainer].defa;
    document.querySelector('#spatk1').textContent = swsh_trainers [swshTrainer].spatka;
    document.querySelector('#spdef1').textContent = swsh_trainers [swshTrainer].spdefa;
    document.querySelector('#spd1').textContent = swsh_trainers [swshTrainer].spda;
    document.querySelector('#move1_1').textContent = swsh_trainers [swshTrainer].move1a;
    document.querySelector('#move2_1').textContent = swsh_trainers [swshTrainer].move2a;
    document.querySelector('#move3_1').textContent = swsh_trainers [swshTrainer].move3a;
    document.querySelector('#move4_1').textContent = swsh_trainers [swshTrainer].move4a;

    
    document.querySelector('#name2').textContent = swsh_trainers [swshTrainer].nameb;
    document.querySelector('#level2').textContent = swsh_trainers [swshTrainer].levelb;
    document.querySelector('#type2').textContent = swsh_trainers [swshTrainer].typeb;
    document.querySelector('#ability2').textContent= swsh_trainers [swshTrainer].abilityb;
    document.querySelector('#item2').textContent = swsh_trainers [swshTrainer].itemb;
    document.querySelector('#hp2').textContent = swsh_trainers [swshTrainer].hpb;
    document.querySelector('#atk2').textContent = swsh_trainers [swshTrainer].atkb;
    document.querySelector('#def2').textContent = swsh_trainers [swshTrainer].defb;
    document.querySelector('#spatk2').textContent = swsh_trainers [swshTrainer].spatkb;
    document.querySelector('#spdef2').textContent = swsh_trainers [swshTrainer].spdefb;
    document.querySelector('#spd2').textContent = swsh_trainers [swshTrainer].spdb;
    document.querySelector('#move1_2').textContent = swsh_trainers [swshTrainer].move1b;
    document.querySelector('#move2_2').textContent = swsh_trainers [swshTrainer].move2b;
    document.querySelector('#move3_2').textContent = swsh_trainers [swshTrainer].move3b;
    document.querySelector('#move4_2').textContent = swsh_trainers [swshTrainer].move4b;

    document.querySelector('#name3').textContent = swsh_trainers [swshTrainer].namec;
    document.querySelector('#level3').textContent = swsh_trainers [swshTrainer].levelc;
    document.querySelector('#type3').textContent = swsh_trainers [swshTrainer].typec;
    document.querySelector('#ability3').textContent= swsh_trainers [swshTrainer].abilityc;
    document.querySelector('#item3').textContent = swsh_trainers [swshTrainer].itemc;
    document.querySelector('#hp3').textContent = swsh_trainers [swshTrainer].hpc;
    document.querySelector('#atk3').textContent = swsh_trainers [swshTrainer].atkc;
    document.querySelector('#def3').textContent = swsh_trainers [swshTrainer].defc;
    document.querySelector('#spatk3').textContent = swsh_trainers [swshTrainer].spatkc;
    document.querySelector('#spdef3').textContent = swsh_trainers [swshTrainer].spdefc;
    document.querySelector('#spd3').textContent = swsh_trainers [swshTrainer].spdc;
    document.querySelector('#move1_3').textContent = swsh_trainers [swshTrainer].move1c;
    document.querySelector('#move2_3').textContent = swsh_trainers [swshTrainer].move2c;
    document.querySelector('#move3_3').textContent = swsh_trainers [swshTrainer].move3c;
    document.querySelector('#move4_3').textContent = swsh_trainers [swshTrainer].move4c;

    document.querySelector('#name4').textContent = swsh_trainers [swshTrainer].named;
    document.querySelector('#level4').textContent = swsh_trainers [swshTrainer].leveld;
    document.querySelector('#type4').textContent = swsh_trainers [swshTrainer].typed;
    document.querySelector('#ability4').textContent= swsh_trainers [swshTrainer].abilityd;
    document.querySelector('#item4').textContent = swsh_trainers [swshTrainer].itemd;
    document.querySelector('#hp4').textContent = swsh_trainers [swshTrainer].hpd;
    document.querySelector('#atk4').textContent = swsh_trainers [swshTrainer].atkd;
    document.querySelector('#def4').textContent = swsh_trainers [swshTrainer].defd;
    document.querySelector('#spatk4').textContent = swsh_trainers [swshTrainer].spatkd;
    document.querySelector('#spdef4').textContent = swsh_trainers [swshTrainer].spdefd;
    document.querySelector('#spd4').textContent = swsh_trainers [swshTrainer].spdd;
    document.querySelector('#move1_4').textContent = swsh_trainers [swshTrainer].move1d;
    document.querySelector('#move2_4').textContent = swsh_trainers [swshTrainer].move2d;
    document.querySelector('#move3_4').textContent = swsh_trainers [swshTrainer].move3d;
    document.querySelector('#move4_4').textContent = swsh_trainers [swshTrainer].move4d;

    document.querySelector('#name5').textContent = swsh_trainers [swshTrainer].namee;
    document.querySelector('#level5').textContent = swsh_trainers [swshTrainer].levele;
    document.querySelector('#type5').textContent = swsh_trainers [swshTrainer].typee;
    document.querySelector('#ability5').textContent= swsh_trainers [swshTrainer].abilitye;
    document.querySelector('#item5').textContent = swsh_trainers [swshTrainer].iteme;
    document.querySelector('#hp5').textContent = swsh_trainers [swshTrainer].hpe;
    document.querySelector('#atk5').textContent = swsh_trainers [swshTrainer].atke;
    document.querySelector('#def5').textContent = swsh_trainers [swshTrainer].defe;
    document.querySelector('#spatk5').textContent = swsh_trainers [swshTrainer].spatke;
    document.querySelector('#spdef5').textContent = swsh_trainers [swshTrainer].spdefe;
    document.querySelector('#spd5').textContent = swsh_trainers [swshTrainer].spde;
    document.querySelector('#move1_5').textContent = swsh_trainers [swshTrainer].move1e;
    document.querySelector('#move2_5').textContent = swsh_trainers [swshTrainer].move2e;
    document.querySelector('#move3_5').textContent = swsh_trainers [swshTrainer].move3e;
    document.querySelector('#move4_5').textContent = swsh_trainers [swshTrainer].move4e;

    document.querySelector('#name6').textContent = swsh_trainers [swshTrainer].namef;
    document.querySelector('#level6').textContent = swsh_trainers [swshTrainer].levelf;
    document.querySelector('#type6').textContent = swsh_trainers [swshTrainer].typef;
    document.querySelector('#ability6').textContent= swsh_trainers [swshTrainer].abilityf;
    document.querySelector('#item6').textContent = swsh_trainers [swshTrainer].itemf;
    document.querySelector('#hp6').textContent = swsh_trainers [swshTrainer].hpf;
    document.querySelector('#atk6').textContent = swsh_trainers [swshTrainer].atkf;
    document.querySelector('#def6').textContent = swsh_trainers [swshTrainer].deff;
    document.querySelector('#spatk6').textContent = swsh_trainers [swshTrainer].spatkf;
    document.querySelector('#spdef6').textContent = swsh_trainers [swshTrainer].spdeff;
    document.querySelector('#spd6').textContent = swsh_trainers [swshTrainer].spdf;
    document.querySelector('#move1_6').textContent = swsh_trainers [swshTrainer].move1f;
    document.querySelector('#move2_6').textContent = swsh_trainers [swshTrainer].move2f;
    document.querySelector('#move3_6').textContent = swsh_trainers [swshTrainer].move3f;
    document.querySelector('#move4_6').textContent = swsh_trainers [swshTrainer].move4f;
}

function showSWSHImages(trainerId) {
    var trainerPicture = document.querySelector("#trainer_image");
    
    trainerPicture.innerHTML = "";

    var imgTrainer = document.createElement("img");
    imgTrainer.src = "images/trainers/swsh/" + trainerId + ".png";
    trainerPicture.appendChild(imgTrainer);
}

function showPokemonSWSHImages(trainerId) {
    var pokemon1Picture = document.querySelector("#pokemon_1_image");
    var pokemon2Picture = document.querySelector("#pokemon_2_image");
    var pokemon3Picture = document.querySelector("#pokemon_3_image");
    var pokemon4Picture = document.querySelector("#pokemon_4_image");
    var pokemon5Picture = document.querySelector("#pokemon_5_image");
    var pokemon6Picture = document.querySelector("#pokemon_6_image");
    var imgPokemon1 = document.createElement("img");
    var imgPokemon2 = document.createElement("img");
    var imgPokemon3 = document.createElement("img");
    var imgPokemon4 = document.createElement("img");
    var imgPokemon5 = document.createElement("img");
    var imgPokemon6 = document.createElement("img");
    
    pokemon1Picture.innerHTML = "";
    pokemon2Picture.innerHTML = "";
    pokemon3Picture.innerHTML = "";
    pokemon4Picture.innerHTML = "";
    pokemon5Picture.innerHTML = "";
    pokemon6Picture.innerHTML = "";

    
    imgPokemon1.src = "images/pokemon/swsh/" + trainerId + "_1.png";
    imgPokemon2.src = "images/pokemon/swsh/" + trainerId + "_2.png";
    imgPokemon3.src = "images/pokemon/swsh/" + trainerId + "_3.png";
    imgPokemon4.src = "images/pokemon/swsh/" + trainerId + "_4.png";
    imgPokemon5.src = "images/pokemon/swsh/" + trainerId + "_5.png";
    imgPokemon6.src = "images/pokemon/swsh/" + trainerId + "_6.png";

    pokemon1Picture.appendChild(imgPokemon1);
    pokemon2Picture.appendChild(imgPokemon2);
    pokemon3Picture.appendChild(imgPokemon3);
    pokemon4Picture.appendChild(imgPokemon4);
    pokemon5Picture.appendChild(imgPokemon5);
    pokemon6Picture.appendChild(imgPokemon6);
}

miloSWSH.addEventListener('click', displaySWSHTrainers);
nessaSWSH.addEventListener('click', displaySWSHTrainers);
kabuSWSH.addEventListener('click', displaySWSHTrainers);
beaSWSH.addEventListener('click', displaySWSHTrainers);
allisterSWSH.addEventListener('click', displaySWSHTrainers);
opalSWSH.addEventListener('click', displaySWSHTrainers);
gordieSWSH.addEventListener('click', displaySWSHTrainers);
melonySWSH.addEventListener('click', displaySWSHTrainers);
piersSWSH.addEventListener('click', displaySWSHTrainers);
raihanSWSH.addEventListener('click', displaySWSHTrainers);
marnieSWSH.addEventListener('click', displaySWSHTrainers);
hopGSWSH.addEventListener('click', displaySWSHTrainers);
hopFSWSH.addEventListener('click', displaySWSHTrainers);
hopWSWSH.addEventListener('click', displaySWSHTrainers);
bedeSWSH.addEventListener('click', displaySWSHTrainers);
nessaCSWSH.addEventListener('click', displaySWSHTrainers);
beaCSWSH.addEventListener('click', displaySWSHTrainers);
allisterCSWSH.addEventListener('click', displaySWSHTrainers);
raihanCSWSH.addEventListener('click', displaySWSHTrainers);
oleanaSWSH.addEventListener('click', displaySWSHTrainers);
roseSWSH.addEventListener('click', displaySWSHTrainers);
leonGSWSH.addEventListener('click', displaySWSHTrainers);
leonFSWSH.addEventListener('click', displaySWSHTrainers);
leonWSWSH.addEventListener('click', displaySWSHTrainers);