let halaUSUM = document.querySelector ("#hala3");
let oliviaUSUM = document.querySelector ("#olivia3");
let guzmaSHUSUM = document.querySelector ("#guzma3");
let nanuUSUM = document.querySelector ("#nanu2");
let guzmaAHUSUM = document.querySelector ("#guzma4");
let lusamineUSUM = document.querySelector ("#lusamine2");
let hapuUSUM = document.querySelector ("#hapu2");
let gladionGUSUM = document.querySelector ("#gladion2_g");
let gladionFUSUM = document.querySelector ("#gladion2_f");
let gladionWUSUM = document.querySelector ("#gladion2_w");
let molayneUSUM = document.querySelector ("#molayne1");
let oliviaE4USUM = document.querySelector ("#olivia4");
let acerolaUSUM = document.querySelector ("#acerola2");
let kahiliUSUM = document.querySelector ("#kahili2");
let hauGUSUM = document.querySelector ("#hau1_g");
let hauFUSUM = document.querySelector ("#hau1_f");
let hauWUSUM = document.querySelector ("#hau1_w");
let maxieUSUM = document.querySelector ("#maxie2");
let archieUSUM = document.querySelector ("#archie2");
let cyrusDUSUM = document.querySelector ("#cyrus3_us");
let cyrusPUSUM = document.querySelector ("#cyrus3_um");
let lysandreXUSUM = document.querySelector ("#lysandre2_us");
let lysandreYUSUM = document.querySelector ("#lysandre2_um");
let ghetsisZUSUM = document.querySelector ("#ghetsis3_us");
let ghetsisRUSUM = document.querySelector ("#ghetsis3_um");
let giovanniXUSUM = document.querySelector ("#giovanni4_us");
let giovanniYUSUM = document.querySelector ("#giovanni4_um");

let usum_trainers = [
    {
        namea : "Machop",
        levela : "LV: 15",
        typea : "Type: Fighting",
        abilitya: "Ability: Guts",
        itema : "Item: None",
        hpa : "HP: 59",
        atka : "Atk: 36",
        defa : "Def: 24",
        spatka : "Sp. Atk: 18",
        spdefa : "Sp. Def: 20",
        spda : "Spd: 29",
        move1a : "-Karate Chop",
        move2a : "-Focus Energy",
        move3a : "-Revenge",
        move4a : "",

        nameb : "Makuhita",
        levelb : "LV: 14",
        typeb : "Type: Fighting",
        abilityb: "Ability: Thick Fat",
        itemb : "Item: None",
        hpb : "HP: 60",
        atkb : "Atk: 29",
        defb : "Def: 18",
        spatkb : "Sp. Atk: 13",
        spdefb : "Sp. Def: 27",
        spdb : "Spd: 17",
        move1b : "-Fake Out",
        move2b : "-Sand Attack",
        move3b : "-Arm Thrust",
        move4b : "",

        namec : "Crabrawler",
        levelc : "LV: 15",
        typec : "Type: Fighting",
        abilityc: "Ability: Iron Fist",
        itemc : "Item: Fightinium Z",
        hpc : "HP: 55",
        atkc : "Atk: 39",
        defc : "Def: 38",
        spatkc : "Sp. Atk: 20",
        spdefc : "Sp. Def: 24",
        spdc : "Spd: 29",
        move1c : "-Power-Up Punch",
        move2c : "-Pursuit",
        move3c : "-Leer",
        move4c : "",   
    },

    {
        namea : "Anorith",
        levela : "LV: 27",
        typea : "Type: Rock/Bug",
        abilitya: "Ability: Battle Armor",
        itema : "Item: None",
        hpa : "HP: 69",
        atka : "Atk: 81",
        defa : "Def: 40",
        spatka : "Sp. Atk: 30",
        spdefa : "Sp. Def: 44",
        spda : "Spd: 70",
        move1a : "-Bug Bite",
        move2a : "-Smack Down",
        move3a : "-Metal Claw",
        move4a : "",

        nameb : "Lileep",
        levelb : "LV: 27",
        typeb : "Type: Rock/Grass",
        abilityb: "Ability: Suction Cups",
        itemb : "Item: None",
        hpb : "HP: 80",
        atkb : "Atk: 35",
        defb : "Def: 78",
        spatkb : "Sp. Atk: 41",
        spdefb : "Sp. Def: 77",
        spdb : "Spd: 25",
        move1b : "-Giga Drain",
        move2b : "-Ancient Power",
        move3b : "-Brine",
        move4b : "",

        namec : "Lycanroc (Midnight)",
        levelc : "LV: 28",
        typec : "Type: Rock",
        abilityc: "Ability: Vital Spirit",
        itemc : "Item: Rockium Z",
        hpc : "HP: 94",
        atkc : "Atk: 104",
        defc : "Def: 55",
        spatkc : "Sp. Atk: 39",
        spdefc : "Sp. Def: 55",
        spdc : "Spd: 76",
        move1c : "-Bite",
        move2c : "-Rock Tomb",
        move3c : "",
        move4c : "",
    },

    {
        namea : "Golisopod",
        levela : "LV: 41",
        typea : "Type: Bug/Water",
        abilitya: "Ability: Emergency Exit",
        itema : "Item: None",
        hpa : "HP: 124",
        atka : "Atk: 159",
        defa : "Def: 157",
        spatka : "Sp. Atk: 59",
        spdefa : "Sp. Def: 91",
        spda : "Spd: 50",
        move1a : "-Sucker Punch",
        move2a : "-First Impression",
        move3a : "-Razor Shell",
        move4a : "",

        nameb : "Masquerain",
        levelb : "LV: 41",
        typeb : "Type: Bug/Flying",
        abilityb: "Ability: Intimidate",
        itemb : "Item: None",
        hpb : "HP: 120",
        atkb : "Atk: 59",
        defb : "Def: 68",
        spatkb : "Sp. Atk: 137",
        spdefb : "Sp. Def: 84",
        spdb : "Spd: 108",
        move1b : "-Air Slash",
        move2b : "-Bug Buzz",
        move3b : "-Icy Wind",
        move4b : "",

        namec : "Pinsir",
        levelc : "LV: 41",
        typec : "Type: Bug",
        abilityc: "Ability: Mold Breaker",
        itemc : "Item: None",
        hpc : "HP: 116",
        atkc : "Atk: 119",
        defc : "Def: 137",
        spatkc : "Sp. Atk: 55",
        spdefc : "Sp. Def: 100",
        spdc : "Spd: 87",
        move1c : "-Throat Chop",
        move2c : "-Storm Throw",
        move3c : "-X-Scissor",
        move4c : "",
    },

    {
        namea : "Sableye",
        levela : "LV: 43",
        typea : "Type: Dark/Ghost",
        abilitya: "Ability: Keen Eye",
        itema : "Item: None",
        hpa : "HP: 108",
        atka : "Atk: 82",
        defa : "Def: 90",
        spatka : "Sp. Atk: 90",
        spdefa : "Sp. Def: 100",
        spda : "Spd: 60",
        move1a : "-Power Gem",
        move2a : "-Shadow Ball",
        move3a : "-Fake Out",
        move4a : "",

        nameb : "Krokorok",
        levelb : "LV: 43",
        typeb : "Type: Ground/Dark",
        abilityb: "Ability: Intimidate",
        itemb : "Item: None",
        hpb : "HP: 117",
        atkb : "Atk: 115",
        defb : "Def: 56",
        spatkb : "Sp. Atk: 50",
        spdefb : "Sp. Def: 56",
        spdb : "Spd: 118",
        move1b : "-Crunch",
        move2b : "-Assurance",
        move3b : "-Swagger",
        move4b : "-Earthquake",

        namec : "Persian (Alolan)",
        levelc : "LV: 44",
        typec : "Type: Dark",
        abilityc: "Ability: Fur Coat",
        itemc : "Item: Darkinium Z",
        hpc : "HP: 124",
        atkc : "Atk: 63",
        defc : "Def: 71",
        spatkc : "Sp. Atk: 111",
        spdefc : "Sp. Def: 75",
        spdc : "Spd: 161",
        move1c : "-Power Gem",
        move2c : "-Fake Out",
        move3c : "-Dark Pulse",
        move4c : "",
    },

    {
        namea : "Golisopod",
        levela : "LV: 45",
        typea : "Type: Bug/Water",
        abilitya: "Ability: Emergency Exit",
        itema : "Item: None",
        hpa : "HP: 136",
        atka : "Atk: 174",
        defa : "Def: 172",
        spatka : "Sp. Atk: 64",
        spdefa : "Sp. Def: 99",
        spda : "Spd: 54",
        move1a : "-Sucker Punch",
        move2a : "-First Impression",
        move3a : "-Razor Shell",
        move4a : "",

        nameb : "Masquerain",
        levelb : "LV: 45",
        typeb : "Type: Bug/Flying",
        abilityb: "Ability: Intimidate",
        itemb : "Item: None",
        hpb : "HP: 131",
        atkb : "Atk: 64",
        defb : "Def: 74",
        spatkb : "Sp. Atk: 149",
        spdefb : "Sp. Def: 92",
        spdb : "Spd: 118",
        move1b : "-Air Slash",
        move2b : "-Bug Buzz",
        move3b : "-Icy Wind",
        move4b : "",

        namec : "Pinsir",
        levelc : "LV: 45",
        typec : "Type: Bug",
        abilityc: "Ability: Mold Breaker",
        itemc : "Item: None",
        hpc : "HP: 127",
        atkc : "Atk: 143",
        defc : "Def: 108",
        spatkc : "Sp. Atk: 74",
        spdefc : "Sp. Def: 81",
        spdc : "Spd: 123",
        move1c : "-Throat Chop",
        move2c : "-Storm Throw",
        move3c : "-X-Scissor",
        move4c : "-Stone Edge",

        named : "Vikavolt",
        leveld : "LV: 45",
        typed : "Type: Bug/Electric",
        abilityd: "Ability: Levitate",
        itemd : "Item: None",
        hpd : "HP: 166",
        atkd : "Atk: 89",
        defd : "Def: 99",
        spatkd : "Sp. Atk: 159",
        spdefd : "Sp. Def: 86",
        spdd : "Spd: 57",
        move1d : "-Flash Cannon",
        move2d : "-Thunderbolt",
        move3d : "-Bug Buzz",
        move4d : "-Energy Ball",
    },

    {
        namea : "Clefable",
        levela : "LV: 47",
        typea : "Type: Fairy",
        abilitya: "Ability: Magic Guard",
        itema : "Item: None",
        hpa : "HP: 160",
        atka : "Atk: 75",
        defa : "Def: 87",
        spatka : "Sp. Atk: 138",
        spdefa : "Sp. Def: 146",
        spda : "Spd: 75",
        move1a : "-Moonblast",
        move2a : "-Charm",
        move3a : "-Psychic",
        move4a : "-Hyper Voice",

        nameb : "Lilligant",
        levelb : "LV: 47",
        typeb : "Type: Grass",
        abilityb: "Ability: Own Tempo",
        itemb : "Item: None",
        hpb : "HP: 136",
        atkb : "Atk: 67",
        defb : "Def: 89",
        spatkb : "Sp. Atk: 167",
        spdefb : "Sp. Def: 89",
        spdb : "Spd: 133",
        move1b : "-Petal Dance",
        move2b : "-Teeter Dance",
        move3b : "-Stun Spore",
        move4b : "",

        namec : "Lopunny",
        levelc : "LV: 47",
        typec : "Type: Normal",
        abilityc: "Ability: Cute Charm",
        itemc : "Item: None",
        hpc : "HP: 132",
        atkc : "Atk: 132",
        defc : "Def: 98",
        spatkc : "Sp. Atk: 62",
        spdefc : "Sp. Def: 109",
        spdc : "Spd: 147",
        move1c : "-Dizzy Punch",
        move2c : "-Thunder Punch",
        move3c : "-Ice Punch",
        move4c : "-Fire Punch",

        named : "Milotic",
        leveld : "LV: 47",
        typed : "Type: Water",
        abilityd: "Ability: Marvel Scale",
        itemd : "Item: None",
        hpd : "HP: 160",
        atkd : "Atk: 67",
        defd : "Def: 93",
        spatkd : "Sp. Atk: 156",
        spdefd : "Sp. Def: 136",
        spdd : "Spd: 124",
        move1d : "-Hydro Pump",
        move2d : "-Icy Wind",
        move3d : "-Flail",
        move4d : "-Dragon Pulse",

        namee : "Bewear",
        levele : "LV: 47",
        typee : "Type: Normal/Fighting",
        abilitye: "Ability: Fluffy",
        iteme : "Item: None",
        hpe : "HP: 213",
        atke : "Atk: 182",
        defe : "Def: 94",
        spatke : "Sp. Atk: 63",
        spdefe : "Sp. Def: 75",
        spde : "Spd: 75",
        move1e : "-Take Down",
        move2e : "-Drain Punch",
        move3e : "-Zen Headbutt",
        move4e : "-Dual Chop",
    },

    {
        namea : "Golurk",
        levela : "LV: 53",
        typea : "Type: Ground/Ghost",
        abilitya: "Ability: No Guard",
        itema : "Item: None",
        hpa : "HP: 206",
        atka : "Atk: 185",
        defa : "Def: 105",
        spatka : "Sp. Atk: 79",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 79",
        move1a : "-Hammer Arm",
        move2a : "-Earthquake",
        move3a : "-Shadow Punch",
        move4a : "-Stealth Rock",

        nameb : "Gastrodon",
        levelb : "LV: 53",
        typeb : "Type: Water/Ground",
        abilityb: "Ability: Sticky Hold",
        itemb : "Item: None",
        hpb : "HP: 229",
        atkb : "Atk: 108",
        defb : "Def: 92",
        spatkb : "Sp. Atk: 151",
        spdefb : "Sp. Def: 107",
        spdb : "Spd: 62",
        move1b : "-Muddy Water",
        move2b : "-Mud Bomb",
        move3b : "-Recover",
        move4b : "",

        namec : "Flygon",
        levelc : "LV: 53",
        typec : "Type: Ground/Dragon",
        abilityc: "Ability: Levitate",
        itemc : "Item: None",
        hpc : "HP: 163",
        atkc : "Atk: 126",
        defc : "Def: 105",
        spatkc : "Sp. Atk: 139",
        spdefc : "Sp. Def: 105",
        spdc : "Spd: 160",
        move1c : "-Earth Power",
        move2c : "-Dragon Breath",
        move3c : "",
        move4c : "",

        named : "Mudsdale",
        leveld : "LV: 54",
        typed : "Type: Ground",
        abilityd: "Ability: Stamina",
        itemd : "Item: Groundium Z",
        hpd : "HP: 188",
        atkd : "Atk: 190",
        defd : "Def: 163",
        spatkd : "Sp. Atk: 80",
        spdefd : "Sp. Def: 113",
        spdd : "Spd: 59",
        move1d : "-Heavy Slam",
        move2d : "-Earthquake",
        move3d : "-Double Kick",
        move4d : "-Payback",
    },

    {
        namea : "Crobat",
        levela : "LV: 53",
        typea : "Type: Poison/Flying",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 169",
        atka : "Atk: 141",
        defa : "Def: 105",
        spatka : "Sp. Atk: 95",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 192",
        move1a : "-Acrobatics",
        move2a : "-Cross Poison",
        move3a : "",
        move4a : "",

        nameb : "Zoroark",
        levelb : "LV: 53",
        typeb : "Type: Dark",
        abilityb: "Ability: Illusion",
        itemb : "Item: Darkinium Z",
        hpb : "HP: 142",
        atkb : "Atk: 132",
        defb : "Def: 84",
        spatkb : "Sp. Atk: 181",
        spdefb : "Sp. Def: 84",
        spdb : "Spd: 165",
        move1b : "-Night Daze",
        move2b : "-Hyper Voice",
        move3b : "-Grass Knot",
        move4b : "",

        namec : "Silvally",
        levelc : "LV: 55",
        typec : "Type: Grass",
        abilityc: "Ability: RKS System",
        itemc : "Item: Grass Memory",
        hpc : "HP: 186",
        atkc : "Atk: 160",
        defc : "Def: 126",
        spatkc : "Sp. Atk: 126",
        spdefc : "Sp. Def: 126",
        spdc : "Spd: 160",
        move1c : "-Multi Attack",
        move2c : "-Crunch",
        move3c : "-Crush Claw",
        move4c : "-X-Scissor",

        named : "Lucario",
        leveld : "LV: 53",
        typed : "Type: Fighting/Steel",
        abilityd: "Ability: Inner Focus",
        itemd : "Item: None",
        hpd : "HP: 153",
        atkd : "Atk: 170",
        defd : "Def: 95",
        spatkd : "Sp. Atk: 142",
        spdefd : "Sp. Def: 95",
        spdd : "Spd: 149",
        move1d : "-Aura Sphere",
        move2d : "-Metal Claw",
        move3d : "-Quick Attack",
        move4d : "",
    },

    {
        namea : "Crobat",
        levela : "LV: 53",
        typea : "Type: Poison/Flying",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 169",
        atka : "Atk: 141",
        defa : "Def: 105",
        spatka : "Sp. Atk: 95",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 192",
        move1a : "-Acrobatics",
        move2a : "-Cross Poison",
        move3a : "",
        move4a : "",

        nameb : "Zoroark",
        levelb : "LV: 53",
        typeb : "Type: Dark",
        abilityb: "Ability: Illusion",
        itemb : "Item: Darkinium Z",
        hpb : "HP: 142",
        atkb : "Atk: 132",
        defb : "Def: 84",
        spatkb : "Sp. Atk: 181",
        spdefb : "Sp. Def: 84",
        spdb : "Spd: 165",
        move1b : "-Night Daze",
        move2b : "-Hyper Voice",
        move3b : "-Grass Knot",
        move4b : "",

        namec : "Silvally",
        levelc : "LV: 55",
        typec : "Type: Fire",
        abilityc: "Ability: RKS System",
        itemc : "Item: Fire Memory",
        hpc : "HP: 186",
        atkc : "Atk: 160",
        defc : "Def: 126",
        spatkc : "Sp. Atk: 126",
        spdefc : "Sp. Def: 126",
        spdc : "Spd: 160",
        move1c : "-Multi Attack",
        move2c : "-Crunch",
        move3c : "-Crush Claw",
        move4c : "-X-Scissor",

        named : "Lucario",
        leveld : "LV: 53",
        typed : "Type: Fighting/Steel",
        abilityd: "Ability: Inner Focus",
        itemd : "Item: None",
        hpd : "HP: 153",
        atkd : "Atk: 170",
        defd : "Def: 95",
        spatkd : "Sp. Atk: 142",
        spdefd : "Sp. Def: 95",
        spdd : "Spd: 149",
        move1d : "-Aura Sphere",
        move2d : "-Metal Claw",
        move3d : "-Quick Attack",
        move4d : "",
    },

    {
        namea : "Crobat",
        levela : "LV: 53",
        typea : "Type: Poison/Flying",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 169",
        atka : "Atk: 141",
        defa : "Def: 105",
        spatka : "Sp. Atk: 95",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 192",
        move1a : "-Acrobatics",
        move2a : "-Cross Poison",
        move3a : "",
        move4a : "",

        nameb : "Zoroark",
        levelb : "LV: 53",
        typeb : "Type: Dark",
        abilityb: "Ability: Illusion",
        itemb : "Item: Darkinium Z",
        hpb : "HP: 142",
        atkb : "Atk: 132",
        defb : "Def: 84",
        spatkb : "Sp. Atk: 181",
        spdefb : "Sp. Def: 84",
        spdb : "Spd: 165",
        move1b : "-Night Daze",
        move2b : "-Hyper Voice",
        move3b : "-Grass Knot",
        move4b : "",

        namec : "Silvally",
        levelc : "LV: 55",
        typec : "Type: Water",
        abilityc: "Ability: RKS System",
        itemc : "Item: Water Memory",
        hpc : "HP: 186",
        atkc : "Atk: 160",
        defc : "Def: 126",
        spatkc : "Sp. Atk: 126",
        spdefc : "Sp. Def: 126",
        spdc : "Spd: 160",
        move1c : "-Multi Attack",
        move2c : "-Crunch",
        move3c : "-Crush Claw",
        move4c : "-X-Scissor",

        named : "Lucario",
        leveld : "LV: 53",
        typed : "Type: Fighting/Steel",
        abilityd: "Ability: Inner Focus",
        itemd : "Item: None",
        hpd : "HP: 153",
        atkd : "Atk: 170",
        defd : "Def: 95",
        spatkd : "Sp. Atk: 142",
        spdefd : "Sp. Def: 95",
        spdd : "Spd: 149",
        move1d : "-Aura Sphere",
        move2d : "-Metal Claw",
        move3d : "-Quick Attack",
        move4d : "",
    },

    {
        namea : "Klefki",
        levela : "LV: 56",
        typea : "Type: Steel/Fairy",
        abilitya: "Ability: Prankster",
        itema : "Item: None",
        hpa : "HP: 146",
        atka : "Atk: 108",
        defa : "Def: 159",
        spatka : "Sp. Atk: 108",
        spdefa : "Sp. Def: 154",
        spda : "Spd: 103",
        move1a : "-Spikes",
        move2a : "-Thunder Wave",
        move3a : "-Flash Cannon",
        move4a : "-Reflect",

        nameb : "Bisharp",
        levelb : "LV: 56",
        typeb : "Type: Dark/Steel",
        abilityb: "Ability: Defiant",
        itemb : "Item: None",
        hpb : "HP: 152",
        atkb : "Atk: 197",
        defb : "Def: 169",
        spatkb : "Sp. Atk: 86",
        spdefb : "Sp. Def: 97",
        spdb : "Spd: 100",
        move1b : "-Night Slash",
        move2b : "-Iron Head",
        move3b : "-X-Scissor",
        move4b : "-Metal Sound",

        namec : "Magnezone",
        levelc : "LV: 56",
        typec : "Type: Electric/Steel",
        abilityc: "Ability: Sturdy",
        itemc : "Item: None",
        hpc : "HP: 161",
        atkc : "Atk: 97",
        defc : "Def: 185",
        spatkc : "Sp. Atk: 202",
        spdefc : "Sp. Def: 119",
        spdc : "Spd: 86",
        move1c : "-Flash Cannon",
        move2c : "-Thunderbolt",
        move3c : "-Tri Attack",
        move4c : "-Screech",

        named : "Metagross",
        leveld : "LV: 56",
        typed : "Type: Steel/Psychic",
        abilityd: "Ability: Clear Body",
        itemd : "Item: None",
        hpd : "HP: 172",
        atkd : "Atk: 170",
        defd : "Def: 202",
        spatkd : "Sp. Atk: 125",
        spdefd : "Sp. Def: 157",
        spdd : "Spd: 97",
        move1d : "-Hammer Arm",
        move2d : "-Meteor Mash",
        move3d : "-Bullet Punch",
        move4d : "-Zen Headbutt",

        namee : "Dugtrio (Alolan)",
        levele : "LV: 57",
        typee : "Type: Ground/Steel",
        abilitye: "Ability: Tangling Hair",
        iteme : "Item: Steelium Z",
        hpe : "HP: 124",
        atke : "Atk: 172",
        defe : "Def: 90",
        spatke : "Sp. Atk: 79",
        spdefe : "Sp. Def: 101",
        spde : "Spd: 183",
        move1e : "-Earthquake",
        move2e : "-Iron Head",
        move3e : "-Sucker Punch",
        move4e : "-Fissure",
    },

    {
        namea : "Armaldo",
        levela : "LV: 56",
        typea : "Type: Rock/Bug",
        abilitya: "Ability: Battle Armor",
        itema : "Item: None",
        hpa : "HP: 166",
        atka : "Atk: 197",
        defa : "Def: 133",
        spatka : "Sp. Atk: 100",
        spdefa : "Sp. Def: 111",
        spda : "Spd: 107",
        move1a : "-Crush Claw",
        move2a : "-X-Scissor",
        move3a : "-Rock Blast",
        move4a : "",

        nameb : "Cradily",
        levelb : "LV: 56",
        typeb : "Type: Rock/Grass",
        abilityb: "Ability: Suction Cups",
        itemb : "Item: None",
        hpb : "HP: 179",
        atkb : "Atk: 112",
        defb : "Def: 165",
        spatkb : "Sp. Atk: 112",
        spdefb : "Sp. Def: 176",
        spdb : "Spd: 69",
        move1b : "-Rock Tomb",
        move2b : "-Energy Ball",
        move3b : "-Stealth Rock",
        move4b : "",

        namec : "Gigalith",
        levelc : "LV: 56",
        typec : "Type: Rock",
        abilityc: "Ability: Sand Stream",
        itemc : "Item: None",
        hpc : "HP: 213",
        atkc : "Atk: 173",
        defc : "Def: 202",
        spatkc : "Sp. Atk: 89",
        spdefc : "Sp. Def: 111",
        spdc : "Spd: 49",
        move1c : "-Stone Edge",
        move2c : "-Bulldoze",
        move3c : "-Iron Head",
        move4c : "",

        named : "Probopass",
        leveld : "LV: 56",
        typed : "Type: Rock/Steel",
        abilityd: "Ability: Sturdy",
        itemd : "Item: None",
        hpd : "HP: 185",
        atkd : "Atk: 83",
        defd : "Def: 184",
        spatkd : "Sp. Atk: 105",
        spdefd : "Sp. Def: 225",
        spdd : "Spd: 66",
        move1d : "-Earth Power",
        move2d : "-Power Gem",
        move3d : "-Thunder Wave",
        move4d : "-Sandstorm",

        namee : "Lycanroc (Midnight)",
        levele : "LV: 57",
        typee : "Type: Rock",
        abilitye: "Ability: Keen Eye",
        iteme : "Item: Rockium Z",
        hpe : "HP: 216",
        atke : "Atk: 153",
        defe : "Def: 143",
        spatke : "Sp. Atk: 84",
        spdefe : "Sp. Def: 107",
        spde : "Spd: 115",
        move1e : "-Crunch",
        move2e : "-Stone Edge",
        move3e : "-Counter",
        move4e : "-Rock Climb",
    },

    {
        namea : "Banette",
        levela : "LV: 56",
        typea : "Type: Ghost",
        abilitya: "Ability: Insomnia",
        itema : "Item: None",
        hpa : "HP: 154",
        atka : "Atk: 185",
        defa : "Def: 91",
        spatka : "Sp. Atk: 111",
        spdefa : "Sp. Def: 89",
        spda : "Spd: 129",
        move1a : "-Shadow Claw",
        move2a : "-Feint Attack",
        move3a : "-Infestation",
        move4a : "-Screech",

        nameb : "Drifblim",
        levelb : "LV: 56",
        typeb : "Type: Ghost/Flying",
        abilityb: "Ability: Aftermath",
        itemb : "Item: None",
        hpb : "HP: 250",
        atkb : "Atk: 108",
        defb : "Def: 106",
        spatkb : "Sp. Atk: 119",
        spdefb : "Sp. Def: 117",
        spdb : "Spd: 108",
        move1b : "-Ominous Wind",
        move2b : "-Focus Energy",
        move3b : "-Amnesia",
        move4b : "-Baton Pass",

        namec : "Dhelmise",
        levelc : "LV: 56",
        typec : "Type: Ghost/Grass",
        abilityc: "Ability: Steelworker",
        itemc : "Item: None",
        hpc : "HP: 161",
        atkc : "Atk: 165",
        defc : "Def: 169",
        spatkc : "Sp. Atk: 115",
        spdefc : "Sp. Def: 157",
        spdc : "Spd: 63",
        move1c : "-Slam",
        move2c : "-Shadow Ball",
        move3c : "-Energy Ball",
        move4c : "-Whirlpool",

        named : "Froslass",
        leveld : "LV: 56",
        typed : "Type: Ice/Ghost",
        abilityd: "Ability: Snow Cloak",
        itemd : "Item: None",
        hpd : "HP: 161",
        atkd : "Atk: 108",
        defd : "Def: 97",
        spatkd : "Sp. Atk: 146",
        spdefd : "Sp. Def: 97",
        spdd : "Spd: 180",
        move1d : "-Blizzard",
        move2d : "-Shadow Ball",
        move3d : "-Confuse Ray",
        move4d : "-Ice Shard",

        namee : "Palossand",
        levele : "LV: 57",
        typee : "Type: Ghost/Ground",
        abilitye: "Ability: Water Compaction",
        iteme : "Item: Ghostium Z",
        hpe : "HP: 216",
        atke : "Atk: 104",
        defe : "Def: 144",
        spatke : "Sp. Atk: 172",
        spdefe : "Sp. Def: 107",
        spde : "Spd: 59",
        move1e : "-Shadow Ball",
        move2e : "-Earth Power",
        move3e : "-Giga Drain",
        move4e : "-Iron Defense",
    },

    {
        namea : "Braviary",
        levela : "LV: 56",
        typea : "Type: Normal/Flying",
        abilitya: "Ability: Sheer Force",
        itema : "Item: None",
        hpa : "HP: 194",
        atka : "Atk: 194",
        defa : "Def: 105",
        spatka : "Sp. Atk: 85",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 146",
        move1a : "-Crush Claw",
        move2a : "-Brave Bird",
        move3a : "-Air Slash",
        move4a : "-Scary Face",

        nameb : "Hawlucha",
        levelb : "LV: 56",
        typeb : "Type: Fighting/Flying",
        abilityb: "Ability: Mold Breaker",
        itemb : "Item: None",
        hpb : "HP: 170",
        atkb : "Atk: 160",
        defb : "Def: 105",
        spatkb : "Sp. Atk: 104",
        spdefb : "Sp. Def: 92",
        spdb : "Spd: 189",
        move1b : "-Flying Press",
        move2b : "-Throat Chop",
        move3b : "-Dual Chop",
        move4b : "-Poison Jab",

        namec : "Oricorio (Baile)",
        levelc : "LV: 56",
        typec : "Type: Fire/Flying",
        abilityc: "Ability: Dancer",
        itemc : "Item: None",
        hpc : "HP: 166",
        atkc : "Atk: 100",
        defc : "Def: 100",
        spatkc : "Sp. Atk: 166",
        spdefc : "Sp. Def: 100",
        spdc : "Spd: 161",
        move1c : "-Revelation Dance",
        move2c : "-Teeter Dance",
        move3c : "-Air Slash",
        move4c : "-Feather Dance",

        named : "Mandibuzz",
        leveld : "LV: 56",
        typed : "Type: Dark/Flying",
        abilityd: "Ability: Big Pecks",
        itemd : "Item: None",
        hpd : "HP: 206",
        atkd : "Atk: 94",
        defd : "Def: 174",
        spatkd : "Sp. Atk: 83",
        spdefd : "Sp. Def: 163",
        spdd : "Spd: 111",
        move1d : "-Bone Rush",
        move2d : "-Brave Bird",
        move3d : "-Punishment",
        move4d : "-Flatter",

        namee : "Toucannon",
        levele : "LV: 57",
        typee : "Type: Normal/Flying",
        abilitye: "Ability: Skill Link",
        iteme : "Item: Flyinium Z",
        hpe : "HP: 175",
        atke : "Atk: 194",
        defe : "Def: 107",
        spatke : "Sp. Atk: 107",
        spdefe : "Sp. Def: 107",
        spde : "Spd: 126",
        move1e : "-Bullet Seed",
        move2e : "-Rock Blast",
        move3e : "-Beak Blast",
        move4e : "-Screech",
    },

    {
        namea : "Raichu (Alolan)",
        levela : "LV: 59",
        typea : "Type: Electric/Psychic",
        abilitya: "Ability: Surge Surfer",
        itema : "Item: None",
        hpa : "HP: 157",
        atka : "Atk: 123",
        defa : "Def: 81",
        spatka : "Sp. Atk: 171",
        spdefa : "Sp. Def: 123",
        spda : "Spd: 189",
        move1a : "-Thunderbolt",
        move2a : "-Quick Attack",
        move3a : "-Psychic",
        move4a : "-Focus Blast",

        nameb : "Vaporeon",
        levelb : "LV: 58",
        typeb : "Type: Water",
        abilityb: "Ability: Water Absorb",
        itemb : "Item: None",
        hpb : "HP: 236",
        atkb : "Atk: 97",
        defb : "Def: 92",
        spatkb : "Sp. Atk: 186",
        spdefb : "Sp. Def: 132",
        spdb : "Spd: 134",
        move1b : "-Hydro Pump",
        move2b : "-Quick Attack",
        move3b : "-Charm",
        move4b : "-Baby-Doll Eyes",

        namec : "Tauros",
        levelc : "LV: 58",
        typec : "Type: Normal",
        abilityc: "Ability: Intimidate",
        itemc : "Item: None",
        hpc : "HP: 172",
        atkc : "Atk: 174",
        defc : "Def: 132",
        spatkc : "Sp. Atk: 68",
        spdefc : "Sp. Def: 103",
        spdc : "Spd: 186",
        move1c : "-Zen Headbutt",
        move2c : "-Iron Head",
        move3c : "-Earthquake",
        move4c : "-Double-Edge",

        named : "Noivern",
        leveld : "LV: 58",
        typed : "Type: Flying/Dragon",
        abilityd: "Ability: Infiltrator",
        itemd : "Item: None",
        hpd : "HP: 184",
        atkd : "Atk: 94",
        defd : "Def: 115",
        spatkd : "Sp. Atk: 171",
        spdefd : "Sp. Def: 115",
        spdd : "Spd: 201",
        move1d : "-Dragon Pulse",
        move2d : "-Air Slash",
        move3d : "-Dark Pulse",
        move4d : "-Super Fang",

        namee : "Crabominable",
        levele : "LV: 59",
        typee : "Type: Fighting/Ice",
        abilitye: "Ability: Iron Fist",
        iteme : "Item: None",
        hpe : "HP: 201",
        atke : "Atk: 215",
        defe : "Def: 113",
        spatke : "Sp. Atk: 95",
        spdefe : "Sp. Def: 101",
        spde : "Spd: 110",
        move1e : "-Power-Up Punch",
        move2e : "-Ice Hammer",
        move3e : "-Stone Edge",
        move4e : "-Dizzy Punch",

        namef : "Decidueye",
        levelf : "LV: 60",
        typef : "Type: Grass/Ghost",
        abilityf: "Ability: Overgrow",
        itemf : "Item: Grassium Z",
        hpf : "HP: 219",
        atkf : "Atk: 189",
        deff : "Def: 113",
        spatkf : "Sp. Atk: 143",
        spdeff : "Sp. Def: 143",
        spdf : "Spd: 107",
        move1f : "-Spirit Shackle",
        move2f : "-Leaf Blade",
        move3f : "-Smack Down",
        move4f : "",
    },

    {
        namea : "Raichu (Alolan)",
        levela : "LV: 59",
        typea : "Type: Electric/Psychic",
        abilitya: "Ability: Surge Surfer",
        itema : "Item: None",
        hpa : "HP: 157",
        atka : "Atk: 123",
        defa : "Def: 81",
        spatka : "Sp. Atk: 171",
        spdefa : "Sp. Def: 123",
        spda : "Spd: 189",
        move1a : "-Thunderbolt",
        move2a : "-Quick Attack",
        move3a : "-Psychic",
        move4a : "-Focus Blast",

        nameb : "Leafeon",
        levelb : "LV: 58",
        typeb : "Type: Grass",
        abilityb: "Ability: Leaf Guard",
        itemb : "Item: None",
        hpb : "HP: 160",
        atkb : "Atk: 186",
        defb : "Def: 173",
        spatkb : "Sp. Atk: 92",
        spdefb : "Sp. Def: 97",
        spdb : "Spd: 169",
        move1b : "-Leaf Blade",
        move2b : "-Quick Attack",
        move3b : "-Charm",
        move4b : "-Baby-Doll Eyes",

        namec : "Tauros",
        levelc : "LV: 58",
        typec : "Type: Normal",
        abilityc: "Ability: Intimidate",
        itemc : "Item: None",
        hpc : "HP: 172",
        atkc : "Atk: 174",
        defc : "Def: 132",
        spatkc : "Sp. Atk: 68",
        spdefc : "Sp. Def: 103",
        spdc : "Spd: 186",
        move1c : "-Zen Headbutt",
        move2c : "-Iron Head",
        move3c : "-Earthquake",
        move4c : "-Double-Edge",

        named : "Noivern",
        leveld : "LV: 58",
        typed : "Type: Flying/Dragon",
        abilityd: "Ability: Infiltrator",
        itemd : "Item: None",
        hpd : "HP: 184",
        atkd : "Atk: 94",
        defd : "Def: 115",
        spatkd : "Sp. Atk: 171",
        spdefd : "Sp. Def: 115",
        spdd : "Spd: 201",
        move1d : "-Dragon Pulse",
        move2d : "-Air Slash",
        move3d : "-Dark Pulse",
        move4d : "-Super Fang",

        namee : "Crabominable",
        levele : "LV: 59",
        typee : "Type: Fighting/Ice",
        abilitye: "Ability: Iron Fist",
        iteme : "Item: None",
        hpe : "HP: 201",
        atke : "Atk: 215",
        defe : "Def: 113",
        spatke : "Sp. Atk: 95",
        spdefe : "Sp. Def: 101",
        spde : "Spd: 110",
        move1e : "-Power-Up Punch",
        move2e : "-Ice Hammer",
        move3e : "-Stone Edge",
        move4e : "-Dizzy Punch",

        namef : "Incineroar",
        levelf : "LV: 60",
        typef : "Type: Fire/Dark",
        abilityf: "Ability: Blaze",
        itemf : "Item: Firium Z",
        hpf : "HP: 239",
        atkf : "Atk: 198",
        deff : "Def: 131",
        spatkf : "Sp. Atk: 119",
        spdeff : "Sp. Def: 131",
        spdf : "Spd: 95",
        move1f : "-Darkest Lariat",
        move2f : "-Flare Blitz",
        move3f : "-Earthquake",
        move4f : "",
    },

    {
        namea : "Raichu (Alolan)",
        levela : "LV: 59",
        typea : "Type: Electric/Psychic",
        abilitya: "Ability: Surge Surfer",
        itema : "Item: None",
        hpa : "HP: 157",
        atka : "Atk: 123",
        defa : "Def: 81",
        spatka : "Sp. Atk: 171",
        spdefa : "Sp. Def: 123",
        spda : "Spd: 189",
        move1a : "-Thunderbolt",
        move2a : "-Quick Attack",
        move3a : "-Psychic",
        move4a : "-Focus Blast",

        nameb : "Flareon",
        levelb : "LV: 58",
        typeb : "Type: Fire",
        abilityb: "Ability: Flash Fire",
        itemb : "Item: None",
        hpb : "HP: 160",
        atkb : "Atk: 209",
        defb : "Def: 92",
        spatkb : "Sp. Atk: 132",
        spdefb : "Sp. Def: 150",
        spdb : "Spd: 134",
        move1b : "-Flare Blitz",
        move2b : "-Quick Attack",
        move3b : "-Charm",
        move4b : "-Baby-Doll Eyes",

        namec : "Tauros",
        levelc : "LV: 58",
        typec : "Type: Normal",
        abilityc: "Ability: Intimidate",
        itemc : "Item: None",
        hpc : "HP: 172",
        atkc : "Atk: 174",
        defc : "Def: 132",
        spatkc : "Sp. Atk: 68",
        spdefc : "Sp. Def: 103",
        spdc : "Spd: 186",
        move1c : "-Zen Headbutt",
        move2c : "-Iron Head",
        move3c : "-Earthquake",
        move4c : "-Double-Edge",

        named : "Noivern",
        leveld : "LV: 58",
        typed : "Type: Flying/Dragon",
        abilityd: "Ability: Infiltrator",
        itemd : "Item: None",
        hpd : "HP: 184",
        atkd : "Atk: 94",
        defd : "Def: 115",
        spatkd : "Sp. Atk: 171",
        spdefd : "Sp. Def: 115",
        spdd : "Spd: 201",
        move1d : "-Dragon Pulse",
        move2d : "-Air Slash",
        move3d : "-Dark Pulse",
        move4d : "-Super Fang",

        namee : "Crabominable",
        levele : "LV: 59",
        typee : "Type: Fighting/Ice",
        abilitye: "Ability: Iron Fist",
        iteme : "Item: None",
        hpe : "HP: 201",
        atke : "Atk: 215",
        defe : "Def: 113",
        spatke : "Sp. Atk: 95",
        spdefe : "Sp. Def: 101",
        spde : "Spd: 110",
        move1e : "-Power-Up Punch",
        move2e : "-Ice Hammer",
        move3e : "-Stone Edge",
        move4e : "-Dizzy Punch",

        namef : "Primarina",
        levelf : "LV: 60",
        typef : "Type: Water/Fairy",
        abilityf: "Ability: Torrent",
        itemf : "Item: Waterium Z",
        hpf : "HP: 221",
        atkf : "Atk: 111",
        deff : "Def: 111",
        spatkf : "Sp. Atk: 212",
        spdeff : "Sp. Def: 162",
        spdf : "Spd: 95",
        move1f : "-Sparkling Aria",
        move2f : "-Moonblast",
        move3f : "-Hyper Voice",
        move4f : "",
    },

    {
        namea : "Mightyena",
        levela : "LV: 64",
        typea : "Type: Dark",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 179",
        atka : "Atk: 176",
        defa : "Def: 150",
        spatka : "Sp. Atk: 97",
        spdefa : "Sp. Def: 97",
        spda : "Spd: 110",
        move1a : "-Crunch",
        move2a : "-Fire Fang",
        move3a : "-Thunder Fang",
        move4a : "-Ice Fang",

        nameb : "Crobat",
        levelb : "LV: 64",
        typeb : "Type: Poison/Flying",
        abilityb: "Ability: Inner Focus",
        itemb : "Item: None",
        hpb : "HP: 198",
        atkb : "Atk: 136",
        defb : "Def: 123",
        spatkb : "Sp. Atk: 150",
        spdefb : "Sp. Def: 123",
        spdb : "Spd: 227",
        move1b : "-Air Slash",
        move2b : "-Sludge Bomb",
        move3b : "-Toxic",
        move4b : "-Dark Pulse",

        namec : "Weezing",
        levelc : "LV: 64",
        typec : "Type: Poison",
        abilityc: "Ability: Levitate",
        itemc : "Item: None",
        hpc : "HP: 173",
        atkc : "Atk: 136",
        defc : "Def: 214",
        spatkc : "Sp. Atk: 129",
        spdefc : "Sp. Def: 150",
        spdc : "Spd: 97",
        move1c : "-Sludge Bomb",
        move2c : "-Thunderbolt",
        move3c : "-Shadow Ball",
        move4c : "-Pain Split",

        named : "Camerupt",
        leveld : "LV: 64",
        typed : "Type: Fire/Ground",
        abilityd: "Ability: Magma Armor",
        itemd : "Item: None",
        hpd : "HP: 179",
        atkd : "Atk: 189",
        defd : "Def: 110",
        spatkd : "Sp. Atk: 195",
        spdefd : "Sp. Def: 117",
        spdd : "Spd: 72",
        move1d : "-Flamethrower",
        move2d : "-Earthquake",
        move3d : "-Stone Edge",
        move4d : "-Flash Cannon",

        namee : "Groudon",
        levele : "LV: 66",
        typee : "Type: Ground",
        abilitye: "Ability: Drought",
        iteme : "Item: None",
        hpe : "HP: 227",
        atke : "Atk: 264",
        defe : "Def: 251",
        spatke : "Sp. Atk: 156",
        spdefe : "Sp. Def: 143",
        spde : "Spd: 143",
        move1e : "-Earthquake",
        move2e : "-Flamethrower",
        move3e : "-Ancient Power",
        move4e : "-Solar Beam",
    },

    {
        namea : "Mightyena",
        levela : "LV: 64",
        typea : "Type: Dark",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 179",
        atka : "Atk: 176",
        defa : "Def: 150",
        spatka : "Sp. Atk: 97",
        spdefa : "Sp. Def: 97",
        spda : "Spd: 110",
        move1a : "-Crunch",
        move2a : "-Fire Fang",
        move3a : "-Thunder Fang",
        move4a : "-Ice Fang",

        nameb : "Crobat",
        levelb : "LV: 64",
        typeb : "Type: Poison/Flying",
        abilityb: "Ability: Inner Focus",
        itemb : "Item: None",
        hpb : "HP: 198",
        atkb : "Atk: 136",
        defb : "Def: 123",
        spatkb : "Sp. Atk: 150",
        spdefb : "Sp. Def: 123",
        spdb : "Spd: 227",
        move1b : "-Air Slash",
        move2b : "-Sludge Bomb",
        move3b : "-Toxic",
        move4b : "-Dark Pulse",

        namec : "Muk",
        levelc : "LV: 64",
        typec : "Type: Poison",
        abilityc: "Ability: Poison Tough",
        itemc : "Item: None",
        hpc : "HP: 224",
        atkc : "Atk: 195",
        defc : "Def: 117",
        spatkc : "Sp. Atk: 104",
        spdefc : "Sp. Def: 189",
        spdc : "Spd: 85",
        move1c : "-Gunk Shot",
        move2c : "-Fire Punch",
        move3c : "-Ice Punch",
        move4c : "-Thunder Punch",

        named : "Sharpedo",
        leveld : "LV: 64",
        typed : "Type: Water/Dark",
        abilityd: "Ability: Rough Skin",
        itemd : "Item: None",
        hpd : "HP: 179",
        atkd : "Atk: 214",
        defd : "Def: 72",
        spatkd : "Sp. Atk: 142",
        spdefd : "Sp. Def: 72",
        spdd : "Spd: 182",
        move1d : "-Liquidation",
        move2d : "-Night Slash",
        move3d : "-Ice Fang",
        move4d : "-Poison Fang",

        namee : "Kyogre",
        levele : "LV: 66",
        typee : "Type: Water",
        abilitye: "Ability: Drizzle",
        iteme : "Item: None",
        hpe : "HP: 227",
        atke : "Atk: 156",
        defe : "Def: 143",
        spatke : "Sp. Atk: 264",
        spdefe : "Sp. Def: 251",
        spde : "Spd: 143",
        move1e : "-Hydro Pump",
        move2e : "-Ice Beam",
        move3e : "-Ancient Power",
        move4e : "-Thunder",
    },

    {
        namea : "Houndoom",
        levela : "LV: 65",
        typea : "Type: Dark/Fire",
        abilitya: "Ability: Early Bird",
        itema : "Item: None",
        hpa : "HP: 188",
        atka : "Atk: 138",
        defa : "Def: 86",
        spatka : "Sp. Atk: 205",
        spdefa : "Sp. Def: 125",
        spda : "Spd: 185",
        move1a : "-Fire Blast",
        move2a : "-Dark Pulse",
        move3a : "-Sludge Bomb",
        move4a : "-Shadow Ball",

        nameb : "Honchkrow",
        levelb : "LV: 65",
        typeb : "Type: Dark/Flying",
        abilityb: "Ability: Insomnia",
        itemb : "Item: None",
        hpb : "HP: 221",
        atkb : "Atk: 224",
        defb : "Def: 88",
        spatkb : "Sp. Atk: 198",
        spdefb : "Sp. Def: 88",
        spdb : "Spd: 113",
        move1b : "-Night Slash",
        move2b : "-Sky Attack",
        move3b : "-Heat Wave",
        move4b : "-Icy Wind",

        namec : "Crobat",
        levelc : "LV: 65",
        typec : "Type: Poison/Flying",
        abilityc: "Ability: Inner Focus",
        itemc : "Item: None",
        hpc : "HP: 201",
        atkc : "Atk: 179",
        defc : "Def: 125",
        spatkc : "Sp. Atk: 112",
        spdefc : "Sp. Def: 125",
        spdc : "Spd: 231",
        move1c : "-Cross Poison",
        move2c : "-Zen Headbutt",
        move3c : "-X-Scissor",
        move4c : "-Super Fang",

        named : "Weavile",
        leveld : "LV: 65",
        typed : "Type: Dark/Ice",
        abilityd: "Ability: Pressure",
        itemd : "Item: None",
        hpd : "HP: 182",
        atkd : "Atk: 218",
        defd : "Def: 105",
        spatkd : "Sp. Atk: 79",
        spdefd : "Sp. Def: 131",
        spdd : "Spd: 224",
        move1d : "-Night Slash",
        move2d : "-Ice Punch",
        move3d : "-Quick Attack",
        move4d : "-Brick Break",

        namee : "Dialga",
        levele : "LV: 67",
        typee : "Type: Steel/Dragon",
        abilitye: "Ability: Pressure",
        iteme : "Item: None",
        hpe : "HP: 273",
        atke : "Atk: 185",
        defe : "Def: 185",
        spatke : "Sp. Atk: 268",
        spdefe : "Sp. Def: 159",
        spde : "Spd: 145",
        move1e : "-Roar of Time",
        move2e : "-Flash Cannon",
        move3e : "-Earth Power",
        move4e : "-Thunderbolt",
    },

    {
        namea : "Houndoom",
        levela : "LV: 65",
        typea : "Type: Dark/Fire",
        abilitya: "Ability: Early Bird",
        itema : "Item: None",
        hpa : "HP: 188",
        atka : "Atk: 138",
        defa : "Def: 86",
        spatka : "Sp. Atk: 205",
        spdefa : "Sp. Def: 125",
        spda : "Spd: 185",
        move1a : "-Fire Blast",
        move2a : "-Dark Pulse",
        move3a : "-Sludge Bomb",
        move4a : "-Shadow Ball",

        nameb : "Honchkrow",
        levelb : "LV: 65",
        typeb : "Type: Dark/Flying",
        abilityb: "Ability: Insomnia",
        itemb : "Item: None",
        hpb : "HP: 221",
        atkb : "Atk: 224",
        defb : "Def: 88",
        spatkb : "Sp. Atk: 198",
        spdefb : "Sp. Def: 88",
        spdb : "Spd: 113",
        move1b : "-Night Slash",
        move2b : "-Sky Attack",
        move3b : "-Heat Wave",
        move4b : "-Icy Wind",

        namec : "Crobat",
        levelc : "LV: 65",
        typec : "Type: Poison/Flying",
        abilityc: "Ability: Inner Focus",
        itemc : "Item: None",
        hpc : "HP: 201",
        atkc : "Atk: 179",
        defc : "Def: 125",
        spatkc : "Sp. Atk: 112",
        spdefc : "Sp. Def: 125",
        spdc : "Spd: 231",
        move1c : "-Cross Poison",
        move2c : "-Zen Headbutt",
        move3c : "-X-Scissor",
        move4c : "-Super Fang",

        named : "Weavile",
        leveld : "LV: 65",
        typed : "Type: Dark/Ice",
        abilityd: "Ability: Pressure",
        itemd : "Item: None",
        hpd : "HP: 182",
        atkd : "Atk: 218",
        defd : "Def: 105",
        spatkd : "Sp. Atk: 79",
        spdefd : "Sp. Def: 131",
        spdd : "Spd: 224",
        move1d : "-Night Slash",
        move2d : "-Ice Punch",
        move3d : "-Quick Attack",
        move4d : "-Brick Break",

        namee : "Palkia",
        levele : "LV: 67",
        typee : "Type: Water/Dragon",
        abilitye: "Ability: Pressure",
        iteme : "Item: None",
        hpe : "HP: 259",
        atke : "Atk: 185",
        defe : "Def: 159",
        spatke : "Sp. Atk: 268",
        spdefe : "Sp. Def: 185",
        spde : "Spd: 159",
        move1e : "-Spacial Rend",
        move2e : "-Surf",
        move3e : "-Earth Power",
        move4e : "-Thunderbolt",
    },

    {
        namea : "Mienshao",
        levela : "LV: 65",
        typea : "Type: Fighting",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 175",
        atka : "Atk: 224",
        defa : "Def: 99",
        spatka : "Sp. Atk: 144",
        spdefa : "Sp. Def: 99",
        spda : "Spd: 198",
        move1a : "-Fake Out",
        move2a : "-High Jump Kick",
        move3a : "-U-Turn",
        move4a : "-Dual Chop",

        nameb : "Honchkrow",
        levelb : "LV: 65",
        typeb : "Type: Dark/Flying",
        abilityb: "Ability: Insomnia",
        itemb : "Item: None",
        hpb : "HP: 221",
        atkb : "Atk: 183",
        defb : "Def: 88",
        spatkb : "Sp. Atk: 198",
        spdefb : "Sp. Def: 88",
        spdb : "Spd: 154",
        move1b : "-Dark Pulse",
        move2b : "-Heat Wave",
        move3b : "-Psychic",
        move4b : "-Shadow Ball",

        namec : "Pyroar",
        levelc : "LV: 65",
        typec : "Type: Fire/Normal",
        abilityc: "Ability: Rivalry",
        itemc : "Item: None",
        hpc : "HP: 203",
        atkc : "Atk: 109",
        defc : "Def: 114",
        spatkc : "Sp. Atk: 203",
        spdefc : "Sp. Def: 107",
        spdc : "Spd: 200",
        move1c : "-Flamethrower",
        move2c : "-Hyper Voice",
        move3c : "-Will-O-Wisp",
        move4c : "-Snarl",

        named : "Mega Gyarados",
        leveld : "LV: 65",
        typed : "Type: Water/Dark",
        abilityd: "Ability: Mold Breaker",
        itemd : "Item: Gyaradosite",
        hpd : "HP: 214",
        atkd : "Atk: 263",
        defd : "Def: 162",
        spatkd : "Sp. Atk: 112",
        spdefd : "Sp. Def: 190",
        spdd : "Spd: 167",
        move1d : "-Waterfall",
        move2d : "-Crunch",
        move3d : "-Stone Edge",
        move4d : "-Earthquake",

        namee : "Xerneas",
        levele : "LV: 67",
        typee : "Type: Fairy",
        abilitye: "Ability: Fairy Aura",
        iteme : "Item: None",
        hpe : "HP: 308",
        atke : "Atk: 200",
        defe : "Def: 152",
        spatke : "Sp. Atk: 242",
        spdefe : "Sp. Def: 156",
        spde : "Spd: 157",
        move1e : "-Geomancy",
        move2e : "-Moonblast",
        move3e : "-Thunderbolt",
        move4e : "-Psyshock",
    },

    {
        namea : "Mienshao",
        levela : "LV: 65",
        typea : "Type: Fighting",
        abilitya: "Ability: Inner Focus",
        itema : "Item: None",
        hpa : "HP: 175",
        atka : "Atk: 224",
        defa : "Def: 99",
        spatka : "Sp. Atk: 144",
        spdefa : "Sp. Def: 99",
        spda : "Spd: 198",
        move1a : "-Fake Out",
        move2a : "-High Jump Kick",
        move3a : "-U-Turn",
        move4a : "-Dual Chop",

        nameb : "Honchkrow",
        levelb : "LV: 65",
        typeb : "Type: Dark/Flying",
        abilityb: "Ability: Insomnia",
        itemb : "Item: None",
        hpb : "HP: 221",
        atkb : "Atk: 183",
        defb : "Def: 88",
        spatkb : "Sp. Atk: 198",
        spdefb : "Sp. Def: 88",
        spdb : "Spd: 154",
        move1b : "-Dark Pulse",
        move2b : "-Heat Wave",
        move3b : "-Psychic",
        move4b : "-Shadow Ball",

        namec : "Pyroar",
        levelc : "LV: 65",
        typec : "Type: Fire/Normal",
        abilityc: "Ability: Rivalry",
        itemc : "Item: None",
        hpc : "HP: 203",
        atkc : "Atk: 109",
        defc : "Def: 114",
        spatkc : "Sp. Atk: 203",
        spdefc : "Sp. Def: 107",
        spdc : "Spd: 200",
        move1c : "-Flamethrower",
        move2c : "-Hyper Voice",
        move3c : "-Will-O-Wisp",
        move4c : "-Snarl",

        named : "Mega Gyarados",
        leveld : "LV: 65",
        typed : "Type: Water/Dark",
        abilityd: "Ability: Mold Breaker",
        itemd : "Item: Gyaradosite",
        hpd : "HP: 214",
        atkd : "Atk: 263",
        defd : "Def: 162",
        spatkd : "Sp. Atk: 112",
        spdefd : "Sp. Def: 190",
        spdd : "Spd: 167",
        move1d : "-Waterfall",
        move2d : "-Crunch",
        move3d : "-Stone Edge",
        move4d : "-Earthquake",

        namee : "Yveltal",
        levele : "LV: 67",
        typee : "Type: Dark/Flying",
        abilitye: "Ability: Dark Aura",
        iteme : "Item: None",
        hpe : "HP: 308",
        atke : "Atk: 200",
        defe : "Def: 152",
        spatke : "Sp. Atk: 242",
        spdefe : "Sp. Def: 156",
        spde : "Spd: 157",
        move1e : "-Oblivion Wing",
        move2e : "-Air Slash",
        move3e : "-Psychic",
        move4e : "-Shadow Ball",
    },

    {
        namea : "Cofagrigus",
        levela : "LV: 66",
        typea : "Type: Ghost",
        abilitya: "Ability: Mummy",
        itema : "Item: None",
        hpa : "HP: 169",
        atka : "Atk: 87",
        defa : "Def: 254",
        spatka : "Sp. Atk: 146",
        spdefa : "Sp. Def: 201",
        spda : "Spd: 61",
        move1a : "-Will-O-Wisp",
        move2a : "-Shadow Ball",
        move3a : "-Dark Pulse",
        move4a : "-Power Split",

        nameb : "Bouffalant",
        levelb : "LV: 66",
        typeb : "Type: Normal",
        abilityb: "Ability: Reckless",
        itemb : "Item: None",
        hpb : "HP: 217",
        atkb : "Atk: 208",
        defb : "Def: 146",
        spatkb : "Sp. Atk: 74",
        spdefb : "Sp. Def: 146",
        spdb : "Spd: 135",
        move1b : "-Head Charge",
        move2b : "-Earthquake",
        move3b : "-Poison Jab",
        move4b : "-Megahorn",

        namec : "Bisharp",
        levelc : "LV: 66",
        typec : "Type: Dark/Steel",
        abilityc: "Ability: Defiant",
        itemc : "Item: None",
        hpc : "HP: 178",
        atkc : "Atk: 228",
        defc : "Def: 195",
        spatkc : "Sp. Atk: 100",
        spdefc : "Sp. Def: 113",
        spdc : "Spd: 113",
        move1c : "-Night Slash",
        move2c : "-Iron Head",
        move3c : "-X-Scissor",
        move4c : "-Stone Edge",

        named : "Hydreigon",
        leveld : "LV: 66",
        typed : "Type: Dark/Dragon",
        abilityd: "Ability: Levitate",
        itemd : "Item: None",
        hpd : "HP: 213",
        atkd : "Atk: 160",
        defd : "Def: 140",
        spatkd : "Sp. Atk: 228",
        spdefd : "Sp. Def: 140",
        spdd : "Spd: 192",
        move1d : "-Dark Pulse",
        move2d : "-Dragon Pulse",
        move3d : "-Surf",
        move4d : "-Hyper Voice",

        namee : "Zekrom",
        levele : "LV: 68",
        typee : "Type: Dragon/Electric",
        abilitye: "Ability: Teravolt",
        iteme : "Item: None",
        hpe : "HP: 234",
        atke : "Atk: 272",
        defe : "Def: 188",
        spatke : "Sp. Atk: 231",
        spdefe : "Sp. Def: 161",
        spde : "Spd: 147",
        move1e : "-Bolt Strike",
        move2e : "-Dragon Claw",
        move3e : "-Zen Headbutt",
        move4e : "-Hyper Voice",
    },

    {
        namea : "Cofagrigus",
        levela : "LV: 66",
        typea : "Type: Ghost",
        abilitya: "Ability: Mummy",
        itema : "Item: None",
        hpa : "HP: 169",
        atka : "Atk: 87",
        defa : "Def: 254",
        spatka : "Sp. Atk: 146",
        spdefa : "Sp. Def: 201",
        spda : "Spd: 61",
        move1a : "-Will-O-Wisp",
        move2a : "-Shadow Ball",
        move3a : "-Dark Pulse",
        move4a : "-Power Split",

        nameb : "Bouffalant",
        levelb : "LV: 66",
        typeb : "Type: Normal",
        abilityb: "Ability: Reckless",
        itemb : "Item: None",
        hpb : "HP: 217",
        atkb : "Atk: 208",
        defb : "Def: 146",
        spatkb : "Sp. Atk: 74",
        spdefb : "Sp. Def: 146",
        spdb : "Spd: 135",
        move1b : "-Head Charge",
        move2b : "-Earthquake",
        move3b : "-Poison Jab",
        move4b : "-Megahorn",

        namec : "Bisharp",
        levelc : "LV: 66",
        typec : "Type: Dark/Steel",
        abilityc: "Ability: Defiant",
        itemc : "Item: None",
        hpc : "HP: 178",
        atkc : "Atk: 228",
        defc : "Def: 195",
        spatkc : "Sp. Atk: 100",
        spdefc : "Sp. Def: 113",
        spdc : "Spd: 113",
        move1c : "-Night Slash",
        move2c : "-Iron Head",
        move3c : "-X-Scissor",
        move4c : "-Stone Edge",

        named : "Hydreigon",
        leveld : "LV: 66",
        typed : "Type: Dark/Dragon",
        abilityd: "Ability: Levitate",
        itemd : "Item: None",
        hpd : "HP: 213",
        atkd : "Atk: 160",
        defd : "Def: 140",
        spatkd : "Sp. Atk: 228",
        spdefd : "Sp. Def: 140",
        spdd : "Spd: 192",
        move1d : "-Dark Pulse",
        move2d : "-Dragon Pulse",
        move3d : "-Surf",
        move4d : "-Hyper Voice",

        namee : "Reshiram",
        levele : "LV: 68",
        typee : "Type: Dragon/Fire",
        abilitye: "Ability: Turboblaze",
        iteme : "Item: None",
        hpe : "HP: 234",
        atke : "Atk: 231",
        defe : "Def: 161",
        spatke : "Sp. Atk: 272",
        spdefe : "Sp. Def: 188",
        spde : "Spd: 147",
        move1e : "-Blue Flare",
        move2e : "-Dragon Claw",
        move3e : "-Zen Headbutt",
        move4e : "-Hyper Voice",
    },

    {
        namea : "Dugtrio",
        levela : "LV: 68",
        typea : "Type: Ground",
        abilitya: "Ability: Sand Veil",
        itema : "Item: Smooth Rock",
        hpa : "HP: 146",
        atka : "Atk: 204",
        defa : "Def: 93",
        spatka : "Sp. Atk: 93",
        spdefa : "Sp. Def: 120",
        spda : "Spd: 231",
        move1a : "-Stealth Rock",
        move2a : "-Earthquake",
        move3a : "-Sandstorm",
        move4a : "-Sucker Punch",

        nameb : "Nidoking",
        levelb : "LV: 68",
        typeb : "Type: Poison/Ground",
        abilityb: "Ability: Poison Point",
        itemb : "Item: None",
        hpb : "HP: 251",
        atkb : "Atk: 206",
        defb : "Def: 130",
        spatkb : "Sp. Atk: 141",
        spdefb : "Sp. Def: 127",
        spdb : "Spd: 141",
        move1b : "-Poison Jab",
        move2b : "-Earthquake",
        move3b : "-Throat Chop",
        move4b : "-Aqua Tail",

        namec : "Nidoqueen",
        levelc : "LV: 68",
        typec : "Type: Poison/Ground",
        abilityc: "Ability: Poison Point",
        itemc : "Item: None",
        hpc : "HP: 263",
        atkc : "Atk: 150",
        defc : "Def: 143",
        spatkc : "Sp. Atk: 170",
        spdefc : "Sp. Def: 141",
        spdc : "Spd: 128",
        move1c : "-Sludge Wave",
        move2c : "-Earth Power",
        move3c : "-Flamethrower",
        move4c : "-Surf",

        named : "Rhyperior",
        leveld : "LV: 68",
        typed : "Type: Ground/Rock",
        abilityd: "Ability: Lightning Rod",
        itemd : "Item: None",
        hpd : "HP: 254",
        atkd : "Atk: 258",
        defd : "Def: 245",
        spatkd : "Sp. Atk: 100",
        spdefd : "Sp. Def: 100",
        spdd : "Spd: 79",
        move1d : "-Stone Edge",
        move2d : "-Earthquake",
        move3d : "-Megahorn",
        move4d : "-Thunder Punch",

        namee : "Mega Mewtwo X",
        levele : "LV: 70",
        typee : "Type: Psychic/Fighting",
        abilitye: "Ability: Steadfast",
        iteme : "Item: Mewtwonite X",
        hpe : "HP: 249",
        atke : "Atk: 336",
        defe : "Def: 166",
        spatke : "Sp. Atk: 241",
        spdefe : "Sp. Def: 166",
        spde : "Spd: 252",
        move1e : "-Zen Headbutt",
        move2e : "-Drain Punch",
        move3e : "-Stone Edge",
        move4e : "-Earthquake",
    },

    {
        namea : "Dugtrio",
        levela : "LV: 68",
        typea : "Type: Ground",
        abilitya: "Ability: Sand Veil",
        itema : "Item: Smooth Rock",
        hpa : "HP: 146",
        atka : "Atk: 204",
        defa : "Def: 93",
        spatka : "Sp. Atk: 93",
        spdefa : "Sp. Def: 120",
        spda : "Spd: 231",
        move1a : "-Stealth Rock",
        move2a : "-Earthquake",
        move3a : "-Sandstorm",
        move4a : "-Sucker Punch",

        nameb : "Nidoking",
        levelb : "LV: 68",
        typeb : "Type: Poison/Ground",
        abilityb: "Ability: Poison Point",
        itemb : "Item: None",
        hpb : "HP: 251",
        atkb : "Atk: 206",
        defb : "Def: 130",
        spatkb : "Sp. Atk: 141",
        spdefb : "Sp. Def: 127",
        spdb : "Spd: 141",
        move1b : "-Poison Jab",
        move2b : "-Earthquake",
        move3b : "-Throat Chop",
        move4b : "-Aqua Tail",

        namec : "Nidoqueen",
        levelc : "LV: 68",
        typec : "Type: Poison/Ground",
        abilityc: "Ability: Poison Point",
        itemc : "Item: None",
        hpc : "HP: 263",
        atkc : "Atk: 150",
        defc : "Def: 143",
        spatkc : "Sp. Atk: 170",
        spdefc : "Sp. Def: 141",
        spdc : "Spd: 128",
        move1c : "-Sludge Wave",
        move2c : "-Earth Power",
        move3c : "-Flamethrower",
        move4c : "-Surf",

        named : "Rhyperior",
        leveld : "LV: 68",
        typed : "Type: Ground/Rock",
        abilityd: "Ability: Lightning Rod",
        itemd : "Item: None",
        hpd : "HP: 254",
        atkd : "Atk: 258",
        defd : "Def: 245",
        spatkd : "Sp. Atk: 100",
        spdefd : "Sp. Def: 100",
        spdd : "Spd: 79",
        move1d : "-Stone Edge",
        move2d : "-Earthquake",
        move3d : "-Megahorn",
        move4d : "-Thunder Punch",

        namee : "Mega Mewtwo Y",
        levele : "LV: 70",
        typee : "Type: Psychic",
        abilitye: "Ability: Insomnia",
        iteme : "Item: Mewtwonite Y",
        hpe : "HP: 249",
        atke : "Atk: 236",
        defe : "Def: 124",
        spatke : "Sp. Atk: 341",
        spdefe : "Sp. Def: 194",
        spde : "Spd: 266",
        move1e : "-Psystrike",
        move2e : "-Aura Sphere",
        move3e : "-Psychic",
        move4e : "-Ice Beam",
    },
]

function displayUSUMTrainers() {

    let newTrainerId = this.id;
    if (newTrainerId !== currentTrainerId) {
        currentTrainerId = newTrainerId;
        showUSUMImages(newTrainerId);
        showPokemonUSUMImages(newTrainerId);
    }


    let usumTrainer = this.dataset.member;

    document.querySelector('#name1').textContent = usum_trainers [usumTrainer].namea;
    document.querySelector('#level1').textContent = usum_trainers [usumTrainer].levela;
    document.querySelector('#type1').textContent = usum_trainers [usumTrainer].typea;
    document.querySelector('#ability1').textContent= usum_trainers [usumTrainer].abilitya;
    document.querySelector('#item1').textContent = usum_trainers [usumTrainer].itema;
    document.querySelector('#hp1').textContent = usum_trainers [usumTrainer].hpa;
    document.querySelector('#atk1').textContent = usum_trainers [usumTrainer].atka;
    document.querySelector('#def1').textContent = usum_trainers [usumTrainer].defa;
    document.querySelector('#spatk1').textContent = usum_trainers [usumTrainer].spatka;
    document.querySelector('#spdef1').textContent = usum_trainers [usumTrainer].spdefa;
    document.querySelector('#spd1').textContent = usum_trainers [usumTrainer].spda;
    document.querySelector('#move1_1').textContent = usum_trainers [usumTrainer].move1a;
    document.querySelector('#move2_1').textContent = usum_trainers [usumTrainer].move2a;
    document.querySelector('#move3_1').textContent = usum_trainers [usumTrainer].move3a;
    document.querySelector('#move4_1').textContent = usum_trainers [usumTrainer].move4a;

    
    document.querySelector('#name2').textContent = usum_trainers [usumTrainer].nameb;
    document.querySelector('#level2').textContent = usum_trainers [usumTrainer].levelb;
    document.querySelector('#type2').textContent = usum_trainers [usumTrainer].typeb;
    document.querySelector('#ability2').textContent= usum_trainers [usumTrainer].abilityb;
    document.querySelector('#item2').textContent = usum_trainers [usumTrainer].itemb;
    document.querySelector('#hp2').textContent = usum_trainers [usumTrainer].hpb;
    document.querySelector('#atk2').textContent = usum_trainers [usumTrainer].atkb;
    document.querySelector('#def2').textContent = usum_trainers [usumTrainer].defb;
    document.querySelector('#spatk2').textContent = usum_trainers [usumTrainer].spatkb;
    document.querySelector('#spdef2').textContent = usum_trainers [usumTrainer].spdefb;
    document.querySelector('#spd2').textContent = usum_trainers [usumTrainer].spdb;
    document.querySelector('#move1_2').textContent = usum_trainers [usumTrainer].move1b;
    document.querySelector('#move2_2').textContent = usum_trainers [usumTrainer].move2b;
    document.querySelector('#move3_2').textContent = usum_trainers [usumTrainer].move3b;
    document.querySelector('#move4_2').textContent = usum_trainers [usumTrainer].move4b;

    document.querySelector('#name3').textContent = usum_trainers [usumTrainer].namec;
    document.querySelector('#level3').textContent = usum_trainers [usumTrainer].levelc;
    document.querySelector('#type3').textContent = usum_trainers [usumTrainer].typec;
    document.querySelector('#ability3').textContent= usum_trainers [usumTrainer].abilityc;
    document.querySelector('#item3').textContent = usum_trainers [usumTrainer].itemc;
    document.querySelector('#hp3').textContent = usum_trainers [usumTrainer].hpc;
    document.querySelector('#atk3').textContent = usum_trainers [usumTrainer].atkc;
    document.querySelector('#def3').textContent = usum_trainers [usumTrainer].defc;
    document.querySelector('#spatk3').textContent = usum_trainers [usumTrainer].spatkc;
    document.querySelector('#spdef3').textContent = usum_trainers [usumTrainer].spdefc;
    document.querySelector('#spd3').textContent = usum_trainers [usumTrainer].spdc;
    document.querySelector('#move1_3').textContent = usum_trainers [usumTrainer].move1c;
    document.querySelector('#move2_3').textContent = usum_trainers [usumTrainer].move2c;
    document.querySelector('#move3_3').textContent = usum_trainers [usumTrainer].move3c;
    document.querySelector('#move4_3').textContent = usum_trainers [usumTrainer].move4c;

    document.querySelector('#name4').textContent = usum_trainers [usumTrainer].named;
    document.querySelector('#level4').textContent = usum_trainers [usumTrainer].leveld;
    document.querySelector('#type4').textContent = usum_trainers [usumTrainer].typed;
    document.querySelector('#ability4').textContent= usum_trainers [usumTrainer].abilityd;
    document.querySelector('#item4').textContent = usum_trainers [usumTrainer].itemd;
    document.querySelector('#hp4').textContent = usum_trainers [usumTrainer].hpd;
    document.querySelector('#atk4').textContent = usum_trainers [usumTrainer].atkd;
    document.querySelector('#def4').textContent = usum_trainers [usumTrainer].defd;
    document.querySelector('#spatk4').textContent = usum_trainers [usumTrainer].spatkd;
    document.querySelector('#spdef4').textContent = usum_trainers [usumTrainer].spdefd;
    document.querySelector('#spd4').textContent = usum_trainers [usumTrainer].spdd;
    document.querySelector('#move1_4').textContent = usum_trainers [usumTrainer].move1d;
    document.querySelector('#move2_4').textContent = usum_trainers [usumTrainer].move2d;
    document.querySelector('#move3_4').textContent = usum_trainers [usumTrainer].move3d;
    document.querySelector('#move4_4').textContent = usum_trainers [usumTrainer].move4d;

    document.querySelector('#name5').textContent = usum_trainers [usumTrainer].namee;
    document.querySelector('#level5').textContent = usum_trainers [usumTrainer].levele;
    document.querySelector('#type5').textContent = usum_trainers [usumTrainer].typee;
    document.querySelector('#ability5').textContent= usum_trainers [usumTrainer].abilitye;
    document.querySelector('#item5').textContent = usum_trainers [usumTrainer].iteme;
    document.querySelector('#hp5').textContent = usum_trainers [usumTrainer].hpe;
    document.querySelector('#atk5').textContent = usum_trainers [usumTrainer].atke;
    document.querySelector('#def5').textContent = usum_trainers [usumTrainer].defe;
    document.querySelector('#spatk5').textContent = usum_trainers [usumTrainer].spatke;
    document.querySelector('#spdef5').textContent = usum_trainers [usumTrainer].spdefe;
    document.querySelector('#spd5').textContent = usum_trainers [usumTrainer].spde;
    document.querySelector('#move1_5').textContent = usum_trainers [usumTrainer].move1e;
    document.querySelector('#move2_5').textContent = usum_trainers [usumTrainer].move2e;
    document.querySelector('#move3_5').textContent = usum_trainers [usumTrainer].move3e;
    document.querySelector('#move4_5').textContent = usum_trainers [usumTrainer].move4e;

    document.querySelector('#name6').textContent = usum_trainers [usumTrainer].namef;
    document.querySelector('#level6').textContent = usum_trainers [usumTrainer].levelf;
    document.querySelector('#type6').textContent = usum_trainers [usumTrainer].typef;
    document.querySelector('#ability6').textContent= usum_trainers [usumTrainer].abilityf;
    document.querySelector('#item6').textContent = usum_trainers [usumTrainer].itemf;
    document.querySelector('#hp6').textContent = usum_trainers [usumTrainer].hpf;
    document.querySelector('#atk6').textContent = usum_trainers [usumTrainer].atkf;
    document.querySelector('#def6').textContent = usum_trainers [usumTrainer].deff;
    document.querySelector('#spatk6').textContent = usum_trainers [usumTrainer].spatkf;
    document.querySelector('#spdef6').textContent = usum_trainers [usumTrainer].spdeff;
    document.querySelector('#spd6').textContent = usum_trainers [usumTrainer].spdf;
    document.querySelector('#move1_6').textContent = usum_trainers [usumTrainer].move1f;
    document.querySelector('#move2_6').textContent = usum_trainers [usumTrainer].move2f;
    document.querySelector('#move3_6').textContent = usum_trainers [usumTrainer].move3f;
    document.querySelector('#move4_6').textContent = usum_trainers [usumTrainer].move4f;
}

function showUSUMImages(trainerId) {
    var trainerPicture = document.querySelector("#trainer_image");
    
    trainerPicture.innerHTML = "";

    var imgTrainer = document.createElement("img");
    imgTrainer.src = "images/trainers/usum/" + trainerId + ".png";
    trainerPicture.appendChild(imgTrainer);
}

function showPokemonUSUMImages(trainerId) {
    var pokemon1Picture = document.querySelector("#pokemon_1_image");
    var pokemon2Picture = document.querySelector("#pokemon_2_image");
    var pokemon3Picture = document.querySelector("#pokemon_3_image");
    var pokemon4Picture = document.querySelector("#pokemon_4_image");
    var pokemon5Picture = document.querySelector("#pokemon_5_image");
    var pokemon6Picture = document.querySelector("#pokemon_6_image");
    var imgPokemon1 = document.createElement("img");
    var imgPokemon2 = document.createElement("img");
    var imgPokemon3 = document.createElement("img");
    var imgPokemon4 = document.createElement("img");
    var imgPokemon5 = document.createElement("img");
    var imgPokemon6 = document.createElement("img");
    
    pokemon1Picture.innerHTML = "";
    pokemon2Picture.innerHTML = "";
    pokemon3Picture.innerHTML = "";
    pokemon4Picture.innerHTML = "";
    pokemon5Picture.innerHTML = "";
    pokemon6Picture.innerHTML = "";

    
    imgPokemon1.src = "images/pokemon/usum/" + trainerId + "_1.png";
    imgPokemon2.src = "images/pokemon/usum/" + trainerId + "_2.png";
    imgPokemon3.src = "images/pokemon/usum/" + trainerId + "_3.png";
    imgPokemon4.src = "images/pokemon/usum/" + trainerId + "_4.png";
    imgPokemon5.src = "images/pokemon/usum/" + trainerId + "_5.png";
    imgPokemon6.src = "images/pokemon/usum/" + trainerId + "_6.png";

    pokemon1Picture.appendChild(imgPokemon1);
    pokemon2Picture.appendChild(imgPokemon2);
    pokemon3Picture.appendChild(imgPokemon3);
    pokemon4Picture.appendChild(imgPokemon4);
    pokemon5Picture.appendChild(imgPokemon5);
    pokemon6Picture.appendChild(imgPokemon6);
}

halaUSUM.addEventListener('click', displayUSUMTrainers);
oliviaUSUM.addEventListener('click', displayUSUMTrainers);
guzmaSHUSUM.addEventListener('click', displayUSUMTrainers);
nanuUSUM.addEventListener('click', displayUSUMTrainers);
guzmaAHUSUM.addEventListener('click', displayUSUMTrainers);
lusamineUSUM.addEventListener('click', displayUSUMTrainers);
hapuUSUM.addEventListener('click', displayUSUMTrainers);
gladionGUSUM.addEventListener('click', displayUSUMTrainers);
gladionFUSUM.addEventListener('click', displayUSUMTrainers);
gladionWUSUM.addEventListener('click', displayUSUMTrainers);
molayneUSUM.addEventListener('click', displayUSUMTrainers);
oliviaE4USUM.addEventListener('click', displayUSUMTrainers);
acerolaUSUM.addEventListener('click', displayUSUMTrainers);
kahiliUSUM.addEventListener('click', displayUSUMTrainers);
hauGUSUM.addEventListener('click', displayUSUMTrainers);
hauFUSUM.addEventListener('click', displayUSUMTrainers);
hauWUSUM.addEventListener('click', displayUSUMTrainers);
maxieUSUM.addEventListener('click', displayUSUMTrainers);
archieUSUM.addEventListener('click', displayUSUMTrainers);
cyrusDUSUM.addEventListener('click', displayUSUMTrainers);
cyrusPUSUM.addEventListener('click', displayUSUMTrainers);
lysandreXUSUM.addEventListener('click', displayUSUMTrainers);
lysandreYUSUM.addEventListener('click', displayUSUMTrainers);
ghetsisZUSUM.addEventListener('click', displayUSUMTrainers);
ghetsisRUSUM.addEventListener('click', displayUSUMTrainers);
giovanniXUSUM.addEventListener('click', displayUSUMTrainers);
giovanniYUSUM.addEventListener('click', displayUSUMTrainers);